package:
  name: pyocct
  version: 7.4.0.0

source:
  path: ../..

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ cdt('libx11-devel') }}  # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('libxi-devel') }}  # [linux]
    - cmake
    - ninja

  host:
    - python
    - occt ==7.4.0
    - tbb-devel
    - smesh ==8.3.0.3  # [win]
    - pybind11
    - libclang ==10.0.0
    - clang ==10.0.0

  run:
    - python
    - wxpython
    - occt ==7.4.0
    - smesh ==8.3.0.3  # [win]

test:
  requires:
    - pytest
  source_files:
    - test
  commands:
    - pytest test -v

about:
  home: https://github.com/LaughlinResearch/pyOCCT
  license: LGPL2.1
  license_family: LGPL
  summary: Python bindings for OpenCASCADE
  description: Python bindings for OpenCASCADE geometry kernel
               and SMESH meshing library.
