package:
  name: pyocct
  version: "7.3.0.0"

source:
  path: ../..

build:
  number: 0
  features:
    - vc14 # [win]

requirements:
  build:
    - python
    - vc 14 # [win]
    - cmake
    - ninja
    - occt ==7.3.0
    - tbb-devel

  run:
    - python
    # - wxpython
    # - pyqt >=5
    - vc 14 # [win]
    - occt ==7.3.0

test:
  source_files:
    - test

about:
  home: https://github.com/LaughlinResearch/pyOCCT
  license: LGPL2.1
  license_family: LGPL
  summary: Python bindings for OpenCASCADE
  description: Python bindings for OpenCASCADE geometry kernel
               and SMESH meshing library.
