package:
  name: pyocct
  version: 7.5.1.0

source:
  path: ../..

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}          #  [win]
    - cmake
    - ninja
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('libxi-devel') }}       # [linux]
    - {{ cdt('libxext-devel') }}     # [linux]

  host:
    - python
    - pybind11
    - occt ==7.5.1
    - tbb-devel

  run:
    - python
    - occt ==7.5.1

test:
  source_files:
    - test

about:
  home: https://github.com/trelau/pyOCCT
  license: LGPL2.1
  license_family: LGPL
  summary: Python bindings for OpenCASCADE.
  description: Python bindings for OpenCASCADE geometry kernel.
