/*
This file is part of pyOCCT which provides Python bindings to the OpenCASCADE
geometry kernel.

Copyright (C) 2016-2018  Laughlin Research, LLC
Copyright (C) 2019 Trevor Laughlin and the pyOCCT contributors

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
*/
#include <pyOCCT_Common.hxx>
#include <Message_Status.hxx>

void bind_Message_Status(py::module &mod){

py::enum_<Message_Status>(mod, "Message_Status", "Enumeration covering all execution statuses supported by the class Message_ExecStatus: 32 statuses per each of 4 types (DONE, WARN, ALARM, FAIL)")
	.value("Message_None", Message_Status::Message_None)
	.value("Message_Done1", Message_Status::Message_Done1)
	.value("Message_Done2", Message_Status::Message_Done2)
	.value("Message_Done3", Message_Status::Message_Done3)
	.value("Message_Done4", Message_Status::Message_Done4)
	.value("Message_Done5", Message_Status::Message_Done5)
	.value("Message_Done6", Message_Status::Message_Done6)
	.value("Message_Done7", Message_Status::Message_Done7)
	.value("Message_Done8", Message_Status::Message_Done8)
	.value("Message_Done9", Message_Status::Message_Done9)
	.value("Message_Done10", Message_Status::Message_Done10)
	.value("Message_Done11", Message_Status::Message_Done11)
	.value("Message_Done12", Message_Status::Message_Done12)
	.value("Message_Done13", Message_Status::Message_Done13)
	.value("Message_Done14", Message_Status::Message_Done14)
	.value("Message_Done15", Message_Status::Message_Done15)
	.value("Message_Done16", Message_Status::Message_Done16)
	.value("Message_Done17", Message_Status::Message_Done17)
	.value("Message_Done18", Message_Status::Message_Done18)
	.value("Message_Done19", Message_Status::Message_Done19)
	.value("Message_Done20", Message_Status::Message_Done20)
	.value("Message_Done21", Message_Status::Message_Done21)
	.value("Message_Done22", Message_Status::Message_Done22)
	.value("Message_Done23", Message_Status::Message_Done23)
	.value("Message_Done24", Message_Status::Message_Done24)
	.value("Message_Done25", Message_Status::Message_Done25)
	.value("Message_Done26", Message_Status::Message_Done26)
	.value("Message_Done27", Message_Status::Message_Done27)
	.value("Message_Done28", Message_Status::Message_Done28)
	.value("Message_Done29", Message_Status::Message_Done29)
	.value("Message_Done30", Message_Status::Message_Done30)
	.value("Message_Done31", Message_Status::Message_Done31)
	.value("Message_Done32", Message_Status::Message_Done32)
	.value("Message_Warn1", Message_Status::Message_Warn1)
	.value("Message_Warn2", Message_Status::Message_Warn2)
	.value("Message_Warn3", Message_Status::Message_Warn3)
	.value("Message_Warn4", Message_Status::Message_Warn4)
	.value("Message_Warn5", Message_Status::Message_Warn5)
	.value("Message_Warn6", Message_Status::Message_Warn6)
	.value("Message_Warn7", Message_Status::Message_Warn7)
	.value("Message_Warn8", Message_Status::Message_Warn8)
	.value("Message_Warn9", Message_Status::Message_Warn9)
	.value("Message_Warn10", Message_Status::Message_Warn10)
	.value("Message_Warn11", Message_Status::Message_Warn11)
	.value("Message_Warn12", Message_Status::Message_Warn12)
	.value("Message_Warn13", Message_Status::Message_Warn13)
	.value("Message_Warn14", Message_Status::Message_Warn14)
	.value("Message_Warn15", Message_Status::Message_Warn15)
	.value("Message_Warn16", Message_Status::Message_Warn16)
	.value("Message_Warn17", Message_Status::Message_Warn17)
	.value("Message_Warn18", Message_Status::Message_Warn18)
	.value("Message_Warn19", Message_Status::Message_Warn19)
	.value("Message_Warn20", Message_Status::Message_Warn20)
	.value("Message_Warn21", Message_Status::Message_Warn21)
	.value("Message_Warn22", Message_Status::Message_Warn22)
	.value("Message_Warn23", Message_Status::Message_Warn23)
	.value("Message_Warn24", Message_Status::Message_Warn24)
	.value("Message_Warn25", Message_Status::Message_Warn25)
	.value("Message_Warn26", Message_Status::Message_Warn26)
	.value("Message_Warn27", Message_Status::Message_Warn27)
	.value("Message_Warn28", Message_Status::Message_Warn28)
	.value("Message_Warn29", Message_Status::Message_Warn29)
	.value("Message_Warn30", Message_Status::Message_Warn30)
	.value("Message_Warn31", Message_Status::Message_Warn31)
	.value("Message_Warn32", Message_Status::Message_Warn32)
	.value("Message_Alarm1", Message_Status::Message_Alarm1)
	.value("Message_Alarm2", Message_Status::Message_Alarm2)
	.value("Message_Alarm3", Message_Status::Message_Alarm3)
	.value("Message_Alarm4", Message_Status::Message_Alarm4)
	.value("Message_Alarm5", Message_Status::Message_Alarm5)
	.value("Message_Alarm6", Message_Status::Message_Alarm6)
	.value("Message_Alarm7", Message_Status::Message_Alarm7)
	.value("Message_Alarm8", Message_Status::Message_Alarm8)
	.value("Message_Alarm9", Message_Status::Message_Alarm9)
	.value("Message_Alarm10", Message_Status::Message_Alarm10)
	.value("Message_Alarm11", Message_Status::Message_Alarm11)
	.value("Message_Alarm12", Message_Status::Message_Alarm12)
	.value("Message_Alarm13", Message_Status::Message_Alarm13)
	.value("Message_Alarm14", Message_Status::Message_Alarm14)
	.value("Message_Alarm15", Message_Status::Message_Alarm15)
	.value("Message_Alarm16", Message_Status::Message_Alarm16)
	.value("Message_Alarm17", Message_Status::Message_Alarm17)
	.value("Message_Alarm18", Message_Status::Message_Alarm18)
	.value("Message_Alarm19", Message_Status::Message_Alarm19)
	.value("Message_Alarm20", Message_Status::Message_Alarm20)
	.value("Message_Alarm21", Message_Status::Message_Alarm21)
	.value("Message_Alarm22", Message_Status::Message_Alarm22)
	.value("Message_Alarm23", Message_Status::Message_Alarm23)
	.value("Message_Alarm24", Message_Status::Message_Alarm24)
	.value("Message_Alarm25", Message_Status::Message_Alarm25)
	.value("Message_Alarm26", Message_Status::Message_Alarm26)
	.value("Message_Alarm27", Message_Status::Message_Alarm27)
	.value("Message_Alarm28", Message_Status::Message_Alarm28)
	.value("Message_Alarm29", Message_Status::Message_Alarm29)
	.value("Message_Alarm30", Message_Status::Message_Alarm30)
	.value("Message_Alarm31", Message_Status::Message_Alarm31)
	.value("Message_Alarm32", Message_Status::Message_Alarm32)
	.value("Message_Fail1", Message_Status::Message_Fail1)
	.value("Message_Fail2", Message_Status::Message_Fail2)
	.value("Message_Fail3", Message_Status::Message_Fail3)
	.value("Message_Fail4", Message_Status::Message_Fail4)
	.value("Message_Fail5", Message_Status::Message_Fail5)
	.value("Message_Fail6", Message_Status::Message_Fail6)
	.value("Message_Fail7", Message_Status::Message_Fail7)
	.value("Message_Fail8", Message_Status::Message_Fail8)
	.value("Message_Fail9", Message_Status::Message_Fail9)
	.value("Message_Fail10", Message_Status::Message_Fail10)
	.value("Message_Fail11", Message_Status::Message_Fail11)
	.value("Message_Fail12", Message_Status::Message_Fail12)
	.value("Message_Fail13", Message_Status::Message_Fail13)
	.value("Message_Fail14", Message_Status::Message_Fail14)
	.value("Message_Fail15", Message_Status::Message_Fail15)
	.value("Message_Fail16", Message_Status::Message_Fail16)
	.value("Message_Fail17", Message_Status::Message_Fail17)
	.value("Message_Fail18", Message_Status::Message_Fail18)
	.value("Message_Fail19", Message_Status::Message_Fail19)
	.value("Message_Fail20", Message_Status::Message_Fail20)
	.value("Message_Fail21", Message_Status::Message_Fail21)
	.value("Message_Fail22", Message_Status::Message_Fail22)
	.value("Message_Fail23", Message_Status::Message_Fail23)
	.value("Message_Fail24", Message_Status::Message_Fail24)
	.value("Message_Fail25", Message_Status::Message_Fail25)
	.value("Message_Fail26", Message_Status::Message_Fail26)
	.value("Message_Fail27", Message_Status::Message_Fail27)
	.value("Message_Fail28", Message_Status::Message_Fail28)
	.value("Message_Fail29", Message_Status::Message_Fail29)
	.value("Message_Fail30", Message_Status::Message_Fail30)
	.value("Message_Fail31", Message_Status::Message_Fail31)
	.value("Message_Fail32", Message_Status::Message_Fail32)
	.export_values();


}