/*
This file is part of pyOCCT which provides Python bindings to the OpenCASCADE
geometry kernel.

Copyright (C) 2016-2018  Laughlin Research, LLC
Copyright (C) 2019 Trevor Laughlin and the pyOCCT contributors

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
*/
#include <pyOCCT_Common.hxx>
#include <Standard.hxx>
#include <Standard_TypeDef.hxx>
#include <TCollection_AsciiString.hxx>
#include <TColStd_SequenceOfAsciiString.hxx>
#include <StepData_EnumTool.hxx>

void bind_StepData_EnumTool(py::module &mod){

py::class_<StepData_EnumTool, std::unique_ptr<StepData_EnumTool, Deleter<StepData_EnumTool>>> cls_StepData_EnumTool(mod, "StepData_EnumTool", "This class gives a way of conversion between the value of an enumeration and its representation in STEP An enumeration corresponds to an integer with reserved values, which begin to 0 In STEP, it is represented by a name in capital letter and limited by two dots, e.g. .UNKNOWN.");

// Constructors
cls_StepData_EnumTool.def(py::init<>());
cls_StepData_EnumTool.def(py::init<const Standard_CString>(), py::arg("e0"));
cls_StepData_EnumTool.def(py::init<const Standard_CString, const Standard_CString>(), py::arg("e0"), py::arg("e1"));
cls_StepData_EnumTool.def(py::init<const Standard_CString, const Standard_CString, const Standard_CString>(), py::arg("e0"), py::arg("e1"), py::arg("e2"));
cls_StepData_EnumTool.def(py::init<const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString>(), py::arg("e0"), py::arg("e1"), py::arg("e2"), py::arg("e3"));
cls_StepData_EnumTool.def(py::init<const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString>(), py::arg("e0"), py::arg("e1"), py::arg("e2"), py::arg("e3"), py::arg("e4"));
cls_StepData_EnumTool.def(py::init<const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString>(), py::arg("e0"), py::arg("e1"), py::arg("e2"), py::arg("e3"), py::arg("e4"), py::arg("e5"));
cls_StepData_EnumTool.def(py::init<const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString>(), py::arg("e0"), py::arg("e1"), py::arg("e2"), py::arg("e3"), py::arg("e4"), py::arg("e5"), py::arg("e6"));
cls_StepData_EnumTool.def(py::init<const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString>(), py::arg("e0"), py::arg("e1"), py::arg("e2"), py::arg("e3"), py::arg("e4"), py::arg("e5"), py::arg("e6"), py::arg("e7"));
cls_StepData_EnumTool.def(py::init<const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString>(), py::arg("e0"), py::arg("e1"), py::arg("e2"), py::arg("e3"), py::arg("e4"), py::arg("e5"), py::arg("e6"), py::arg("e7"), py::arg("e8"));
cls_StepData_EnumTool.def(py::init<const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString>(), py::arg("e0"), py::arg("e1"), py::arg("e2"), py::arg("e3"), py::arg("e4"), py::arg("e5"), py::arg("e6"), py::arg("e7"), py::arg("e8"), py::arg("e9"));
cls_StepData_EnumTool.def(py::init<const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString>(), py::arg("e0"), py::arg("e1"), py::arg("e2"), py::arg("e3"), py::arg("e4"), py::arg("e5"), py::arg("e6"), py::arg("e7"), py::arg("e8"), py::arg("e9"), py::arg("e10"));
cls_StepData_EnumTool.def(py::init<const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString>(), py::arg("e0"), py::arg("e1"), py::arg("e2"), py::arg("e3"), py::arg("e4"), py::arg("e5"), py::arg("e6"), py::arg("e7"), py::arg("e8"), py::arg("e9"), py::arg("e10"), py::arg("e11"));
cls_StepData_EnumTool.def(py::init<const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString>(), py::arg("e0"), py::arg("e1"), py::arg("e2"), py::arg("e3"), py::arg("e4"), py::arg("e5"), py::arg("e6"), py::arg("e7"), py::arg("e8"), py::arg("e9"), py::arg("e10"), py::arg("e11"), py::arg("e12"));
cls_StepData_EnumTool.def(py::init<const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString>(), py::arg("e0"), py::arg("e1"), py::arg("e2"), py::arg("e3"), py::arg("e4"), py::arg("e5"), py::arg("e6"), py::arg("e7"), py::arg("e8"), py::arg("e9"), py::arg("e10"), py::arg("e11"), py::arg("e12"), py::arg("e13"));
cls_StepData_EnumTool.def(py::init<const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString>(), py::arg("e0"), py::arg("e1"), py::arg("e2"), py::arg("e3"), py::arg("e4"), py::arg("e5"), py::arg("e6"), py::arg("e7"), py::arg("e8"), py::arg("e9"), py::arg("e10"), py::arg("e11"), py::arg("e12"), py::arg("e13"), py::arg("e14"));
cls_StepData_EnumTool.def(py::init<const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString>(), py::arg("e0"), py::arg("e1"), py::arg("e2"), py::arg("e3"), py::arg("e4"), py::arg("e5"), py::arg("e6"), py::arg("e7"), py::arg("e8"), py::arg("e9"), py::arg("e10"), py::arg("e11"), py::arg("e12"), py::arg("e13"), py::arg("e14"), py::arg("e15"));
cls_StepData_EnumTool.def(py::init<const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString>(), py::arg("e0"), py::arg("e1"), py::arg("e2"), py::arg("e3"), py::arg("e4"), py::arg("e5"), py::arg("e6"), py::arg("e7"), py::arg("e8"), py::arg("e9"), py::arg("e10"), py::arg("e11"), py::arg("e12"), py::arg("e13"), py::arg("e14"), py::arg("e15"), py::arg("e16"));
cls_StepData_EnumTool.def(py::init<const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString>(), py::arg("e0"), py::arg("e1"), py::arg("e2"), py::arg("e3"), py::arg("e4"), py::arg("e5"), py::arg("e6"), py::arg("e7"), py::arg("e8"), py::arg("e9"), py::arg("e10"), py::arg("e11"), py::arg("e12"), py::arg("e13"), py::arg("e14"), py::arg("e15"), py::arg("e16"), py::arg("e17"));
cls_StepData_EnumTool.def(py::init<const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString>(), py::arg("e0"), py::arg("e1"), py::arg("e2"), py::arg("e3"), py::arg("e4"), py::arg("e5"), py::arg("e6"), py::arg("e7"), py::arg("e8"), py::arg("e9"), py::arg("e10"), py::arg("e11"), py::arg("e12"), py::arg("e13"), py::arg("e14"), py::arg("e15"), py::arg("e16"), py::arg("e17"), py::arg("e18"));
cls_StepData_EnumTool.def(py::init<const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString>(), py::arg("e0"), py::arg("e1"), py::arg("e2"), py::arg("e3"), py::arg("e4"), py::arg("e5"), py::arg("e6"), py::arg("e7"), py::arg("e8"), py::arg("e9"), py::arg("e10"), py::arg("e11"), py::arg("e12"), py::arg("e13"), py::arg("e14"), py::arg("e15"), py::arg("e16"), py::arg("e17"), py::arg("e18"), py::arg("e19"));
cls_StepData_EnumTool.def(py::init<const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString>(), py::arg("e0"), py::arg("e1"), py::arg("e2"), py::arg("e3"), py::arg("e4"), py::arg("e5"), py::arg("e6"), py::arg("e7"), py::arg("e8"), py::arg("e9"), py::arg("e10"), py::arg("e11"), py::arg("e12"), py::arg("e13"), py::arg("e14"), py::arg("e15"), py::arg("e16"), py::arg("e17"), py::arg("e18"), py::arg("e19"), py::arg("e20"));
cls_StepData_EnumTool.def(py::init<const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString>(), py::arg("e0"), py::arg("e1"), py::arg("e2"), py::arg("e3"), py::arg("e4"), py::arg("e5"), py::arg("e6"), py::arg("e7"), py::arg("e8"), py::arg("e9"), py::arg("e10"), py::arg("e11"), py::arg("e12"), py::arg("e13"), py::arg("e14"), py::arg("e15"), py::arg("e16"), py::arg("e17"), py::arg("e18"), py::arg("e19"), py::arg("e20"), py::arg("e21"));
cls_StepData_EnumTool.def(py::init<const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString>(), py::arg("e0"), py::arg("e1"), py::arg("e2"), py::arg("e3"), py::arg("e4"), py::arg("e5"), py::arg("e6"), py::arg("e7"), py::arg("e8"), py::arg("e9"), py::arg("e10"), py::arg("e11"), py::arg("e12"), py::arg("e13"), py::arg("e14"), py::arg("e15"), py::arg("e16"), py::arg("e17"), py::arg("e18"), py::arg("e19"), py::arg("e20"), py::arg("e21"), py::arg("e22"));
cls_StepData_EnumTool.def(py::init<const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString>(), py::arg("e0"), py::arg("e1"), py::arg("e2"), py::arg("e3"), py::arg("e4"), py::arg("e5"), py::arg("e6"), py::arg("e7"), py::arg("e8"), py::arg("e9"), py::arg("e10"), py::arg("e11"), py::arg("e12"), py::arg("e13"), py::arg("e14"), py::arg("e15"), py::arg("e16"), py::arg("e17"), py::arg("e18"), py::arg("e19"), py::arg("e20"), py::arg("e21"), py::arg("e22"), py::arg("e23"));
cls_StepData_EnumTool.def(py::init<const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString>(), py::arg("e0"), py::arg("e1"), py::arg("e2"), py::arg("e3"), py::arg("e4"), py::arg("e5"), py::arg("e6"), py::arg("e7"), py::arg("e8"), py::arg("e9"), py::arg("e10"), py::arg("e11"), py::arg("e12"), py::arg("e13"), py::arg("e14"), py::arg("e15"), py::arg("e16"), py::arg("e17"), py::arg("e18"), py::arg("e19"), py::arg("e20"), py::arg("e21"), py::arg("e22"), py::arg("e23"), py::arg("e24"));
cls_StepData_EnumTool.def(py::init<const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString>(), py::arg("e0"), py::arg("e1"), py::arg("e2"), py::arg("e3"), py::arg("e4"), py::arg("e5"), py::arg("e6"), py::arg("e7"), py::arg("e8"), py::arg("e9"), py::arg("e10"), py::arg("e11"), py::arg("e12"), py::arg("e13"), py::arg("e14"), py::arg("e15"), py::arg("e16"), py::arg("e17"), py::arg("e18"), py::arg("e19"), py::arg("e20"), py::arg("e21"), py::arg("e22"), py::arg("e23"), py::arg("e24"), py::arg("e25"));
cls_StepData_EnumTool.def(py::init<const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString>(), py::arg("e0"), py::arg("e1"), py::arg("e2"), py::arg("e3"), py::arg("e4"), py::arg("e5"), py::arg("e6"), py::arg("e7"), py::arg("e8"), py::arg("e9"), py::arg("e10"), py::arg("e11"), py::arg("e12"), py::arg("e13"), py::arg("e14"), py::arg("e15"), py::arg("e16"), py::arg("e17"), py::arg("e18"), py::arg("e19"), py::arg("e20"), py::arg("e21"), py::arg("e22"), py::arg("e23"), py::arg("e24"), py::arg("e25"), py::arg("e26"));
cls_StepData_EnumTool.def(py::init<const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString>(), py::arg("e0"), py::arg("e1"), py::arg("e2"), py::arg("e3"), py::arg("e4"), py::arg("e5"), py::arg("e6"), py::arg("e7"), py::arg("e8"), py::arg("e9"), py::arg("e10"), py::arg("e11"), py::arg("e12"), py::arg("e13"), py::arg("e14"), py::arg("e15"), py::arg("e16"), py::arg("e17"), py::arg("e18"), py::arg("e19"), py::arg("e20"), py::arg("e21"), py::arg("e22"), py::arg("e23"), py::arg("e24"), py::arg("e25"), py::arg("e26"), py::arg("e27"));
cls_StepData_EnumTool.def(py::init<const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString>(), py::arg("e0"), py::arg("e1"), py::arg("e2"), py::arg("e3"), py::arg("e4"), py::arg("e5"), py::arg("e6"), py::arg("e7"), py::arg("e8"), py::arg("e9"), py::arg("e10"), py::arg("e11"), py::arg("e12"), py::arg("e13"), py::arg("e14"), py::arg("e15"), py::arg("e16"), py::arg("e17"), py::arg("e18"), py::arg("e19"), py::arg("e20"), py::arg("e21"), py::arg("e22"), py::arg("e23"), py::arg("e24"), py::arg("e25"), py::arg("e26"), py::arg("e27"), py::arg("e28"));
cls_StepData_EnumTool.def(py::init<const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString>(), py::arg("e0"), py::arg("e1"), py::arg("e2"), py::arg("e3"), py::arg("e4"), py::arg("e5"), py::arg("e6"), py::arg("e7"), py::arg("e8"), py::arg("e9"), py::arg("e10"), py::arg("e11"), py::arg("e12"), py::arg("e13"), py::arg("e14"), py::arg("e15"), py::arg("e16"), py::arg("e17"), py::arg("e18"), py::arg("e19"), py::arg("e20"), py::arg("e21"), py::arg("e22"), py::arg("e23"), py::arg("e24"), py::arg("e25"), py::arg("e26"), py::arg("e27"), py::arg("e28"), py::arg("e29"));
cls_StepData_EnumTool.def(py::init<const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString>(), py::arg("e0"), py::arg("e1"), py::arg("e2"), py::arg("e3"), py::arg("e4"), py::arg("e5"), py::arg("e6"), py::arg("e7"), py::arg("e8"), py::arg("e9"), py::arg("e10"), py::arg("e11"), py::arg("e12"), py::arg("e13"), py::arg("e14"), py::arg("e15"), py::arg("e16"), py::arg("e17"), py::arg("e18"), py::arg("e19"), py::arg("e20"), py::arg("e21"), py::arg("e22"), py::arg("e23"), py::arg("e24"), py::arg("e25"), py::arg("e26"), py::arg("e27"), py::arg("e28"), py::arg("e29"), py::arg("e30"));
cls_StepData_EnumTool.def(py::init<const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString>(), py::arg("e0"), py::arg("e1"), py::arg("e2"), py::arg("e3"), py::arg("e4"), py::arg("e5"), py::arg("e6"), py::arg("e7"), py::arg("e8"), py::arg("e9"), py::arg("e10"), py::arg("e11"), py::arg("e12"), py::arg("e13"), py::arg("e14"), py::arg("e15"), py::arg("e16"), py::arg("e17"), py::arg("e18"), py::arg("e19"), py::arg("e20"), py::arg("e21"), py::arg("e22"), py::arg("e23"), py::arg("e24"), py::arg("e25"), py::arg("e26"), py::arg("e27"), py::arg("e28"), py::arg("e29"), py::arg("e30"), py::arg("e31"));
cls_StepData_EnumTool.def(py::init<const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString>(), py::arg("e0"), py::arg("e1"), py::arg("e2"), py::arg("e3"), py::arg("e4"), py::arg("e5"), py::arg("e6"), py::arg("e7"), py::arg("e8"), py::arg("e9"), py::arg("e10"), py::arg("e11"), py::arg("e12"), py::arg("e13"), py::arg("e14"), py::arg("e15"), py::arg("e16"), py::arg("e17"), py::arg("e18"), py::arg("e19"), py::arg("e20"), py::arg("e21"), py::arg("e22"), py::arg("e23"), py::arg("e24"), py::arg("e25"), py::arg("e26"), py::arg("e27"), py::arg("e28"), py::arg("e29"), py::arg("e30"), py::arg("e31"), py::arg("e32"));
cls_StepData_EnumTool.def(py::init<const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString>(), py::arg("e0"), py::arg("e1"), py::arg("e2"), py::arg("e3"), py::arg("e4"), py::arg("e5"), py::arg("e6"), py::arg("e7"), py::arg("e8"), py::arg("e9"), py::arg("e10"), py::arg("e11"), py::arg("e12"), py::arg("e13"), py::arg("e14"), py::arg("e15"), py::arg("e16"), py::arg("e17"), py::arg("e18"), py::arg("e19"), py::arg("e20"), py::arg("e21"), py::arg("e22"), py::arg("e23"), py::arg("e24"), py::arg("e25"), py::arg("e26"), py::arg("e27"), py::arg("e28"), py::arg("e29"), py::arg("e30"), py::arg("e31"), py::arg("e32"), py::arg("e33"));
cls_StepData_EnumTool.def(py::init<const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString>(), py::arg("e0"), py::arg("e1"), py::arg("e2"), py::arg("e3"), py::arg("e4"), py::arg("e5"), py::arg("e6"), py::arg("e7"), py::arg("e8"), py::arg("e9"), py::arg("e10"), py::arg("e11"), py::arg("e12"), py::arg("e13"), py::arg("e14"), py::arg("e15"), py::arg("e16"), py::arg("e17"), py::arg("e18"), py::arg("e19"), py::arg("e20"), py::arg("e21"), py::arg("e22"), py::arg("e23"), py::arg("e24"), py::arg("e25"), py::arg("e26"), py::arg("e27"), py::arg("e28"), py::arg("e29"), py::arg("e30"), py::arg("e31"), py::arg("e32"), py::arg("e33"), py::arg("e34"));
cls_StepData_EnumTool.def(py::init<const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString>(), py::arg("e0"), py::arg("e1"), py::arg("e2"), py::arg("e3"), py::arg("e4"), py::arg("e5"), py::arg("e6"), py::arg("e7"), py::arg("e8"), py::arg("e9"), py::arg("e10"), py::arg("e11"), py::arg("e12"), py::arg("e13"), py::arg("e14"), py::arg("e15"), py::arg("e16"), py::arg("e17"), py::arg("e18"), py::arg("e19"), py::arg("e20"), py::arg("e21"), py::arg("e22"), py::arg("e23"), py::arg("e24"), py::arg("e25"), py::arg("e26"), py::arg("e27"), py::arg("e28"), py::arg("e29"), py::arg("e30"), py::arg("e31"), py::arg("e32"), py::arg("e33"), py::arg("e34"), py::arg("e35"));
cls_StepData_EnumTool.def(py::init<const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString>(), py::arg("e0"), py::arg("e1"), py::arg("e2"), py::arg("e3"), py::arg("e4"), py::arg("e5"), py::arg("e6"), py::arg("e7"), py::arg("e8"), py::arg("e9"), py::arg("e10"), py::arg("e11"), py::arg("e12"), py::arg("e13"), py::arg("e14"), py::arg("e15"), py::arg("e16"), py::arg("e17"), py::arg("e18"), py::arg("e19"), py::arg("e20"), py::arg("e21"), py::arg("e22"), py::arg("e23"), py::arg("e24"), py::arg("e25"), py::arg("e26"), py::arg("e27"), py::arg("e28"), py::arg("e29"), py::arg("e30"), py::arg("e31"), py::arg("e32"), py::arg("e33"), py::arg("e34"), py::arg("e35"), py::arg("e36"));
cls_StepData_EnumTool.def(py::init<const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString>(), py::arg("e0"), py::arg("e1"), py::arg("e2"), py::arg("e3"), py::arg("e4"), py::arg("e5"), py::arg("e6"), py::arg("e7"), py::arg("e8"), py::arg("e9"), py::arg("e10"), py::arg("e11"), py::arg("e12"), py::arg("e13"), py::arg("e14"), py::arg("e15"), py::arg("e16"), py::arg("e17"), py::arg("e18"), py::arg("e19"), py::arg("e20"), py::arg("e21"), py::arg("e22"), py::arg("e23"), py::arg("e24"), py::arg("e25"), py::arg("e26"), py::arg("e27"), py::arg("e28"), py::arg("e29"), py::arg("e30"), py::arg("e31"), py::arg("e32"), py::arg("e33"), py::arg("e34"), py::arg("e35"), py::arg("e36"), py::arg("e37"));
cls_StepData_EnumTool.def(py::init<const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString>(), py::arg("e0"), py::arg("e1"), py::arg("e2"), py::arg("e3"), py::arg("e4"), py::arg("e5"), py::arg("e6"), py::arg("e7"), py::arg("e8"), py::arg("e9"), py::arg("e10"), py::arg("e11"), py::arg("e12"), py::arg("e13"), py::arg("e14"), py::arg("e15"), py::arg("e16"), py::arg("e17"), py::arg("e18"), py::arg("e19"), py::arg("e20"), py::arg("e21"), py::arg("e22"), py::arg("e23"), py::arg("e24"), py::arg("e25"), py::arg("e26"), py::arg("e27"), py::arg("e28"), py::arg("e29"), py::arg("e30"), py::arg("e31"), py::arg("e32"), py::arg("e33"), py::arg("e34"), py::arg("e35"), py::arg("e36"), py::arg("e37"), py::arg("e38"));
cls_StepData_EnumTool.def(py::init<const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString, const Standard_CString>(), py::arg("e0"), py::arg("e1"), py::arg("e2"), py::arg("e3"), py::arg("e4"), py::arg("e5"), py::arg("e6"), py::arg("e7"), py::arg("e8"), py::arg("e9"), py::arg("e10"), py::arg("e11"), py::arg("e12"), py::arg("e13"), py::arg("e14"), py::arg("e15"), py::arg("e16"), py::arg("e17"), py::arg("e18"), py::arg("e19"), py::arg("e20"), py::arg("e21"), py::arg("e22"), py::arg("e23"), py::arg("e24"), py::arg("e25"), py::arg("e26"), py::arg("e27"), py::arg("e28"), py::arg("e29"), py::arg("e30"), py::arg("e31"), py::arg("e32"), py::arg("e33"), py::arg("e34"), py::arg("e35"), py::arg("e36"), py::arg("e37"), py::arg("e38"), py::arg("e39"));

// Fields

// Methods
// cls_StepData_EnumTool.def_static("operator new_", (void * (*)(size_t)) &StepData_EnumTool::operator new, "None", py::arg("theSize"));
// cls_StepData_EnumTool.def_static("operator delete_", (void (*)(void *)) &StepData_EnumTool::operator delete, "None", py::arg("theAddress"));
// cls_StepData_EnumTool.def_static("operator new[]_", (void * (*)(size_t)) &StepData_EnumTool::operator new[], "None", py::arg("theSize"));
// cls_StepData_EnumTool.def_static("operator delete[]_", (void (*)(void *)) &StepData_EnumTool::operator delete[], "None", py::arg("theAddress"));
// cls_StepData_EnumTool.def_static("operator new_", (void * (*)(size_t, void *)) &StepData_EnumTool::operator new, "None", py::arg(""), py::arg("theAddress"));
// cls_StepData_EnumTool.def_static("operator delete_", (void (*)(void *, void *)) &StepData_EnumTool::operator delete, "None", py::arg(""), py::arg(""));
cls_StepData_EnumTool.def("AddDefinition", (void (StepData_EnumTool::*)(const Standard_CString)) &StepData_EnumTool::AddDefinition, "Processes a definition, splits it according blanks if any empty definitions are ignored A null definition can be input by given '$' :the corresponding position is attached to 'null/undefined' value (as one particular item of the enumeration list) See also IsSet", py::arg("term"));
cls_StepData_EnumTool.def("IsSet", (Standard_Boolean (StepData_EnumTool::*)() const) &StepData_EnumTool::IsSet, "Returns True if at least one definition has been entered after creation time (i.e. by AddDefinition only)");
cls_StepData_EnumTool.def("MaxValue", (Standard_Integer (StepData_EnumTool::*)() const) &StepData_EnumTool::MaxValue, "Returns the maximum integer for a suitable value Remark : while values begin at zero, MaxValue is the count of recorded values minus one");
cls_StepData_EnumTool.def("Optional", (void (StepData_EnumTool::*)(const Standard_Boolean)) &StepData_EnumTool::Optional, "Sets or Unsets the EnumTool to accept undefined value (for optional field). Ignored if no null value is defined (by '$') Can be changed during execution (to read each field), Default is True (if a null value is defined)", py::arg("mode"));
cls_StepData_EnumTool.def("NullValue", (Standard_Integer (StepData_EnumTool::*)() const) &StepData_EnumTool::NullValue, "Returns the value attached to 'null/undefined value' If none is specified or if Optional has been set to False, returns -1 Null Value has been specified by definition '$'");
cls_StepData_EnumTool.def("Text", (const TCollection_AsciiString & (StepData_EnumTool::*)(const Standard_Integer) const) &StepData_EnumTool::Text, "Returns the text which corresponds to a given numeric value It is limited by dots If num is out of range, returns an empty string", py::arg("num"));
cls_StepData_EnumTool.def("Value", (Standard_Integer (StepData_EnumTool::*)(const Standard_CString) const) &StepData_EnumTool::Value, "Returns the numeric value found for a text The text must be in capitals and limited by dots A non-suitable text gives a negative value to be returned", py::arg("txt"));
cls_StepData_EnumTool.def("Value", (Standard_Integer (StepData_EnumTool::*)(const TCollection_AsciiString &) const) &StepData_EnumTool::Value, "Same as above but works on an AsciiString", py::arg("txt"));

// Enums

}