/*
This file is part of pyOCCT which provides Python bindings to the OpenCASCADE
geometry kernel.

Copyright (C) 2016-2018  Laughlin Research, LLC
Copyright (C) 2019 Trevor Laughlin and the pyOCCT contributors

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
*/
#include <pyOCCT_Common.hxx>
#include <XCAFDimTolObjects_DimensionType.hxx>

void bind_XCAFDimTolObjects_DimensionType(py::module &mod){

py::enum_<XCAFDimTolObjects_DimensionType>(mod, "XCAFDimTolObjects_DimensionType", "Defines types of dimension")
	.value("XCAFDimTolObjects_DimensionType_Location_None", XCAFDimTolObjects_DimensionType::XCAFDimTolObjects_DimensionType_Location_None)
	.value("XCAFDimTolObjects_DimensionType_Location_CurvedDistance", XCAFDimTolObjects_DimensionType::XCAFDimTolObjects_DimensionType_Location_CurvedDistance)
	.value("XCAFDimTolObjects_DimensionType_Location_LinearDistance", XCAFDimTolObjects_DimensionType::XCAFDimTolObjects_DimensionType_Location_LinearDistance)
	.value("XCAFDimTolObjects_DimensionType_Location_LinearDistance_FromCenterToOuter", XCAFDimTolObjects_DimensionType::XCAFDimTolObjects_DimensionType_Location_LinearDistance_FromCenterToOuter)
	.value("XCAFDimTolObjects_DimensionType_Location_LinearDistance_FromCenterToInner", XCAFDimTolObjects_DimensionType::XCAFDimTolObjects_DimensionType_Location_LinearDistance_FromCenterToInner)
	.value("XCAFDimTolObjects_DimensionType_Location_LinearDistance_FromOuterToCenter", XCAFDimTolObjects_DimensionType::XCAFDimTolObjects_DimensionType_Location_LinearDistance_FromOuterToCenter)
	.value("XCAFDimTolObjects_DimensionType_Location_LinearDistance_FromOuterToOuter", XCAFDimTolObjects_DimensionType::XCAFDimTolObjects_DimensionType_Location_LinearDistance_FromOuterToOuter)
	.value("XCAFDimTolObjects_DimensionType_Location_LinearDistance_FromOuterToInner", XCAFDimTolObjects_DimensionType::XCAFDimTolObjects_DimensionType_Location_LinearDistance_FromOuterToInner)
	.value("XCAFDimTolObjects_DimensionType_Location_LinearDistance_FromInnerToCenter", XCAFDimTolObjects_DimensionType::XCAFDimTolObjects_DimensionType_Location_LinearDistance_FromInnerToCenter)
	.value("XCAFDimTolObjects_DimensionType_Location_LinearDistance_FromInnerToOuter", XCAFDimTolObjects_DimensionType::XCAFDimTolObjects_DimensionType_Location_LinearDistance_FromInnerToOuter)
	.value("XCAFDimTolObjects_DimensionType_Location_LinearDistance_FromInnerToInner", XCAFDimTolObjects_DimensionType::XCAFDimTolObjects_DimensionType_Location_LinearDistance_FromInnerToInner)
	.value("XCAFDimTolObjects_DimensionType_Location_Angular", XCAFDimTolObjects_DimensionType::XCAFDimTolObjects_DimensionType_Location_Angular)
	.value("XCAFDimTolObjects_DimensionType_Location_Oriented", XCAFDimTolObjects_DimensionType::XCAFDimTolObjects_DimensionType_Location_Oriented)
	.value("XCAFDimTolObjects_DimensionType_Location_WithPath", XCAFDimTolObjects_DimensionType::XCAFDimTolObjects_DimensionType_Location_WithPath)
	.value("XCAFDimTolObjects_DimensionType_Size_CurveLength", XCAFDimTolObjects_DimensionType::XCAFDimTolObjects_DimensionType_Size_CurveLength)
	.value("XCAFDimTolObjects_DimensionType_Size_Diameter", XCAFDimTolObjects_DimensionType::XCAFDimTolObjects_DimensionType_Size_Diameter)
	.value("XCAFDimTolObjects_DimensionType_Size_SphericalDiameter", XCAFDimTolObjects_DimensionType::XCAFDimTolObjects_DimensionType_Size_SphericalDiameter)
	.value("XCAFDimTolObjects_DimensionType_Size_Radius", XCAFDimTolObjects_DimensionType::XCAFDimTolObjects_DimensionType_Size_Radius)
	.value("XCAFDimTolObjects_DimensionType_Size_SphericalRadius", XCAFDimTolObjects_DimensionType::XCAFDimTolObjects_DimensionType_Size_SphericalRadius)
	.value("XCAFDimTolObjects_DimensionType_Size_ToroidalMinorDiameter", XCAFDimTolObjects_DimensionType::XCAFDimTolObjects_DimensionType_Size_ToroidalMinorDiameter)
	.value("XCAFDimTolObjects_DimensionType_Size_ToroidalMajorDiameter", XCAFDimTolObjects_DimensionType::XCAFDimTolObjects_DimensionType_Size_ToroidalMajorDiameter)
	.value("XCAFDimTolObjects_DimensionType_Size_ToroidalMinorRadius", XCAFDimTolObjects_DimensionType::XCAFDimTolObjects_DimensionType_Size_ToroidalMinorRadius)
	.value("XCAFDimTolObjects_DimensionType_Size_ToroidalMajorRadius", XCAFDimTolObjects_DimensionType::XCAFDimTolObjects_DimensionType_Size_ToroidalMajorRadius)
	.value("XCAFDimTolObjects_DimensionType_Size_ToroidalHighMajorDiameter", XCAFDimTolObjects_DimensionType::XCAFDimTolObjects_DimensionType_Size_ToroidalHighMajorDiameter)
	.value("XCAFDimTolObjects_DimensionType_Size_ToroidalLowMajorDiameter", XCAFDimTolObjects_DimensionType::XCAFDimTolObjects_DimensionType_Size_ToroidalLowMajorDiameter)
	.value("XCAFDimTolObjects_DimensionType_Size_ToroidalHighMajorRadius", XCAFDimTolObjects_DimensionType::XCAFDimTolObjects_DimensionType_Size_ToroidalHighMajorRadius)
	.value("XCAFDimTolObjects_DimensionType_Size_ToroidalLowMajorRadius", XCAFDimTolObjects_DimensionType::XCAFDimTolObjects_DimensionType_Size_ToroidalLowMajorRadius)
	.value("XCAFDimTolObjects_DimensionType_Size_Thickness", XCAFDimTolObjects_DimensionType::XCAFDimTolObjects_DimensionType_Size_Thickness)
	.value("XCAFDimTolObjects_DimensionType_Size_Angular", XCAFDimTolObjects_DimensionType::XCAFDimTolObjects_DimensionType_Size_Angular)
	.value("XCAFDimTolObjects_DimensionType_Size_WithPath", XCAFDimTolObjects_DimensionType::XCAFDimTolObjects_DimensionType_Size_WithPath)
	.value("XCAFDimTolObjects_DimensionType_CommonLabel", XCAFDimTolObjects_DimensionType::XCAFDimTolObjects_DimensionType_CommonLabel)
	.value("XCAFDimTolObjects_DimensionType_DimensionPresentation", XCAFDimTolObjects_DimensionType::XCAFDimTolObjects_DimensionType_DimensionPresentation)
	.export_values();


}