/*
This file is part of pyOCCT which provides Python bindings to the OpenCASCADE
geometry kernel.

Copyright (C) 2016-2018  Laughlin Research, LLC
Copyright (C) 2019 Trevor Laughlin and the pyOCCT contributors

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
*/
#include <pyOCCT_Common.hxx>

void bind_Graphic3d_GroupAspect(py::module &);
void bind_Graphic3d_AlphaMode(py::module &);
void bind_Graphic3d_FresnelModel(py::module &);
void bind_Graphic3d_NameOfMaterial(py::module &);
void bind_Graphic3d_TypeOfMaterial(py::module &);
void bind_Graphic3d_TypeOfReflection(py::module &);
void bind_Graphic3d_TypeOfShaderObject(py::module &);
void bind_Graphic3d_LevelOfTextureAnisotropy(py::module &);
void bind_Graphic3d_TextureUnit(py::module &);
void bind_Graphic3d_TypeOfTextureFilter(py::module &);
void bind_Graphic3d_TypeOfTextureMode(py::module &);
void bind_Graphic3d_TypeOfTexture(py::module &);
void bind_Graphic3d_TypeOfShadingModel(py::module &);
void bind_Graphic3d_TypeOfLightSource(py::module &);
void bind_Graphic3d_TextPath(py::module &);
void bind_Graphic3d_HorizontalTextAlignment(py::module &);
void bind_Graphic3d_VerticalTextAlignment(py::module &);
void bind_Graphic3d_TypeOfPrimitiveArray(py::module &);
void bind_Graphic3d_TypeOfAttribute(py::module &);
void bind_Graphic3d_CappingFlags(py::module &);
void bind_Graphic3d_TypeOfComposition(py::module &);
void bind_Graphic3d_TransModeFlags(py::module &);
void bind_Graphic3d_DiagnosticInfo(py::module &);
void bind_Graphic3d_ExportFormat(py::module &);
void bind_Graphic3d_RenderTransparentMethod(py::module &);
void bind_Graphic3d_RenderingMode(py::module &);
void bind_Graphic3d_StereoMode(py::module &);
void bind_Graphic3d_ToneMappingMethod(py::module &);
void bind_Graphic3d_TypeOfStructure(py::module &);
void bind_Graphic3d_TypeOfConnection(py::module &);
void bind_Graphic3d_SortType(py::module &);
void bind_Graphic3d_NameOfTextureEnv(py::module &);
void bind_Graphic3d_TypeOfAnswer(py::module &);
void bind_Graphic3d_TypeOfBackfacingModel(py::module &);
void bind_Graphic3d_TypeOfVisualization(py::module &);
void bind_Graphic3d_ZLayerSetting(py::module &);
void bind_Graphic3d_NameOfTexture2D(py::module &);
void bind_Graphic3d_TypeOfLimit(py::module &);
void bind_Graphic3d_NameOfTexture1D(py::module &);
void bind_Graphic3d_NameOfTexturePlane(py::module &);
void bind_Graphic3d_TypeOfBackground(py::module &);
void bind_Graphic3d_HatchStyle(py::module &);
void bind_Graphic3d_Vec3(py::module &);
void bind_Graphic3d_Vec3d(py::module &);
void bind_Graphic3d_Vec3i(py::module &);
void bind_Graphic3d_Vec3u(py::module &);
void bind_Graphic3d_Vec3ub(py::module &);
void bind_Graphic3d_Vec3b(py::module &);
void bind_Graphic3d_Vec4(py::module &);
void bind_Graphic3d_Vec4d(py::module &);
void bind_Graphic3d_Vec4i(py::module &);
void bind_Graphic3d_Vec4u(py::module &);
void bind_Graphic3d_Vec4ub(py::module &);
void bind_Graphic3d_Vec4b(py::module &);
void bind_Graphic3d_Fresnel(py::module &);
void bind_Graphic3d_BSDF(py::module &);
void bind_Graphic3d_MaterialAspect(py::module &);
void bind_Graphic3d_PolygonOffset(py::module &);
void bind_Graphic3d_ShaderAttribute(py::module &);
void bind_Graphic3d_ShaderObject(py::module &);
void bind_Graphic3d_Vec2(py::module &);
void bind_Graphic3d_Vec2d(py::module &);
void bind_Graphic3d_Vec2i(py::module &);
void bind_Graphic3d_Vec2u(py::module &);
void bind_Graphic3d_Vec2ub(py::module &);
void bind_Graphic3d_Vec2b(py::module &);
void bind_Graphic3d_Mat4(py::module &);
void bind_Graphic3d_Mat4d(py::module &);
void bind_Graphic3d_ValueInterface(py::module &);
void bind_Graphic3d_UniformInt(py::module &);
void bind_Graphic3d_UniformVec2i(py::module &);
void bind_Graphic3d_UniformVec3i(py::module &);
void bind_Graphic3d_UniformVec4i(py::module &);
void bind_Graphic3d_UniformFloat(py::module &);
void bind_Graphic3d_UniformVec2(py::module &);
void bind_Graphic3d_UniformVec3(py::module &);
void bind_Graphic3d_UniformVec4(py::module &);
void bind_Graphic3d_ShaderVariable(py::module &);
void bind_Graphic3d_TextureParams(py::module &);
void bind_Graphic3d_ShaderObjectList(py::module &);
void bind_Graphic3d_ShaderVariableList(py::module &);
void bind_Graphic3d_ShaderAttributeList(py::module &);
void bind_Graphic3d_ShaderProgram(py::module &);
void bind_Graphic3d_TextureRoot(py::module &);
void bind_Graphic3d_TextureMap(py::module &);
void bind_Graphic3d_TextureSet(py::module &);
void bind_Graphic3d_AspectFillArea3d(py::module &);
void bind_Graphic3d_ZLayerId(py::module &);
void bind_Graphic3d_PresentationAttributes(py::module &);
void bind_Graphic3d_BufferType(py::module &);
void bind_Graphic3d_CameraTile(py::module &);
void bind_Graphic3d_WorldViewProjState(py::module &);
void bind_Graphic3d_Camera(py::module &);
void bind_Graphic3d_CameraLerp(py::module &);
void bind_Graphic3d_CLight(py::module &);
void bind_Graphic3d_BndBox3d(py::module &);
void bind_Graphic3d_BndBox4f(py::module &);
void bind_Graphic3d_AspectLine3d(py::module &);
void bind_Graphic3d_AspectTextDefinitionError(py::module &);
void bind_Graphic3d_AspectText3d(py::module &);
void bind_Graphic3d_MarkerImage(py::module &);
void bind_Graphic3d_AspectMarker3d(py::module &);
void bind_Graphic3d_Vertex(py::module &);
void bind_Graphic3d_Attribute(py::module &);
void bind_Graphic3d_Array1OfAttribute(py::module &);
void bind_Graphic3d_Buffer(py::module &);
void bind_Graphic3d_IndexBuffer(py::module &);
void bind_Graphic3d_BoundBuffer(py::module &);
void bind_Graphic3d_Group(py::module &);
void bind_Graphic3d_SequenceOfGroup(py::module &);
void bind_Graphic3d_ClipPlane(py::module &);
void bind_Graphic3d_SequenceOfHClipPlane(py::module &);
void bind_Graphic3d_ViewAffinity(py::module &);
void bind_Graphic3d_TransformPers(py::module &);
void bind_Graphic3d_CStructure(py::module &);
void bind_Graphic3d_DataStructureManager(py::module &);
void bind_Graphic3d_AxisAspect(py::module &);
void bind_Graphic3d_GraduatedTrihedron(py::module &);
void bind_Graphic3d_MapOfStructure(py::module &);
void bind_Graphic3d_NMapOfTransient(py::module &);
void bind_Graphic3d_RenderingParams(py::module &);
void bind_Graphic3d_IndexedMapOfAddress(py::module &);
void bind_Graphic3d_BndBox4d(py::module &);
void bind_Graphic3d_Structure(py::module &);
void bind_Graphic3d_SequenceOfStructure(py::module &);
void bind_Graphic3d_TextureEnv(py::module &);
void bind_Graphic3d_LightSet(py::module &);
void bind_Graphic3d_ZLayerSettings(py::module &);
void bind_Graphic3d_CView(py::module &);
void bind_Graphic3d_MapOfObject(py::module &);
void bind_Graphic3d_IndexedMapOfView(py::module &);
void bind_Graphic3d_StructureManager(py::module &);
void bind_Graphic3d_ArrayOfPrimitives(py::module &);
void bind_Graphic3d_ArrayOfQuadrangles(py::module &);
void bind_Graphic3d_ArrayOfTriangles(py::module &);
void bind_Graphic3d_ArrayOfPoints(py::module &);
void bind_Graphic3d_ArrayOfPolylines(py::module &);
void bind_Graphic3d_Texture2D(py::module &);
void bind_Graphic3d_Texture2Dmanual(py::module &);
void bind_Graphic3d_ArrayOfPolygons(py::module &);
void bind_Graphic3d_ArrayOfQuadrangleStrips(py::module &);
void bind_Graphic3d_ArrayOfSegments(py::module &);
void bind_Graphic3d_ArrayOfTriangleFans(py::module &);
void bind_Graphic3d_ArrayOfTriangleStrips(py::module &);
void bind_Graphic3d_CTexture(py::module &);
void bind_Graphic3d_GraphicDriver(py::module &);
void bind_Graphic3d_GroupDefinitionError(py::module &);
void bind_Graphic3d_MapIteratorOfMapOfStructure(py::module &);
void bind_Graphic3d_MaterialDefinitionError(py::module &);
void bind_Graphic3d_PriorityDefinitionError(py::module &);
void bind_Graphic3d_StructureDefinitionError(py::module &);
void bind_Graphic3d_Texture1D(py::module &);
void bind_Graphic3d_Texture1Dmanual(py::module &);
void bind_Graphic3d_Texture1Dsegment(py::module &);
void bind_Graphic3d_Texture2Dplane(py::module &);
void bind_Graphic3d_TransformError(py::module &);

PYBIND11_MODULE(Graphic3d, mod) {

py::module::import("OCCT.Precision");
py::module::import("OCCT.Standard");
py::module::import("OCCT.Image");
py::module::import("OCCT.Aspect");
py::module::import("OCCT.NCollection");
py::module::import("OCCT.TCollection");
py::module::import("OCCT.Quantity");
py::module::import("OCCT.OSD");
py::module::import("OCCT.gp");
py::module::import("OCCT.Bnd");
py::module::import("OCCT.BVH");
py::module::import("OCCT.Font");
py::module::import("OCCT.TColStd");
py::module::import("OCCT.Geom");

bind_Graphic3d_GroupAspect(mod);
bind_Graphic3d_AlphaMode(mod);
bind_Graphic3d_FresnelModel(mod);
bind_Graphic3d_NameOfMaterial(mod);
bind_Graphic3d_TypeOfMaterial(mod);
bind_Graphic3d_TypeOfReflection(mod);
bind_Graphic3d_TypeOfShaderObject(mod);
bind_Graphic3d_LevelOfTextureAnisotropy(mod);
bind_Graphic3d_TextureUnit(mod);
bind_Graphic3d_TypeOfTextureFilter(mod);
bind_Graphic3d_TypeOfTextureMode(mod);
bind_Graphic3d_TypeOfTexture(mod);
bind_Graphic3d_TypeOfShadingModel(mod);
bind_Graphic3d_TypeOfLightSource(mod);
bind_Graphic3d_TextPath(mod);
bind_Graphic3d_HorizontalTextAlignment(mod);
bind_Graphic3d_VerticalTextAlignment(mod);
bind_Graphic3d_TypeOfPrimitiveArray(mod);
bind_Graphic3d_TypeOfAttribute(mod);
bind_Graphic3d_CappingFlags(mod);
bind_Graphic3d_TypeOfComposition(mod);
bind_Graphic3d_TransModeFlags(mod);
bind_Graphic3d_DiagnosticInfo(mod);
bind_Graphic3d_ExportFormat(mod);
bind_Graphic3d_RenderTransparentMethod(mod);
bind_Graphic3d_RenderingMode(mod);
bind_Graphic3d_StereoMode(mod);
bind_Graphic3d_ToneMappingMethod(mod);
bind_Graphic3d_TypeOfStructure(mod);
bind_Graphic3d_TypeOfConnection(mod);
bind_Graphic3d_SortType(mod);
bind_Graphic3d_NameOfTextureEnv(mod);
bind_Graphic3d_TypeOfAnswer(mod);
bind_Graphic3d_TypeOfBackfacingModel(mod);
bind_Graphic3d_TypeOfVisualization(mod);
bind_Graphic3d_ZLayerSetting(mod);
bind_Graphic3d_NameOfTexture2D(mod);
bind_Graphic3d_TypeOfLimit(mod);
bind_Graphic3d_NameOfTexture1D(mod);
bind_Graphic3d_NameOfTexturePlane(mod);
bind_Graphic3d_TypeOfBackground(mod);
bind_Graphic3d_HatchStyle(mod);
bind_Graphic3d_Vec3(mod);
bind_Graphic3d_Vec3d(mod);
bind_Graphic3d_Vec3i(mod);
bind_Graphic3d_Vec3u(mod);
bind_Graphic3d_Vec3ub(mod);
bind_Graphic3d_Vec3b(mod);
bind_Graphic3d_Vec4(mod);
bind_Graphic3d_Vec4d(mod);
bind_Graphic3d_Vec4i(mod);
bind_Graphic3d_Vec4u(mod);
bind_Graphic3d_Vec4ub(mod);
bind_Graphic3d_Vec4b(mod);
bind_Graphic3d_Fresnel(mod);
bind_Graphic3d_BSDF(mod);
bind_Graphic3d_MaterialAspect(mod);
bind_Graphic3d_PolygonOffset(mod);
bind_Graphic3d_ShaderAttribute(mod);
bind_Graphic3d_ShaderObject(mod);
bind_Graphic3d_Vec2(mod);
bind_Graphic3d_Vec2d(mod);
bind_Graphic3d_Vec2i(mod);
bind_Graphic3d_Vec2u(mod);
bind_Graphic3d_Vec2ub(mod);
bind_Graphic3d_Vec2b(mod);
bind_Graphic3d_Mat4(mod);
bind_Graphic3d_Mat4d(mod);
bind_Graphic3d_ValueInterface(mod);
bind_Graphic3d_UniformInt(mod);
bind_Graphic3d_UniformVec2i(mod);
bind_Graphic3d_UniformVec3i(mod);
bind_Graphic3d_UniformVec4i(mod);
bind_Graphic3d_UniformFloat(mod);
bind_Graphic3d_UniformVec2(mod);
bind_Graphic3d_UniformVec3(mod);
bind_Graphic3d_UniformVec4(mod);
bind_Graphic3d_ShaderVariable(mod);
bind_Graphic3d_TextureParams(mod);
bind_Graphic3d_ShaderObjectList(mod);
bind_Graphic3d_ShaderVariableList(mod);
bind_Graphic3d_ShaderAttributeList(mod);
bind_Graphic3d_ShaderProgram(mod);
bind_Graphic3d_TextureRoot(mod);
bind_Graphic3d_TextureMap(mod);
bind_Graphic3d_TextureSet(mod);
bind_Graphic3d_AspectFillArea3d(mod);
bind_Graphic3d_ZLayerId(mod);
bind_Graphic3d_PresentationAttributes(mod);
bind_Graphic3d_BufferType(mod);
bind_Graphic3d_CameraTile(mod);
bind_Graphic3d_WorldViewProjState(mod);
bind_Graphic3d_Camera(mod);
bind_Graphic3d_CameraLerp(mod);
bind_Graphic3d_CLight(mod);
bind_Graphic3d_BndBox3d(mod);
bind_Graphic3d_BndBox4f(mod);
bind_Graphic3d_AspectLine3d(mod);
bind_Graphic3d_AspectTextDefinitionError(mod);
bind_Graphic3d_AspectText3d(mod);
bind_Graphic3d_MarkerImage(mod);
bind_Graphic3d_AspectMarker3d(mod);
bind_Graphic3d_Vertex(mod);
bind_Graphic3d_Attribute(mod);
bind_Graphic3d_Array1OfAttribute(mod);
bind_Graphic3d_Buffer(mod);
bind_Graphic3d_IndexBuffer(mod);
bind_Graphic3d_BoundBuffer(mod);
bind_Graphic3d_Group(mod);
bind_Graphic3d_SequenceOfGroup(mod);
bind_Graphic3d_ClipPlane(mod);
bind_Graphic3d_SequenceOfHClipPlane(mod);
bind_Graphic3d_ViewAffinity(mod);
bind_Graphic3d_TransformPers(mod);
bind_Graphic3d_CStructure(mod);
bind_Graphic3d_DataStructureManager(mod);
bind_Graphic3d_AxisAspect(mod);
bind_Graphic3d_GraduatedTrihedron(mod);
bind_Graphic3d_MapOfStructure(mod);
bind_Graphic3d_NMapOfTransient(mod);
bind_Graphic3d_RenderingParams(mod);
bind_Graphic3d_IndexedMapOfAddress(mod);
bind_Graphic3d_BndBox4d(mod);
bind_Graphic3d_Structure(mod);
bind_Graphic3d_SequenceOfStructure(mod);
bind_Graphic3d_TextureEnv(mod);
bind_Graphic3d_LightSet(mod);
bind_Graphic3d_ZLayerSettings(mod);
bind_Graphic3d_CView(mod);
bind_Graphic3d_MapOfObject(mod);
bind_Graphic3d_IndexedMapOfView(mod);
bind_Graphic3d_StructureManager(mod);
bind_Graphic3d_ArrayOfPrimitives(mod);
bind_Graphic3d_ArrayOfQuadrangles(mod);
bind_Graphic3d_ArrayOfTriangles(mod);
bind_Graphic3d_ArrayOfPoints(mod);
bind_Graphic3d_ArrayOfPolylines(mod);
bind_Graphic3d_Texture2D(mod);
bind_Graphic3d_Texture2Dmanual(mod);
bind_Graphic3d_ArrayOfPolygons(mod);
bind_Graphic3d_ArrayOfQuadrangleStrips(mod);
bind_Graphic3d_ArrayOfSegments(mod);
bind_Graphic3d_ArrayOfTriangleFans(mod);
bind_Graphic3d_ArrayOfTriangleStrips(mod);
bind_Graphic3d_CTexture(mod);
bind_Graphic3d_GraphicDriver(mod);
bind_Graphic3d_GroupDefinitionError(mod);
bind_Graphic3d_MapIteratorOfMapOfStructure(mod);
bind_Graphic3d_MaterialDefinitionError(mod);
bind_Graphic3d_PriorityDefinitionError(mod);
bind_Graphic3d_StructureDefinitionError(mod);
bind_Graphic3d_Texture1D(mod);
bind_Graphic3d_Texture1Dmanual(mod);
bind_Graphic3d_Texture1Dsegment(mod);
bind_Graphic3d_Texture2Dplane(mod);
bind_Graphic3d_TransformError(mod);

}
