/*
This file is part of pyOCCT which provides Python bindings to the OpenCASCADE
geometry kernel.

Copyright (C) 2016-2018  Laughlin Research, LLC
Copyright (C) 2019 Trevor Laughlin and the pyOCCT contributors

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
*/
#include <pyOCCT_Common.hxx>

void bind_Standard_HandlerStatus(py::module &);
void bind_Abs(py::module &);
void bind_HashCode(py::module &);
void bind_IsEqual(py::module &);
void bind_IsEven(py::module &);
void bind_IsOdd(py::module &);
void bind_Max(py::module &);
void bind_Min(py::module &);
void bind_Modulus(py::module &);
void bind_Square(py::module &);
void bind_IntegerFirst(py::module &);
void bind_IntegerLast(py::module &);
void bind_IntegerSize(py::module &);
void bind_RealSmall(py::module &);
void bind_RealDigits(py::module &);
void bind_RealEpsilon(py::module &);
void bind_RealFirst(py::module &);
void bind_RealFirst10Exp(py::module &);
void bind_RealLast(py::module &);
void bind_RealLast10Exp(py::module &);
void bind_RealMantissa(py::module &);
void bind_RealRadix(py::module &);
void bind_RealSize(py::module &);
void bind_IntToReal(py::module &);
void bind_ATan(py::module &);
void bind_Ceiling(py::module &);
void bind_Cos(py::module &);
void bind_Epsilon(py::module &);
void bind_Exp(py::module &);
void bind_Floor(py::module &);
void bind_IntegerPart(py::module &);
void bind_Log10(py::module &);
void bind_Pow(py::module &);
void bind_RealPart(py::module &);
void bind_RealToInt(py::module &);
void bind_RealToShortReal(py::module &);
void bind_Round(py::module &);
void bind_Sin(py::module &);
void bind_ASinh(py::module &);
void bind_Tan(py::module &);
void bind_Tanh(py::module &);
void bind_IsAlphabetic(py::module &);
void bind_IsDigit(py::module &);
void bind_IsXDigit(py::module &);
void bind_IsAlphanumeric(py::module &);
void bind_IsControl(py::module &);
void bind_IsGraphic(py::module &);
void bind_IsLowerCase(py::module &);
void bind_IsPrintable(py::module &);
void bind_IsPunctuation(py::module &);
void bind_IsSpace(py::module &);
void bind_IsUpperCase(py::module &);
void bind_LowerCase(py::module &);
void bind_UpperCase(py::module &);
void bind_ToExtCharacter(py::module &);
void bind_ToCharacter(py::module &);
void bind_IsAnAscii(py::module &);
void bind_Standard_ASSERT_DO_NOTHING(py::module &);
void bind_ShortRealSmall(py::module &);
void bind_ShortRealDigits(py::module &);
void bind_ShortRealEpsilon(py::module &);
void bind_ShortRealFirst(py::module &);
void bind_ShortRealFirst10Exp(py::module &);
void bind_ShortRealLast(py::module &);
void bind_ShortRealLast10Exp(py::module &);
void bind_ShortRealMantissa(py::module &);
void bind_ShortRealRadix(py::module &);
void bind_ShortRealSize(py::module &);
void bind_Standard_Atomic_Increment(py::module &);
void bind_Standard_Atomic_Decrement(py::module &);
void bind_Standard_Integer(py::module &);
void bind_Standard_Real(py::module &);
void bind_Standard_Boolean(py::module &);
void bind_Standard_ShortReal(py::module &);
void bind_Standard_Character(py::module &);
void bind_Standard_Byte(py::module &);
void bind_Standard_Address(py::module &);
void bind_Standard_Size(py::module &);
void bind_Standard_Time(py::module &);
void bind_Standard_Utf8Char(py::module &);
void bind_Standard_Utf8UChar(py::module &);
void bind_Standard_ExtCharacter(py::module &);
void bind_Standard_Utf16Char(py::module &);
void bind_Standard_Utf32Char(py::module &);
void bind_Standard_WideChar(py::module &);
void bind_Standard_CString(py::module &);
void bind_Standard_ExtString(py::module &);
void bind_Standard(py::module &);
void bind_Standard_OStream(py::module &);
void bind_Standard_Transient(py::module &);
void bind_Standard_Type(py::module &);
void bind_Standard_SStream(py::module &);
void bind_Standard_Failure(py::module &);
void bind_Standard_DomainError(py::module &);
void bind_Standard_DimensionError(py::module &);
void bind_Standard_DimensionMismatch(py::module &);
void bind_Standard_ProgramError(py::module &);
void bind_Standard_OutOfMemory(py::module &);
void bind_Standard_RangeError(py::module &);
void bind_Standard_OutOfRange(py::module &);
void bind_Standard_Static_Assert(py::module &);
void bind_Standard_ConstructionError(py::module &);
void bind_Standard_NoSuchObject(py::module &);
void bind_Standard_PCharacter(py::module &);
void bind_Standard_IStream(py::module &);
void bind_Standard_PExtCharacter(py::module &);
void bind_Standard_TypeMismatch(py::module &);
void bind_Standard_Persistent(py::module &);
void bind_Standard_UUID(py::module &);
void bind_Standard_GUID(py::module &);
void bind_Standard_MultiplyDefined(py::module &);
void bind_Standard_ImmutableObject(py::module &);
void bind_Standard_PErrorHandler(py::module &);
void bind_Standard_JmpBuf(py::module &);
void bind_Standard_ThreadId(py::module &);
void bind_Standard_ErrorHandler(py::module &);
void bind_Standard_ErrorHandlerCallback(py::module &);
void bind_Standard_Mutex(py::module &);
void bind_Standard_NullObject(py::module &);
void bind_Standard_NotImplemented(py::module &);
void bind_Standard_NegativeValue(py::module &);
void bind_Standard_NullValue(py::module &);
void bind_Standard_AbortiveTransaction(py::module &);
void bind_Standard_ArrayStreamBuffer(py::module &);
void bind_Standard_CLocaleSentry(py::module &);
void bind_Standard_NumericError(py::module &);
void bind_Standard_DivideByZero(py::module &);
void bind_Standard_LicenseError(py::module &);
void bind_Standard_LicenseNotFound(py::module &);
void bind_Standard_MMgrRoot(py::module &);
void bind_Standard_MMgrOpt(py::module &);
void bind_Standard_MMgrRaw(py::module &);
void bind_Standard_MMgrTBBalloc(py::module &);
void bind_Standard_NoMoreObject(py::module &);
void bind_Standard_Overflow(py::module &);
void bind_Standard_PByte(py::module &);
void bind_Standard_TooManyUsers(py::module &);
void bind_Standard_Underflow(py::module &);

PYBIND11_MODULE(Standard, mod) {


bind_Standard_HandlerStatus(mod);
bind_Abs(mod);
bind_HashCode(mod);
bind_IsEqual(mod);
bind_IsEven(mod);
bind_IsOdd(mod);
bind_Max(mod);
bind_Min(mod);
bind_Modulus(mod);
bind_Square(mod);
bind_IntegerFirst(mod);
bind_IntegerLast(mod);
bind_IntegerSize(mod);
bind_RealSmall(mod);
bind_RealDigits(mod);
bind_RealEpsilon(mod);
bind_RealFirst(mod);
bind_RealFirst10Exp(mod);
bind_RealLast(mod);
bind_RealLast10Exp(mod);
bind_RealMantissa(mod);
bind_RealRadix(mod);
bind_RealSize(mod);
bind_IntToReal(mod);
bind_ATan(mod);
bind_Ceiling(mod);
bind_Cos(mod);
bind_Epsilon(mod);
bind_Exp(mod);
bind_Floor(mod);
bind_IntegerPart(mod);
bind_Log10(mod);
bind_Pow(mod);
bind_RealPart(mod);
bind_RealToInt(mod);
bind_RealToShortReal(mod);
bind_Round(mod);
bind_Sin(mod);
bind_ASinh(mod);
bind_Tan(mod);
bind_Tanh(mod);
bind_IsAlphabetic(mod);
bind_IsDigit(mod);
bind_IsXDigit(mod);
bind_IsAlphanumeric(mod);
bind_IsControl(mod);
bind_IsGraphic(mod);
bind_IsLowerCase(mod);
bind_IsPrintable(mod);
bind_IsPunctuation(mod);
bind_IsSpace(mod);
bind_IsUpperCase(mod);
bind_LowerCase(mod);
bind_UpperCase(mod);
bind_ToExtCharacter(mod);
bind_ToCharacter(mod);
bind_IsAnAscii(mod);
bind_Standard_ASSERT_DO_NOTHING(mod);
bind_ShortRealSmall(mod);
bind_ShortRealDigits(mod);
bind_ShortRealEpsilon(mod);
bind_ShortRealFirst(mod);
bind_ShortRealFirst10Exp(mod);
bind_ShortRealLast(mod);
bind_ShortRealLast10Exp(mod);
bind_ShortRealMantissa(mod);
bind_ShortRealRadix(mod);
bind_ShortRealSize(mod);
bind_Standard_Atomic_Increment(mod);
bind_Standard_Atomic_Decrement(mod);
bind_Standard_Integer(mod);
bind_Standard_Real(mod);
bind_Standard_Boolean(mod);
bind_Standard_ShortReal(mod);
bind_Standard_Character(mod);
bind_Standard_Byte(mod);
bind_Standard_Address(mod);
bind_Standard_Size(mod);
bind_Standard_Time(mod);
bind_Standard_Utf8Char(mod);
bind_Standard_Utf8UChar(mod);
bind_Standard_ExtCharacter(mod);
bind_Standard_Utf16Char(mod);
bind_Standard_Utf32Char(mod);
bind_Standard_WideChar(mod);
bind_Standard_CString(mod);
bind_Standard_ExtString(mod);
bind_Standard(mod);
bind_Standard_OStream(mod);
bind_Standard_Transient(mod);
bind_Standard_Type(mod);
bind_Standard_SStream(mod);
bind_Standard_Failure(mod);
bind_Standard_DomainError(mod);
bind_Standard_DimensionError(mod);
bind_Standard_DimensionMismatch(mod);
bind_Standard_ProgramError(mod);
bind_Standard_OutOfMemory(mod);
bind_Standard_RangeError(mod);
bind_Standard_OutOfRange(mod);
bind_Standard_Static_Assert(mod);
bind_Standard_ConstructionError(mod);
bind_Standard_NoSuchObject(mod);
bind_Standard_PCharacter(mod);
bind_Standard_IStream(mod);
bind_Standard_PExtCharacter(mod);
bind_Standard_TypeMismatch(mod);
bind_Standard_Persistent(mod);
bind_Standard_UUID(mod);
bind_Standard_GUID(mod);
bind_Standard_MultiplyDefined(mod);
bind_Standard_ImmutableObject(mod);
bind_Standard_PErrorHandler(mod);
bind_Standard_JmpBuf(mod);
bind_Standard_ThreadId(mod);
bind_Standard_ErrorHandler(mod);
bind_Standard_ErrorHandlerCallback(mod);
bind_Standard_Mutex(mod);
bind_Standard_NullObject(mod);
bind_Standard_NotImplemented(mod);
bind_Standard_NegativeValue(mod);
bind_Standard_NullValue(mod);
bind_Standard_AbortiveTransaction(mod);
bind_Standard_ArrayStreamBuffer(mod);
bind_Standard_CLocaleSentry(mod);
bind_Standard_NumericError(mod);
bind_Standard_DivideByZero(mod);
bind_Standard_LicenseError(mod);
bind_Standard_LicenseNotFound(mod);
bind_Standard_MMgrRoot(mod);
bind_Standard_MMgrOpt(mod);
bind_Standard_MMgrRaw(mod);
bind_Standard_MMgrTBBalloc(mod);
bind_Standard_NoMoreObject(mod);
bind_Standard_Overflow(mod);
bind_Standard_PByte(mod);
bind_Standard_TooManyUsers(mod);
bind_Standard_Underflow(mod);

}
