/*
This file is part of pyOCCT which provides Python bindings to the OpenCASCADE
geometry kernel.

Copyright (C) 2016-2018  Laughlin Research, LLC
Copyright (C) 2019 Trevor Laughlin and the pyOCCT contributors

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
*/
#include <pyOCCT_Common.hxx>

void bind_StepVisual_CentralOrParallel(py::module &);
void bind_StepVisual_MarkerType(py::module &);
void bind_StepVisual_NullStyle(py::module &);
void bind_StepVisual_SurfaceSide(py::module &);
void bind_StepVisual_TextPath(py::module &);
void bind_StepVisual_TessellatedItem(py::module &);
void bind_StepVisual_CoordinatesList(py::module &);
void bind_StepVisual_VectorOfHSequenceOfInteger(py::module &);
void bind_StepVisual_TessellatedCurveSet(py::module &);
void bind_StepVisual_PresentedItem(py::module &);
void bind_StepVisual_Array1OfTessellatedItem(py::module &);
void bind_StepVisual_TessellatedGeometricSet(py::module &);
void bind_StepVisual_DraughtingModel(py::module &);
void bind_StepVisual_PresentationStyleSelect(py::module &);
void bind_StepVisual_Array1OfPresentationStyleSelect(py::module &);
void bind_StepVisual_HArray1OfPresentationStyleSelect(py::module &);
void bind_StepVisual_PresentationStyleAssignment(py::module &);
void bind_StepVisual_Array1OfPresentationStyleAssignment(py::module &);
void bind_StepVisual_HArray1OfPresentationStyleAssignment(py::module &);
void bind_StepVisual_StyledItemTarget(py::module &);
void bind_StepVisual_StyledItem(py::module &);
void bind_StepVisual_AnnotationOccurrence(py::module &);
void bind_StepVisual_AnnotationCurveOccurrence(py::module &);
void bind_StepVisual_AnnotationCurveOccurrenceAndAnnotationOccurrenceAndGeomReprItemAndReprItemAndStyledItem(py::module &);
void bind_StepVisual_AnnotationFillArea(py::module &);
void bind_StepVisual_AnnotationFillAreaOccurrence(py::module &);
void bind_StepVisual_AnnotationPlaneElement(py::module &);
void bind_StepVisual_Array1OfAnnotationPlaneElement(py::module &);
void bind_StepVisual_HArray1OfAnnotationPlaneElement(py::module &);
void bind_StepVisual_AnnotationPlane(py::module &);
void bind_StepVisual_AnnotationText(py::module &);
void bind_StepVisual_AnnotationTextOccurrence(py::module &);
void bind_StepVisual_AreaInSet(py::module &);
void bind_StepVisual_AreaOrView(py::module &);
void bind_StepVisual_BoxCharacteristicSelect(py::module &);
void bind_StepVisual_Array1OfBoxCharacteristicSelect(py::module &);
void bind_StepVisual_CameraModelD3MultiClippingInterectionSelect(py::module &);
void bind_StepVisual_Array1OfCameraModelD3MultiClippingInterectionSelect(py::module &);
void bind_StepVisual_CameraModelD3MultiClippingUnionSelect(py::module &);
void bind_StepVisual_Array1OfCameraModelD3MultiClippingUnionSelect(py::module &);
void bind_StepVisual_CurveStyleFontPattern(py::module &);
void bind_StepVisual_Array1OfCurveStyleFontPattern(py::module &);
void bind_StepVisual_DirectionCountSelect(py::module &);
void bind_StepVisual_Array1OfDirectionCountSelect(py::module &);
void bind_StepVisual_DraughtingCalloutElement(py::module &);
void bind_StepVisual_Array1OfDraughtingCalloutElement(py::module &);
void bind_StepVisual_FillStyleSelect(py::module &);
void bind_StepVisual_Array1OfFillStyleSelect(py::module &);
void bind_StepVisual_InvisibleItem(py::module &);
void bind_StepVisual_Array1OfInvisibleItem(py::module &);
void bind_StepVisual_LayeredItem(py::module &);
void bind_StepVisual_Array1OfLayeredItem(py::module &);
void bind_StepVisual_StyleContextSelect(py::module &);
void bind_StepVisual_Array1OfStyleContextSelect(py::module &);
void bind_StepVisual_SurfaceStyleElementSelect(py::module &);
void bind_StepVisual_Array1OfSurfaceStyleElementSelect(py::module &);
void bind_StepVisual_TextOrCharacter(py::module &);
void bind_StepVisual_Array1OfTextOrCharacter(py::module &);
void bind_StepVisual_Colour(py::module &);
void bind_StepVisual_BackgroundColour(py::module &);
void bind_StepVisual_CameraImage(py::module &);
void bind_StepVisual_CameraImage2dWithScale(py::module &);
void bind_StepVisual_CameraImage3dWithScale(py::module &);
void bind_StepVisual_CameraModel(py::module &);
void bind_StepVisual_CameraModelD2(py::module &);
void bind_StepVisual_CameraModelD3(py::module &);
void bind_StepVisual_CameraModelD3MultiClipping(py::module &);
void bind_StepVisual_CameraModelD3MultiClippingIntersection(py::module &);
void bind_StepVisual_CameraModelD3MultiClippingUnion(py::module &);
void bind_StepVisual_CameraUsage(py::module &);
void bind_StepVisual_CharacterizedObjectAndCharacterizedRepresentationAndDraughtingModelAndRepresentation(py::module &);
void bind_StepVisual_ColourSpecification(py::module &);
void bind_StepVisual_ColourRgb(py::module &);
void bind_StepVisual_HArray1OfTextOrCharacter(py::module &);
void bind_StepVisual_CompositeText(py::module &);
void bind_StepVisual_CompositeTextWithExtent(py::module &);
void bind_StepVisual_InvisibilityContext(py::module &);
void bind_StepVisual_HArray1OfInvisibleItem(py::module &);
void bind_StepVisual_Invisibility(py::module &);
void bind_StepVisual_ContextDependentInvisibility(py::module &);
void bind_StepVisual_HArray1OfStyleContextSelect(py::module &);
void bind_StepVisual_OverRidingStyledItem(py::module &);
void bind_StepVisual_ContextDependentOverRidingStyledItem(py::module &);
void bind_StepVisual_CurveStyleFontSelect(py::module &);
void bind_StepVisual_CurveStyle(py::module &);
void bind_StepVisual_HArray1OfCurveStyleFontPattern(py::module &);
void bind_StepVisual_CurveStyleFont(py::module &);
void bind_StepVisual_DraughtingAnnotationOccurrence(py::module &);
void bind_StepVisual_HArray1OfDraughtingCalloutElement(py::module &);
void bind_StepVisual_DraughtingCallout(py::module &);
void bind_StepVisual_PreDefinedColour(py::module &);
void bind_StepVisual_DraughtingPreDefinedColour(py::module &);
void bind_StepVisual_PreDefinedItem(py::module &);
void bind_StepVisual_PreDefinedCurveFont(py::module &);
void bind_StepVisual_DraughtingPreDefinedCurveFont(py::module &);
void bind_StepVisual_ExternallyDefinedCurveFont(py::module &);
void bind_StepVisual_ExternallyDefinedTextFont(py::module &);
void bind_StepVisual_HArray1OfFillStyleSelect(py::module &);
void bind_StepVisual_FillAreaStyle(py::module &);
void bind_StepVisual_FillAreaStyleColour(py::module &);
void bind_StepVisual_FontSelect(py::module &);
void bind_StepVisual_HArray1OfBoxCharacteristicSelect(py::module &);
void bind_StepVisual_HArray1OfCameraModelD3MultiClippingInterectionSelect(py::module &);
void bind_StepVisual_HArray1OfCameraModelD3MultiClippingUnionSelect(py::module &);
void bind_StepVisual_HArray1OfDirectionCountSelect(py::module &);
void bind_StepVisual_HArray1OfLayeredItem(py::module &);
void bind_StepVisual_HArray1OfSurfaceStyleElementSelect(py::module &);
void bind_StepVisual_MarkerMember(py::module &);
void bind_StepVisual_MarkerSelect(py::module &);
void bind_StepVisual_PresentationRepresentation(py::module &);
void bind_StepVisual_PresentationArea(py::module &);
void bind_StepVisual_MechanicalDesignGeometricPresentationArea(py::module &);
void bind_StepVisual_MechanicalDesignGeometricPresentationRepresentation(py::module &);
void bind_StepVisual_NullStyleMember(py::module &);
void bind_StepVisual_PlanarExtent(py::module &);
void bind_StepVisual_PlanarBox(py::module &);
void bind_StepVisual_PointStyle(py::module &);
void bind_StepVisual_PreDefinedTextFont(py::module &);
void bind_StepVisual_PresentationLayerAssignment(py::module &);
void bind_StepVisual_PresentationLayerUsage(py::module &);
void bind_StepVisual_PresentationRepresentationSelect(py::module &);
void bind_StepVisual_PresentationSet(py::module &);
void bind_StepVisual_PresentationSizeAssignmentSelect(py::module &);
void bind_StepVisual_PresentationSize(py::module &);
void bind_StepVisual_PresentationStyleByContext(py::module &);
void bind_StepVisual_PresentationView(py::module &);
void bind_StepVisual_PresentedItemRepresentation(py::module &);
void bind_StepVisual_SurfaceSideStyle(py::module &);
void bind_StepVisual_SurfaceStyleBoundary(py::module &);
void bind_StepVisual_SurfaceStyleControlGrid(py::module &);
void bind_StepVisual_SurfaceStyleFillArea(py::module &);
void bind_StepVisual_SurfaceStyleParameterLine(py::module &);
void bind_StepVisual_SurfaceStyleSegmentationCurve(py::module &);
void bind_StepVisual_SurfaceStyleSilhouette(py::module &);
void bind_StepVisual_SurfaceStyleUsage(py::module &);
void bind_StepVisual_Template(py::module &);
void bind_StepVisual_TemplateInstance(py::module &);
void bind_StepVisual_TessellatedAnnotationOccurrence(py::module &);
void bind_StepVisual_TextLiteral(py::module &);
void bind_StepVisual_TextStyle(py::module &);
void bind_StepVisual_TextStyleForDefinedFont(py::module &);
void bind_StepVisual_TextStyleWithBoxCharacteristics(py::module &);
void bind_StepVisual_ViewVolume(py::module &);

PYBIND11_MODULE(StepVisual, mod) {

py::module::import("OCCT.StepGeom");
py::module::import("OCCT.Standard");
py::module::import("OCCT.TCollection");
py::module::import("OCCT.TColgp");
py::module::import("OCCT.NCollection");
py::module::import("OCCT.TColStd");
py::module::import("OCCT.StepRepr");
py::module::import("OCCT.StepData");
py::module::import("OCCT.StepShape");
py::module::import("OCCT.StepBasic");

bind_StepVisual_CentralOrParallel(mod);
bind_StepVisual_MarkerType(mod);
bind_StepVisual_NullStyle(mod);
bind_StepVisual_SurfaceSide(mod);
bind_StepVisual_TextPath(mod);
bind_StepVisual_TessellatedItem(mod);
bind_StepVisual_CoordinatesList(mod);
bind_StepVisual_VectorOfHSequenceOfInteger(mod);
bind_StepVisual_TessellatedCurveSet(mod);
bind_StepVisual_PresentedItem(mod);
bind_StepVisual_Array1OfTessellatedItem(mod);
bind_StepVisual_TessellatedGeometricSet(mod);
bind_StepVisual_DraughtingModel(mod);
bind_StepVisual_PresentationStyleSelect(mod);
bind_StepVisual_Array1OfPresentationStyleSelect(mod);
bind_StepVisual_HArray1OfPresentationStyleSelect(mod);
bind_StepVisual_PresentationStyleAssignment(mod);
bind_StepVisual_Array1OfPresentationStyleAssignment(mod);
bind_StepVisual_HArray1OfPresentationStyleAssignment(mod);
bind_StepVisual_StyledItemTarget(mod);
bind_StepVisual_StyledItem(mod);
bind_StepVisual_AnnotationOccurrence(mod);
bind_StepVisual_AnnotationCurveOccurrence(mod);
bind_StepVisual_AnnotationCurveOccurrenceAndAnnotationOccurrenceAndGeomReprItemAndReprItemAndStyledItem(mod);
bind_StepVisual_AnnotationFillArea(mod);
bind_StepVisual_AnnotationFillAreaOccurrence(mod);
bind_StepVisual_AnnotationPlaneElement(mod);
bind_StepVisual_Array1OfAnnotationPlaneElement(mod);
bind_StepVisual_HArray1OfAnnotationPlaneElement(mod);
bind_StepVisual_AnnotationPlane(mod);
bind_StepVisual_AnnotationText(mod);
bind_StepVisual_AnnotationTextOccurrence(mod);
bind_StepVisual_AreaInSet(mod);
bind_StepVisual_AreaOrView(mod);
bind_StepVisual_BoxCharacteristicSelect(mod);
bind_StepVisual_Array1OfBoxCharacteristicSelect(mod);
bind_StepVisual_CameraModelD3MultiClippingInterectionSelect(mod);
bind_StepVisual_Array1OfCameraModelD3MultiClippingInterectionSelect(mod);
bind_StepVisual_CameraModelD3MultiClippingUnionSelect(mod);
bind_StepVisual_Array1OfCameraModelD3MultiClippingUnionSelect(mod);
bind_StepVisual_CurveStyleFontPattern(mod);
bind_StepVisual_Array1OfCurveStyleFontPattern(mod);
bind_StepVisual_DirectionCountSelect(mod);
bind_StepVisual_Array1OfDirectionCountSelect(mod);
bind_StepVisual_DraughtingCalloutElement(mod);
bind_StepVisual_Array1OfDraughtingCalloutElement(mod);
bind_StepVisual_FillStyleSelect(mod);
bind_StepVisual_Array1OfFillStyleSelect(mod);
bind_StepVisual_InvisibleItem(mod);
bind_StepVisual_Array1OfInvisibleItem(mod);
bind_StepVisual_LayeredItem(mod);
bind_StepVisual_Array1OfLayeredItem(mod);
bind_StepVisual_StyleContextSelect(mod);
bind_StepVisual_Array1OfStyleContextSelect(mod);
bind_StepVisual_SurfaceStyleElementSelect(mod);
bind_StepVisual_Array1OfSurfaceStyleElementSelect(mod);
bind_StepVisual_TextOrCharacter(mod);
bind_StepVisual_Array1OfTextOrCharacter(mod);
bind_StepVisual_Colour(mod);
bind_StepVisual_BackgroundColour(mod);
bind_StepVisual_CameraImage(mod);
bind_StepVisual_CameraImage2dWithScale(mod);
bind_StepVisual_CameraImage3dWithScale(mod);
bind_StepVisual_CameraModel(mod);
bind_StepVisual_CameraModelD2(mod);
bind_StepVisual_CameraModelD3(mod);
bind_StepVisual_CameraModelD3MultiClipping(mod);
bind_StepVisual_CameraModelD3MultiClippingIntersection(mod);
bind_StepVisual_CameraModelD3MultiClippingUnion(mod);
bind_StepVisual_CameraUsage(mod);
bind_StepVisual_CharacterizedObjectAndCharacterizedRepresentationAndDraughtingModelAndRepresentation(mod);
bind_StepVisual_ColourSpecification(mod);
bind_StepVisual_ColourRgb(mod);
bind_StepVisual_HArray1OfTextOrCharacter(mod);
bind_StepVisual_CompositeText(mod);
bind_StepVisual_CompositeTextWithExtent(mod);
bind_StepVisual_InvisibilityContext(mod);
bind_StepVisual_HArray1OfInvisibleItem(mod);
bind_StepVisual_Invisibility(mod);
bind_StepVisual_ContextDependentInvisibility(mod);
bind_StepVisual_HArray1OfStyleContextSelect(mod);
bind_StepVisual_OverRidingStyledItem(mod);
bind_StepVisual_ContextDependentOverRidingStyledItem(mod);
bind_StepVisual_CurveStyleFontSelect(mod);
bind_StepVisual_CurveStyle(mod);
bind_StepVisual_HArray1OfCurveStyleFontPattern(mod);
bind_StepVisual_CurveStyleFont(mod);
bind_StepVisual_DraughtingAnnotationOccurrence(mod);
bind_StepVisual_HArray1OfDraughtingCalloutElement(mod);
bind_StepVisual_DraughtingCallout(mod);
bind_StepVisual_PreDefinedColour(mod);
bind_StepVisual_DraughtingPreDefinedColour(mod);
bind_StepVisual_PreDefinedItem(mod);
bind_StepVisual_PreDefinedCurveFont(mod);
bind_StepVisual_DraughtingPreDefinedCurveFont(mod);
bind_StepVisual_ExternallyDefinedCurveFont(mod);
bind_StepVisual_ExternallyDefinedTextFont(mod);
bind_StepVisual_HArray1OfFillStyleSelect(mod);
bind_StepVisual_FillAreaStyle(mod);
bind_StepVisual_FillAreaStyleColour(mod);
bind_StepVisual_FontSelect(mod);
bind_StepVisual_HArray1OfBoxCharacteristicSelect(mod);
bind_StepVisual_HArray1OfCameraModelD3MultiClippingInterectionSelect(mod);
bind_StepVisual_HArray1OfCameraModelD3MultiClippingUnionSelect(mod);
bind_StepVisual_HArray1OfDirectionCountSelect(mod);
bind_StepVisual_HArray1OfLayeredItem(mod);
bind_StepVisual_HArray1OfSurfaceStyleElementSelect(mod);
bind_StepVisual_MarkerMember(mod);
bind_StepVisual_MarkerSelect(mod);
bind_StepVisual_PresentationRepresentation(mod);
bind_StepVisual_PresentationArea(mod);
bind_StepVisual_MechanicalDesignGeometricPresentationArea(mod);
bind_StepVisual_MechanicalDesignGeometricPresentationRepresentation(mod);
bind_StepVisual_NullStyleMember(mod);
bind_StepVisual_PlanarExtent(mod);
bind_StepVisual_PlanarBox(mod);
bind_StepVisual_PointStyle(mod);
bind_StepVisual_PreDefinedTextFont(mod);
bind_StepVisual_PresentationLayerAssignment(mod);
bind_StepVisual_PresentationLayerUsage(mod);
bind_StepVisual_PresentationRepresentationSelect(mod);
bind_StepVisual_PresentationSet(mod);
bind_StepVisual_PresentationSizeAssignmentSelect(mod);
bind_StepVisual_PresentationSize(mod);
bind_StepVisual_PresentationStyleByContext(mod);
bind_StepVisual_PresentationView(mod);
bind_StepVisual_PresentedItemRepresentation(mod);
bind_StepVisual_SurfaceSideStyle(mod);
bind_StepVisual_SurfaceStyleBoundary(mod);
bind_StepVisual_SurfaceStyleControlGrid(mod);
bind_StepVisual_SurfaceStyleFillArea(mod);
bind_StepVisual_SurfaceStyleParameterLine(mod);
bind_StepVisual_SurfaceStyleSegmentationCurve(mod);
bind_StepVisual_SurfaceStyleSilhouette(mod);
bind_StepVisual_SurfaceStyleUsage(mod);
bind_StepVisual_Template(mod);
bind_StepVisual_TemplateInstance(mod);
bind_StepVisual_TessellatedAnnotationOccurrence(mod);
bind_StepVisual_TextLiteral(mod);
bind_StepVisual_TextStyle(mod);
bind_StepVisual_TextStyleForDefinedFont(mod);
bind_StepVisual_TextStyleWithBoxCharacteristics(mod);
bind_StepVisual_ViewVolume(mod);

}
