#include <pyOCCT_Common.hpp>

#include <BRepBuilderAPI_MakeShape.hxx>
#include <TopoDS_Edge.hxx>
#include <Standard_TypeDef.hxx>
#include <TopoDS_Vertex.hxx>
#include <Standard_Handle.hxx>
#include <ChFiDS_SecHArray1.hxx>
#include <BRepFilletAPI_LocalOperation.hxx>
#include <TopoDS_Shape.hxx>
#include <TopoDS_Face.hxx>
#include <TopOpeBRepBuild_HBuilder.hxx>
#include <TopTools_ListOfShape.hxx>
#include <BRepFilletAPI_MakeChamfer.hxx>
#include <ChFi3d_FilletShape.hxx>
#include <GeomAbs_Shape.hxx>
#include <Law_Function.hxx>
#include <TColgp_Array1OfPnt2d.hxx>
#include <Geom_Surface.hxx>
#include <ChFiDS_ErrorStatus.hxx>
#include <BRepFilletAPI_MakeFillet.hxx>
#include <TopTools_SequenceOfShape.hxx>
#include <ChFi2d_ConstructionError.hxx>
#include <BRepFilletAPI_MakeFillet2d.hxx>

PYBIND11_MODULE(BRepFilletAPI, mod) {

	// IMPORT
	py::module::import("OCCT.BRepBuilderAPI");
	py::module::import("OCCT.TopoDS");
	py::module::import("OCCT.Standard");
	py::module::import("OCCT.ChFiDS");
	py::module::import("OCCT.TopOpeBRepBuild");
	py::module::import("OCCT.TopTools");
	py::module::import("OCCT.ChFi3d");
	py::module::import("OCCT.GeomAbs");
	py::module::import("OCCT.Law");
	py::module::import("OCCT.TColgp");
	py::module::import("OCCT.Geom");
	py::module::import("OCCT.ChFi2d");

	py::module other_mod;

	// IMPORT GUARDS

	// ENUMS

	// FUNCTIONS

	// CLASSES
	// C:\Miniconda\envs\occt\Library\include\opencascade\BRepFilletAPI_LocalOperation.hxx
	py::class_<BRepFilletAPI_LocalOperation, std::unique_ptr<BRepFilletAPI_LocalOperation, Deleter<BRepFilletAPI_LocalOperation>>, BRepBuilderAPI_MakeShape> cls_BRepFilletAPI_LocalOperation(mod, "BRepFilletAPI_LocalOperation", "Construction of fillets on the edges of a Shell.");
	cls_BRepFilletAPI_LocalOperation.def("Add", (void (BRepFilletAPI_LocalOperation::*)(const TopoDS_Edge &)) &BRepFilletAPI_LocalOperation::Add, "Adds a contour in the builder (builds a contour of tangent edges).", py::arg("E"));
	cls_BRepFilletAPI_LocalOperation.def("ResetContour", (void (BRepFilletAPI_LocalOperation::*)(const Standard_Integer)) &BRepFilletAPI_LocalOperation::ResetContour, "Reset the contour of index IC, there is nomore information in the contour.", py::arg("IC"));
	cls_BRepFilletAPI_LocalOperation.def("NbContours", (Standard_Integer (BRepFilletAPI_LocalOperation::*)() const ) &BRepFilletAPI_LocalOperation::NbContours, "Number of contours.");
	cls_BRepFilletAPI_LocalOperation.def("Contour", (Standard_Integer (BRepFilletAPI_LocalOperation::*)(const TopoDS_Edge &) const ) &BRepFilletAPI_LocalOperation::Contour, "Returns the index of the contour containing the edge E, returns 0 if E doesn't belong to any contour.", py::arg("E"));
	cls_BRepFilletAPI_LocalOperation.def("NbEdges", (Standard_Integer (BRepFilletAPI_LocalOperation::*)(const Standard_Integer) const ) &BRepFilletAPI_LocalOperation::NbEdges, "Number of Edges in the contour I.", py::arg("I"));
	cls_BRepFilletAPI_LocalOperation.def("Edge", (const TopoDS_Edge & (BRepFilletAPI_LocalOperation::*)(const Standard_Integer, const Standard_Integer) const ) &BRepFilletAPI_LocalOperation::Edge, "Returns the Edge J in the contour I.", py::arg("I"), py::arg("J"));
	cls_BRepFilletAPI_LocalOperation.def("Remove", (void (BRepFilletAPI_LocalOperation::*)(const TopoDS_Edge &)) &BRepFilletAPI_LocalOperation::Remove, "remove the contour containing the Edge E.", py::arg("E"));
	cls_BRepFilletAPI_LocalOperation.def("Length", (Standard_Real (BRepFilletAPI_LocalOperation::*)(const Standard_Integer) const ) &BRepFilletAPI_LocalOperation::Length, "returns the length the contour of index IC.", py::arg("IC"));
	cls_BRepFilletAPI_LocalOperation.def("FirstVertex", (TopoDS_Vertex (BRepFilletAPI_LocalOperation::*)(const Standard_Integer) const ) &BRepFilletAPI_LocalOperation::FirstVertex, "Returns the first Vertex of the contour of index IC.", py::arg("IC"));
	cls_BRepFilletAPI_LocalOperation.def("LastVertex", (TopoDS_Vertex (BRepFilletAPI_LocalOperation::*)(const Standard_Integer) const ) &BRepFilletAPI_LocalOperation::LastVertex, "Returns the last Vertex of the contour of index IC.", py::arg("IC"));
	cls_BRepFilletAPI_LocalOperation.def("Abscissa", (Standard_Real (BRepFilletAPI_LocalOperation::*)(const Standard_Integer, const TopoDS_Vertex &) const ) &BRepFilletAPI_LocalOperation::Abscissa, "returns the abscissa of the vertex V on the contour of index IC.", py::arg("IC"), py::arg("V"));
	cls_BRepFilletAPI_LocalOperation.def("RelativeAbscissa", (Standard_Real (BRepFilletAPI_LocalOperation::*)(const Standard_Integer, const TopoDS_Vertex &) const ) &BRepFilletAPI_LocalOperation::RelativeAbscissa, "returns the relative abscissa([0.,1.]) of the vertex V on the contour of index IC.", py::arg("IC"), py::arg("V"));
	cls_BRepFilletAPI_LocalOperation.def("ClosedAndTangent", (Standard_Boolean (BRepFilletAPI_LocalOperation::*)(const Standard_Integer) const ) &BRepFilletAPI_LocalOperation::ClosedAndTangent, "returns true if the contour of index IC is closed an tangent.", py::arg("IC"));
	cls_BRepFilletAPI_LocalOperation.def("Closed", (Standard_Boolean (BRepFilletAPI_LocalOperation::*)(const Standard_Integer) const ) &BRepFilletAPI_LocalOperation::Closed, "returns true if the contour of index IC is closed", py::arg("IC"));
	cls_BRepFilletAPI_LocalOperation.def("Reset", (void (BRepFilletAPI_LocalOperation::*)()) &BRepFilletAPI_LocalOperation::Reset, "Reset all the fields updated by Build operation and leave the algorithm in the same state than before build call. It allows contours and radius modifications to build the result another time.");
	cls_BRepFilletAPI_LocalOperation.def("Simulate", (void (BRepFilletAPI_LocalOperation::*)(const Standard_Integer)) &BRepFilletAPI_LocalOperation::Simulate, "None", py::arg("IC"));
	cls_BRepFilletAPI_LocalOperation.def("NbSurf", (Standard_Integer (BRepFilletAPI_LocalOperation::*)(const Standard_Integer) const ) &BRepFilletAPI_LocalOperation::NbSurf, "None", py::arg("IC"));
	cls_BRepFilletAPI_LocalOperation.def("Sect", (opencascade::handle<ChFiDS_SecHArray1> (BRepFilletAPI_LocalOperation::*)(const Standard_Integer, const Standard_Integer) const ) &BRepFilletAPI_LocalOperation::Sect, "None", py::arg("IC"), py::arg("IS"));

	// C:\Miniconda\envs\occt\Library\include\opencascade\BRepFilletAPI_MakeChamfer.hxx
	py::class_<BRepFilletAPI_MakeChamfer, std::unique_ptr<BRepFilletAPI_MakeChamfer, Deleter<BRepFilletAPI_MakeChamfer>>, BRepFilletAPI_LocalOperation> cls_BRepFilletAPI_MakeChamfer(mod, "BRepFilletAPI_MakeChamfer", "Describes functions to build chamfers on edges of a shell or solid. Chamfered Edge of a Shell or Solid A MakeChamfer object provides a framework for: - initializing the construction algorithm with a given shape, - acquiring the data characterizing the chamfers, - building the chamfers and constructing the resulting shape, and - consulting the result.");
	cls_BRepFilletAPI_MakeChamfer.def(py::init<const TopoDS_Shape &>(), py::arg("S"));
	cls_BRepFilletAPI_MakeChamfer.def("Add", (void (BRepFilletAPI_MakeChamfer::*)(const TopoDS_Edge &)) &BRepFilletAPI_MakeChamfer::Add, "Adds edge E to the table of edges used by this algorithm to build chamfers, where the parameters of the chamfer must be set after the", py::arg("E"));
	cls_BRepFilletAPI_MakeChamfer.def("Add", (void (BRepFilletAPI_MakeChamfer::*)(const Standard_Real, const TopoDS_Edge &, const TopoDS_Face &)) &BRepFilletAPI_MakeChamfer::Add, "Adds edge E to the table of edges used by this algorithm to build chamfers, where the parameters of the chamfer are given by the two distances Dis1 and Dis2; the face F identifies the side where Dis1 is measured. The Add function results in a contour being built by propagation from the edge E (i.e. the contour contains at least this edge). This contour is composed of edges of the shape which are tangential to one another and which delimit two series of tangential faces, with one series of faces being located on either side of the contour. Warning Nothing is done if edge E or the face F does not belong to the initial shape.", py::arg("Dis"), py::arg("E"), py::arg("F"));
	cls_BRepFilletAPI_MakeChamfer.def("SetDist", (void (BRepFilletAPI_MakeChamfer::*)(const Standard_Real, const Standard_Integer, const TopoDS_Face &)) &BRepFilletAPI_MakeChamfer::SetDist, "Sets the distances Dis1 and Dis2 which give the parameters of the chamfer along the contour of index IC generated using the Add function in the internal data structure of this algorithm. The face F identifies the side where Dis1 is measured. Warning Nothing is done if either the edge E or the face F does not belong to the initial shape.", py::arg("Dis"), py::arg("IC"), py::arg("F"));
	cls_BRepFilletAPI_MakeChamfer.def("GetDist", (void (BRepFilletAPI_MakeChamfer::*)(const Standard_Integer, Standard_Real &) const ) &BRepFilletAPI_MakeChamfer::GetDist, "None", py::arg("IC"), py::arg("Dis"));
	cls_BRepFilletAPI_MakeChamfer.def("Add", (void (BRepFilletAPI_MakeChamfer::*)(const Standard_Real, const Standard_Real, const TopoDS_Edge &, const TopoDS_Face &)) &BRepFilletAPI_MakeChamfer::Add, "Adds a fillet contour in the builder (builds a contour of tangent edges to <E> and sets the two distances <Dis1> and <Dis2> ( parameters of the chamfer ) ).", py::arg("Dis1"), py::arg("Dis2"), py::arg("E"), py::arg("F"));
	cls_BRepFilletAPI_MakeChamfer.def("SetDists", (void (BRepFilletAPI_MakeChamfer::*)(const Standard_Real, const Standard_Real, const Standard_Integer, const TopoDS_Face &)) &BRepFilletAPI_MakeChamfer::SetDists, "Sets the distances Dis1 and Dis2 which give the parameters of the chamfer along the contour of index IC generated using the Add function in the internal data structure of this algorithm. The face F identifies the side where Dis1 is measured. Warning Nothing is done if either the edge E or the face F does not belong to the initial shape.", py::arg("Dis1"), py::arg("Dis2"), py::arg("IC"), py::arg("F"));
	cls_BRepFilletAPI_MakeChamfer.def("Dists", (void (BRepFilletAPI_MakeChamfer::*)(const Standard_Integer, Standard_Real &, Standard_Real &) const ) &BRepFilletAPI_MakeChamfer::Dists, "Returns the distances Dis1 and Dis2 which give the parameters of the chamfer along the contour of index IC in the internal data structure of this algorithm. Warning -1. is returned if IC is outside the bounds of the table of contours.", py::arg("IC"), py::arg("Dis1"), py::arg("Dis2"));
	cls_BRepFilletAPI_MakeChamfer.def("AddDA", (void (BRepFilletAPI_MakeChamfer::*)(const Standard_Real, const Standard_Real, const TopoDS_Edge &, const TopoDS_Face &)) &BRepFilletAPI_MakeChamfer::AddDA, "Adds a fillet contour in the builder (builds a contour of tangent edges to <E> and sets the distance <Dis1> and angle <Angle> ( parameters of the chamfer ) ).", py::arg("Dis"), py::arg("Angle"), py::arg("E"), py::arg("F"));
	cls_BRepFilletAPI_MakeChamfer.def("SetDistAngle", (void (BRepFilletAPI_MakeChamfer::*)(const Standard_Real, const Standard_Real, const Standard_Integer, const TopoDS_Face &)) &BRepFilletAPI_MakeChamfer::SetDistAngle, "set the distance <Dis> and <Angle> of the fillet contour of index <IC> in the DS with <Dis> on <F>. if the face <F> is not one of common faces of an edge of the contour <IC>", py::arg("Dis"), py::arg("Angle"), py::arg("IC"), py::arg("F"));
	cls_BRepFilletAPI_MakeChamfer.def("GetDistAngle", (void (BRepFilletAPI_MakeChamfer::*)(const Standard_Integer, Standard_Real &, Standard_Real &, Standard_Boolean &) const ) &BRepFilletAPI_MakeChamfer::GetDistAngle, "gives the distances <Dis> and <Angle> of the fillet contour of index <IC> in the DS", py::arg("IC"), py::arg("Dis"), py::arg("Angle"), py::arg("DisOnFace1"));
	cls_BRepFilletAPI_MakeChamfer.def("IsSymetric", (Standard_Boolean (BRepFilletAPI_MakeChamfer::*)(const Standard_Integer) const ) &BRepFilletAPI_MakeChamfer::IsSymetric, "return True if chamfer symetric false else.", py::arg("IC"));
	cls_BRepFilletAPI_MakeChamfer.def("IsTwoDistances", (Standard_Boolean (BRepFilletAPI_MakeChamfer::*)(const Standard_Integer) const ) &BRepFilletAPI_MakeChamfer::IsTwoDistances, "return True if chamfer is made with two distances false else.", py::arg("IC"));
	cls_BRepFilletAPI_MakeChamfer.def("IsDistanceAngle", (Standard_Boolean (BRepFilletAPI_MakeChamfer::*)(const Standard_Integer) const ) &BRepFilletAPI_MakeChamfer::IsDistanceAngle, "return True if chamfer is made with distance and angle false else.", py::arg("IC"));
	cls_BRepFilletAPI_MakeChamfer.def("ResetContour", (void (BRepFilletAPI_MakeChamfer::*)(const Standard_Integer)) &BRepFilletAPI_MakeChamfer::ResetContour, "Erases the chamfer parameters on the contour of index IC in the internal data structure of this algorithm. Use the SetDists function to reset this data. Warning Nothing is done if IC is outside the bounds of the table of contours.", py::arg("IC"));
	cls_BRepFilletAPI_MakeChamfer.def("NbContours", (Standard_Integer (BRepFilletAPI_MakeChamfer::*)() const ) &BRepFilletAPI_MakeChamfer::NbContours, "Returns the number of contours generated using the Add function in the internal data structure of this algorithm.");
	cls_BRepFilletAPI_MakeChamfer.def("Contour", (Standard_Integer (BRepFilletAPI_MakeChamfer::*)(const TopoDS_Edge &) const ) &BRepFilletAPI_MakeChamfer::Contour, "Returns the index of the contour in the internal data structure of this algorithm, which contains the edge E of the shape. This function returns 0 if the edge E does not belong to any contour. Warning This index can change if a contour is removed from the internal data structure of this algorithm using the function Remove.", py::arg("E"));
	cls_BRepFilletAPI_MakeChamfer.def("NbEdges", (Standard_Integer (BRepFilletAPI_MakeChamfer::*)(const Standard_Integer) const ) &BRepFilletAPI_MakeChamfer::NbEdges, "Returns the number of edges in the contour of index I in the internal data structure of this algorithm. Warning Returns 0 if I is outside the bounds of the table of contours.", py::arg("I"));
	cls_BRepFilletAPI_MakeChamfer.def("Edge", (const TopoDS_Edge & (BRepFilletAPI_MakeChamfer::*)(const Standard_Integer, const Standard_Integer) const ) &BRepFilletAPI_MakeChamfer::Edge, "Returns the edge of index J in the contour of index I in the internal data structure of this algorithm. Warning Returns a null shape if: - I is outside the bounds of the table of contours, or - J is outside the bounds of the table of edges of the contour of index I.", py::arg("I"), py::arg("J"));
	cls_BRepFilletAPI_MakeChamfer.def("Remove", (void (BRepFilletAPI_MakeChamfer::*)(const TopoDS_Edge &)) &BRepFilletAPI_MakeChamfer::Remove, "Removes the contour in the internal data structure of this algorithm which contains the edge E of the shape. Warning Nothing is done if the edge E does not belong to the contour in the internal data structure of this algorithm.", py::arg("E"));
	cls_BRepFilletAPI_MakeChamfer.def("Length", (Standard_Real (BRepFilletAPI_MakeChamfer::*)(const Standard_Integer) const ) &BRepFilletAPI_MakeChamfer::Length, "Returns the length of the contour of index IC in the internal data structure of this algorithm. Warning Returns -1. if IC is outside the bounds of the table of contours.", py::arg("IC"));
	cls_BRepFilletAPI_MakeChamfer.def("FirstVertex", (TopoDS_Vertex (BRepFilletAPI_MakeChamfer::*)(const Standard_Integer) const ) &BRepFilletAPI_MakeChamfer::FirstVertex, "Returns the first vertex of the contour of index IC in the internal data structure of this algorithm. Warning Returns a null shape if IC is outside the bounds of the table of contours.", py::arg("IC"));
	cls_BRepFilletAPI_MakeChamfer.def("LastVertex", (TopoDS_Vertex (BRepFilletAPI_MakeChamfer::*)(const Standard_Integer) const ) &BRepFilletAPI_MakeChamfer::LastVertex, "Returns the last vertex of the contour of index IC in the internal data structure of this algorithm. Warning Returns a null shape if IC is outside the bounds of the table of contours.", py::arg("IC"));
	cls_BRepFilletAPI_MakeChamfer.def("Abscissa", (Standard_Real (BRepFilletAPI_MakeChamfer::*)(const Standard_Integer, const TopoDS_Vertex &) const ) &BRepFilletAPI_MakeChamfer::Abscissa, "Returns the curvilinear abscissa of the vertex V on the contour of index IC in the internal data structure of this algorithm. Warning Returns -1. if: - IC is outside the bounds of the table of contours, or - V is not on the contour of index IC.", py::arg("IC"), py::arg("V"));
	cls_BRepFilletAPI_MakeChamfer.def("RelativeAbscissa", (Standard_Real (BRepFilletAPI_MakeChamfer::*)(const Standard_Integer, const TopoDS_Vertex &) const ) &BRepFilletAPI_MakeChamfer::RelativeAbscissa, "Returns the relative curvilinear abscissa (i.e. between 0 and 1) of the vertex V on the contour of index IC in the internal data structure of this algorithm. Warning Returns -1. if: - IC is outside the bounds of the table of contours, or - V is not on the contour of index IC.", py::arg("IC"), py::arg("V"));
	cls_BRepFilletAPI_MakeChamfer.def("ClosedAndTangent", (Standard_Boolean (BRepFilletAPI_MakeChamfer::*)(const Standard_Integer) const ) &BRepFilletAPI_MakeChamfer::ClosedAndTangent, "eturns true if the contour of index IC in the internal data structure of this algorithm is closed and tangential at the point of closure. Warning Returns false if IC is outside the bounds of the table of contours.", py::arg("IC"));
	cls_BRepFilletAPI_MakeChamfer.def("Closed", (Standard_Boolean (BRepFilletAPI_MakeChamfer::*)(const Standard_Integer) const ) &BRepFilletAPI_MakeChamfer::Closed, "Returns true if the contour of index IC in the internal data structure of this algorithm is closed. Warning Returns false if IC is outside the bounds of the table of contours.", py::arg("IC"));
	cls_BRepFilletAPI_MakeChamfer.def("Build", (void (BRepFilletAPI_MakeChamfer::*)()) &BRepFilletAPI_MakeChamfer::Build, "Builds the chamfers on all the contours in the internal data structure of this algorithm and constructs the resulting shape. Use the function IsDone to verify that the chamfered shape is built. Use the function Shape to retrieve the chamfered shape. Warning The construction of chamfers implements highly complex construction algorithms. Consequently, there may be instances where the algorithm fails, for example if the data defining the parameters of the chamfer is not compatible with the geometry of the initial shape. There is no initial analysis of errors and these only become evident at the construction stage. Additionally, in the current software release, the following cases are not handled: - the end point of the contour is the point of intersection of 4 or more edges of the shape, or - the intersection of the chamfer with a face which limits the contour is not fully contained in this face.");
	cls_BRepFilletAPI_MakeChamfer.def("Reset", (void (BRepFilletAPI_MakeChamfer::*)()) &BRepFilletAPI_MakeChamfer::Reset, "Reinitializes this algorithm, thus canceling the effects of the Build function. This function allows modifications to be made to the contours and chamfer parameters in order to rebuild the shape.");
	cls_BRepFilletAPI_MakeChamfer.def("Builder", (opencascade::handle<TopOpeBRepBuild_HBuilder> (BRepFilletAPI_MakeChamfer::*)() const ) &BRepFilletAPI_MakeChamfer::Builder, "Returns the internal filleting algorithm.");
	cls_BRepFilletAPI_MakeChamfer.def("Generated", (const TopTools_ListOfShape & (BRepFilletAPI_MakeChamfer::*)(const TopoDS_Shape &)) &BRepFilletAPI_MakeChamfer::Generated, "Returns the list of shapes generated from the shape <EorV>.", py::arg("EorV"));
	cls_BRepFilletAPI_MakeChamfer.def("Modified", (const TopTools_ListOfShape & (BRepFilletAPI_MakeChamfer::*)(const TopoDS_Shape &)) &BRepFilletAPI_MakeChamfer::Modified, "Returns the list of shapes modified from the shape <F>.", py::arg("F"));
	cls_BRepFilletAPI_MakeChamfer.def("IsDeleted", (Standard_Boolean (BRepFilletAPI_MakeChamfer::*)(const TopoDS_Shape &)) &BRepFilletAPI_MakeChamfer::IsDeleted, "None", py::arg("F"));
	cls_BRepFilletAPI_MakeChamfer.def("Simulate", (void (BRepFilletAPI_MakeChamfer::*)(const Standard_Integer)) &BRepFilletAPI_MakeChamfer::Simulate, "None", py::arg("IC"));
	cls_BRepFilletAPI_MakeChamfer.def("NbSurf", (Standard_Integer (BRepFilletAPI_MakeChamfer::*)(const Standard_Integer) const ) &BRepFilletAPI_MakeChamfer::NbSurf, "None", py::arg("IC"));
	cls_BRepFilletAPI_MakeChamfer.def("Sect", (opencascade::handle<ChFiDS_SecHArray1> (BRepFilletAPI_MakeChamfer::*)(const Standard_Integer, const Standard_Integer) const ) &BRepFilletAPI_MakeChamfer::Sect, "None", py::arg("IC"), py::arg("IS"));

	// C:\Miniconda\envs\occt\Library\include\opencascade\BRepFilletAPI_MakeFillet.hxx
	py::class_<BRepFilletAPI_MakeFillet, std::unique_ptr<BRepFilletAPI_MakeFillet, Deleter<BRepFilletAPI_MakeFillet>>, BRepFilletAPI_LocalOperation> cls_BRepFilletAPI_MakeFillet(mod, "BRepFilletAPI_MakeFillet", "Describes functions to build fillets on the broken edges of a shell or solid. A MakeFillet object provides a framework for: - initializing the construction algorithm with a given shape, - acquiring the data characterizing the fillets, - building the fillets and constructing the resulting shape, and - consulting the result.");
	cls_BRepFilletAPI_MakeFillet.def(py::init<const TopoDS_Shape &>(), py::arg("S"));
	cls_BRepFilletAPI_MakeFillet.def(py::init<const TopoDS_Shape &, const ChFi3d_FilletShape>(), py::arg("S"), py::arg("FShape"));
	cls_BRepFilletAPI_MakeFillet.def("SetParams", (void (BRepFilletAPI_MakeFillet::*)(const Standard_Real, const Standard_Real, const Standard_Real, const Standard_Real, const Standard_Real, const Standard_Real)) &BRepFilletAPI_MakeFillet::SetParams, "None", py::arg("Tang"), py::arg("Tesp"), py::arg("T2d"), py::arg("TApp3d"), py::arg("TolApp2d"), py::arg("Fleche"));
	cls_BRepFilletAPI_MakeFillet.def("SetContinuity", (void (BRepFilletAPI_MakeFillet::*)(const GeomAbs_Shape, const Standard_Real)) &BRepFilletAPI_MakeFillet::SetContinuity, "Changes the parameters of continiuity InternalContinuity to produce fillet'surfaces with an continuity Ci (i=0,1 or 2). By defaultInternalContinuity = GeomAbs_C1. AngularTolerance is the G1 tolerance between fillet and support'faces.", py::arg("InternalContinuity"), py::arg("AngularTolerance"));
	cls_BRepFilletAPI_MakeFillet.def("Add", (void (BRepFilletAPI_MakeFillet::*)(const TopoDS_Edge &)) &BRepFilletAPI_MakeFillet::Add, "Adds a fillet contour in the builder (builds a contour of tangent edges). The Radius must be set after.", py::arg("E"));
	cls_BRepFilletAPI_MakeFillet.def("Add", (void (BRepFilletAPI_MakeFillet::*)(const Standard_Real, const TopoDS_Edge &)) &BRepFilletAPI_MakeFillet::Add, "Adds a fillet description in the builder - builds a contour of tangent edges, - sets the radius.", py::arg("Radius"), py::arg("E"));
	cls_BRepFilletAPI_MakeFillet.def("Add", (void (BRepFilletAPI_MakeFillet::*)(const Standard_Real, const Standard_Real, const TopoDS_Edge &)) &BRepFilletAPI_MakeFillet::Add, "Adds a fillet description in the builder - builds a contour of tangent edges, - sets a linear radius evolution law between the first and last vertex of the spine.", py::arg("R1"), py::arg("R2"), py::arg("E"));
	cls_BRepFilletAPI_MakeFillet.def("Add", (void (BRepFilletAPI_MakeFillet::*)(const opencascade::handle<Law_Function> &, const TopoDS_Edge &)) &BRepFilletAPI_MakeFillet::Add, "Adds a fillet description in the builder - builds a contour of tangent edges, - sest the radius evolution law.", py::arg("L"), py::arg("E"));
	cls_BRepFilletAPI_MakeFillet.def("Add", (void (BRepFilletAPI_MakeFillet::*)(const TColgp_Array1OfPnt2d &, const TopoDS_Edge &)) &BRepFilletAPI_MakeFillet::Add, "Adds a fillet description in the builder - builds a contour of tangent edges, - sets the radius evolution law interpolating the values given in the array UandR :", py::arg("UandR"), py::arg("E"));
	cls_BRepFilletAPI_MakeFillet.def("SetRadius", (void (BRepFilletAPI_MakeFillet::*)(const Standard_Real, const Standard_Integer, const Standard_Integer)) &BRepFilletAPI_MakeFillet::SetRadius, "Sets the parameters of the fillet along the contour of index IC generated using the Add function in the internal data structure of this algorithm, where Radius is the radius of the fillet.", py::arg("Radius"), py::arg("IC"), py::arg("IinC"));
	cls_BRepFilletAPI_MakeFillet.def("SetRadius", (void (BRepFilletAPI_MakeFillet::*)(const Standard_Real, const Standard_Real, const Standard_Integer, const Standard_Integer)) &BRepFilletAPI_MakeFillet::SetRadius, "Sets the parameters of the fillet along the contour of index IC generated using the Add function in the internal data structure of this algorithm, where the radius of the fillet evolves according to a linear evolution law defined from R1 to R2, between the first and last vertices of the contour of index IC.", py::arg("R1"), py::arg("R2"), py::arg("IC"), py::arg("IinC"));
	cls_BRepFilletAPI_MakeFillet.def("SetRadius", (void (BRepFilletAPI_MakeFillet::*)(const opencascade::handle<Law_Function> &, const Standard_Integer, const Standard_Integer)) &BRepFilletAPI_MakeFillet::SetRadius, "Sets the parameters of the fillet along the contour of index IC generated using the Add function in the internal data structure of this algorithm, where the radius of the fillet evolves according to the evolution law L, between the first and last vertices of the contour of index IC.", py::arg("L"), py::arg("IC"), py::arg("IinC"));
	cls_BRepFilletAPI_MakeFillet.def("SetRadius", (void (BRepFilletAPI_MakeFillet::*)(const TColgp_Array1OfPnt2d &, const Standard_Integer, const Standard_Integer)) &BRepFilletAPI_MakeFillet::SetRadius, "Sets the parameters of the fillet along the contour of index IC generated using the Add function in the internal data structure of this algorithm, where the radius of the fillet evolves according to the evolution law which interpolates the set of parameter and radius pairs given in the array UandR as follows: - the X coordinate of a point in UandR defines a relative parameter on the contour (i.e. a parameter between 0 and 1), - the Y coordinate of a point in UandR gives the corresponding value of the radius, and the radius evolves between the first and last vertices of the contour of index IC.", py::arg("UandR"), py::arg("IC"), py::arg("IinC"));
	cls_BRepFilletAPI_MakeFillet.def("ResetContour", (void (BRepFilletAPI_MakeFillet::*)(const Standard_Integer)) &BRepFilletAPI_MakeFillet::ResetContour, "Erases the radius information on the contour of index IC in the internal data structure of this algorithm. Use the SetRadius function to reset this data. Warning Nothing is done if IC is outside the bounds of the table of contours.", py::arg("IC"));
	cls_BRepFilletAPI_MakeFillet.def("IsConstant", (Standard_Boolean (BRepFilletAPI_MakeFillet::*)(const Standard_Integer)) &BRepFilletAPI_MakeFillet::IsConstant, "Returns true if the radius of the fillet along the contour of index IC in the internal data structure of this algorithm is constant, Warning False is returned if IC is outside the bounds of the table of contours or if E does not belong to the contour of index IC.", py::arg("IC"));
	cls_BRepFilletAPI_MakeFillet.def("Radius", (Standard_Real (BRepFilletAPI_MakeFillet::*)(const Standard_Integer)) &BRepFilletAPI_MakeFillet::Radius, "Returns the radius of the fillet along the contour of index IC in the internal data structure of this algorithm Warning - Use this function only if the radius is constant. - -1. is returned if IC is outside the bounds of the table of contours or if E does not belong to the contour of index IC.", py::arg("IC"));
	cls_BRepFilletAPI_MakeFillet.def("IsConstant", (Standard_Boolean (BRepFilletAPI_MakeFillet::*)(const Standard_Integer, const TopoDS_Edge &)) &BRepFilletAPI_MakeFillet::IsConstant, "Returns true if the radius of the fillet along the edge E of the contour of index IC in the internal data structure of this algorithm is constant. Warning False is returned if IC is outside the bounds of the table of contours or if E does not belong to the contour of index IC.", py::arg("IC"), py::arg("E"));
	cls_BRepFilletAPI_MakeFillet.def("Radius", (Standard_Real (BRepFilletAPI_MakeFillet::*)(const Standard_Integer, const TopoDS_Edge &)) &BRepFilletAPI_MakeFillet::Radius, "Returns the radius of the fillet along the edge E of the contour of index IC in the internal data structure of this algorithm. Warning - Use this function only if the radius is constant. - -1 is returned if IC is outside the bounds of the table of contours or if E does not belong to the contour of index IC.", py::arg("IC"), py::arg("E"));
	cls_BRepFilletAPI_MakeFillet.def("SetRadius", (void (BRepFilletAPI_MakeFillet::*)(const Standard_Real, const Standard_Integer, const TopoDS_Edge &)) &BRepFilletAPI_MakeFillet::SetRadius, "Assigns Radius as the radius of the fillet on the edge E", py::arg("Radius"), py::arg("IC"), py::arg("E"));
	cls_BRepFilletAPI_MakeFillet.def("SetRadius", (void (BRepFilletAPI_MakeFillet::*)(const Standard_Real, const Standard_Integer, const TopoDS_Vertex &)) &BRepFilletAPI_MakeFillet::SetRadius, "None", py::arg("Radius"), py::arg("IC"), py::arg("V"));
	cls_BRepFilletAPI_MakeFillet.def("GetBounds", (Standard_Boolean (BRepFilletAPI_MakeFillet::*)(const Standard_Integer, const TopoDS_Edge &, Standard_Real &, Standard_Real &)) &BRepFilletAPI_MakeFillet::GetBounds, "None", py::arg("IC"), py::arg("E"), py::arg("F"), py::arg("L"));
	cls_BRepFilletAPI_MakeFillet.def("GetLaw", (opencascade::handle<Law_Function> (BRepFilletAPI_MakeFillet::*)(const Standard_Integer, const TopoDS_Edge &)) &BRepFilletAPI_MakeFillet::GetLaw, "None", py::arg("IC"), py::arg("E"));
	cls_BRepFilletAPI_MakeFillet.def("SetLaw", (void (BRepFilletAPI_MakeFillet::*)(const Standard_Integer, const TopoDS_Edge &, const opencascade::handle<Law_Function> &)) &BRepFilletAPI_MakeFillet::SetLaw, "None", py::arg("IC"), py::arg("E"), py::arg("L"));
	cls_BRepFilletAPI_MakeFillet.def("SetFilletShape", (void (BRepFilletAPI_MakeFillet::*)(const ChFi3d_FilletShape)) &BRepFilletAPI_MakeFillet::SetFilletShape, "Assigns FShape as the type of fillet shape built by this algorithm.", py::arg("FShape"));
	cls_BRepFilletAPI_MakeFillet.def("GetFilletShape", (ChFi3d_FilletShape (BRepFilletAPI_MakeFillet::*)() const ) &BRepFilletAPI_MakeFillet::GetFilletShape, "Returns the type of fillet shape built by this algorithm.");
	cls_BRepFilletAPI_MakeFillet.def("NbContours", (Standard_Integer (BRepFilletAPI_MakeFillet::*)() const ) &BRepFilletAPI_MakeFillet::NbContours, "Returns the number of contours generated using the Add function in the internal data structure of this algorithm.");
	cls_BRepFilletAPI_MakeFillet.def("Contour", (Standard_Integer (BRepFilletAPI_MakeFillet::*)(const TopoDS_Edge &) const ) &BRepFilletAPI_MakeFillet::Contour, "Returns the index of the contour in the internal data structure of this algorithm which contains the edge E of the shape. This function returns 0 if the edge E does not belong to any contour. Warning This index can change if a contour is removed from the internal data structure of this algorithm using the function Remove.", py::arg("E"));
	cls_BRepFilletAPI_MakeFillet.def("NbEdges", (Standard_Integer (BRepFilletAPI_MakeFillet::*)(const Standard_Integer) const ) &BRepFilletAPI_MakeFillet::NbEdges, "Returns the number of edges in the contour of index I in the internal data structure of this algorithm. Warning Returns 0 if I is outside the bounds of the table of contours.", py::arg("I"));
	cls_BRepFilletAPI_MakeFillet.def("Edge", (const TopoDS_Edge & (BRepFilletAPI_MakeFillet::*)(const Standard_Integer, const Standard_Integer) const ) &BRepFilletAPI_MakeFillet::Edge, "Returns the edge of index J in the contour of index I in the internal data structure of this algorithm. Warning Returns a null shape if: - I is outside the bounds of the table of contours, or - J is outside the bounds of the table of edges of the index I contour.", py::arg("I"), py::arg("J"));
	cls_BRepFilletAPI_MakeFillet.def("Remove", (void (BRepFilletAPI_MakeFillet::*)(const TopoDS_Edge &)) &BRepFilletAPI_MakeFillet::Remove, "Removes the contour in the internal data structure of this algorithm which contains the edge E of the shape. Warning Nothing is done if the edge E does not belong to the contour in the internal data structure of this algorithm.", py::arg("E"));
	cls_BRepFilletAPI_MakeFillet.def("Length", (Standard_Real (BRepFilletAPI_MakeFillet::*)(const Standard_Integer) const ) &BRepFilletAPI_MakeFillet::Length, "Returns the length of the contour of index IC in the internal data structure of this algorithm. Warning Returns -1. if IC is outside the bounds of the table of contours.", py::arg("IC"));
	cls_BRepFilletAPI_MakeFillet.def("FirstVertex", (TopoDS_Vertex (BRepFilletAPI_MakeFillet::*)(const Standard_Integer) const ) &BRepFilletAPI_MakeFillet::FirstVertex, "Returns the first vertex of the contour of index IC in the internal data structure of this algorithm. Warning Returns a null shape if IC is outside the bounds of the table of contours.", py::arg("IC"));
	cls_BRepFilletAPI_MakeFillet.def("LastVertex", (TopoDS_Vertex (BRepFilletAPI_MakeFillet::*)(const Standard_Integer) const ) &BRepFilletAPI_MakeFillet::LastVertex, "Returns the last vertex of the contour of index IC in the internal data structure of this algorithm. Warning Returns a null shape if IC is outside the bounds of the table of contours.", py::arg("IC"));
	cls_BRepFilletAPI_MakeFillet.def("Abscissa", (Standard_Real (BRepFilletAPI_MakeFillet::*)(const Standard_Integer, const TopoDS_Vertex &) const ) &BRepFilletAPI_MakeFillet::Abscissa, "Returns the curvilinear abscissa of the vertex V on the contour of index IC in the internal data structure of this algorithm. Warning Returns -1. if: - IC is outside the bounds of the table of contours, or - V is not on the contour of index IC.", py::arg("IC"), py::arg("V"));
	cls_BRepFilletAPI_MakeFillet.def("RelativeAbscissa", (Standard_Real (BRepFilletAPI_MakeFillet::*)(const Standard_Integer, const TopoDS_Vertex &) const ) &BRepFilletAPI_MakeFillet::RelativeAbscissa, "Returns the relative curvilinear abscissa (i.e. between 0 and 1) of the vertex V on the contour of index IC in the internal data structure of this algorithm. Warning Returns -1. if: - IC is outside the bounds of the table of contours, or - V is not on the contour of index IC.", py::arg("IC"), py::arg("V"));
	cls_BRepFilletAPI_MakeFillet.def("ClosedAndTangent", (Standard_Boolean (BRepFilletAPI_MakeFillet::*)(const Standard_Integer) const ) &BRepFilletAPI_MakeFillet::ClosedAndTangent, "Returns true if the contour of index IC in the internal data structure of this algorithm is closed and tangential at the point of closure. Warning Returns false if IC is outside the bounds of the table of contours.", py::arg("IC"));
	cls_BRepFilletAPI_MakeFillet.def("Closed", (Standard_Boolean (BRepFilletAPI_MakeFillet::*)(const Standard_Integer) const ) &BRepFilletAPI_MakeFillet::Closed, "Returns true if the contour of index IC in the internal data structure of this algorithm is closed. Warning Returns false if IC is outside the bounds of the table of contours.", py::arg("IC"));
	cls_BRepFilletAPI_MakeFillet.def("Build", (void (BRepFilletAPI_MakeFillet::*)()) &BRepFilletAPI_MakeFillet::Build, "Builds the fillets on all the contours in the internal data structure of this algorithm and constructs the resulting shape. Use the function IsDone to verify that the filleted shape is built. Use the function Shape to retrieve the filleted shape. Warning The construction of fillets implements highly complex construction algorithms. Consequently, there may be instances where the algorithm fails, for example if the data defining the radius of the fillet is not compatible with the geometry of the initial shape. There is no initial analysis of errors and they only become evident at the construction stage. Additionally, in the current software release, the following cases are not handled: - the end point of the contour is the point of intersection of 4 or more edges of the shape, or - the intersection of the fillet with a face which limits the contour is not fully contained in this face.");
	cls_BRepFilletAPI_MakeFillet.def("Reset", (void (BRepFilletAPI_MakeFillet::*)()) &BRepFilletAPI_MakeFillet::Reset, "Reinitializes this algorithm, thus canceling the effects of the Build function. This function allows modifications to be made to the contours and fillet parameters in order to rebuild the shape.");
	cls_BRepFilletAPI_MakeFillet.def("Builder", (opencascade::handle<TopOpeBRepBuild_HBuilder> (BRepFilletAPI_MakeFillet::*)() const ) &BRepFilletAPI_MakeFillet::Builder, "Returns the internal topology building algorithm.");
	cls_BRepFilletAPI_MakeFillet.def("Generated", (const TopTools_ListOfShape & (BRepFilletAPI_MakeFillet::*)(const TopoDS_Shape &)) &BRepFilletAPI_MakeFillet::Generated, "Returns the list of shapes generated from the shape <EorV>.", py::arg("EorV"));
	cls_BRepFilletAPI_MakeFillet.def("Modified", (const TopTools_ListOfShape & (BRepFilletAPI_MakeFillet::*)(const TopoDS_Shape &)) &BRepFilletAPI_MakeFillet::Modified, "Returns the list of shapes modified from the shape <F>.", py::arg("F"));
	cls_BRepFilletAPI_MakeFillet.def("IsDeleted", (Standard_Boolean (BRepFilletAPI_MakeFillet::*)(const TopoDS_Shape &)) &BRepFilletAPI_MakeFillet::IsDeleted, "None", py::arg("F"));
	cls_BRepFilletAPI_MakeFillet.def("NbSurfaces", (Standard_Integer (BRepFilletAPI_MakeFillet::*)() const ) &BRepFilletAPI_MakeFillet::NbSurfaces, "returns the number of surfaces after the shape creation.");
	cls_BRepFilletAPI_MakeFillet.def("NewFaces", (const TopTools_ListOfShape & (BRepFilletAPI_MakeFillet::*)(const Standard_Integer)) &BRepFilletAPI_MakeFillet::NewFaces, "Return the faces created for surface <I>.", py::arg("I"));
	cls_BRepFilletAPI_MakeFillet.def("Simulate", (void (BRepFilletAPI_MakeFillet::*)(const Standard_Integer)) &BRepFilletAPI_MakeFillet::Simulate, "None", py::arg("IC"));
	cls_BRepFilletAPI_MakeFillet.def("NbSurf", (Standard_Integer (BRepFilletAPI_MakeFillet::*)(const Standard_Integer) const ) &BRepFilletAPI_MakeFillet::NbSurf, "None", py::arg("IC"));
	cls_BRepFilletAPI_MakeFillet.def("Sect", (opencascade::handle<ChFiDS_SecHArray1> (BRepFilletAPI_MakeFillet::*)(const Standard_Integer, const Standard_Integer) const ) &BRepFilletAPI_MakeFillet::Sect, "None", py::arg("IC"), py::arg("IS"));
	cls_BRepFilletAPI_MakeFillet.def("NbFaultyContours", (Standard_Integer (BRepFilletAPI_MakeFillet::*)() const ) &BRepFilletAPI_MakeFillet::NbFaultyContours, "Returns the number of contours where the computation of the fillet failed");
	cls_BRepFilletAPI_MakeFillet.def("FaultyContour", (Standard_Integer (BRepFilletAPI_MakeFillet::*)(const Standard_Integer) const ) &BRepFilletAPI_MakeFillet::FaultyContour, "for each I in [1.. NbFaultyContours] returns the index IC of the contour where the computation of the fillet failed. the method NbEdges(IC) gives the number of edges in the contour IC the method Edge(IC,ie) gives the edge number ie of the contour IC", py::arg("I"));
	cls_BRepFilletAPI_MakeFillet.def("NbComputedSurfaces", (Standard_Integer (BRepFilletAPI_MakeFillet::*)(const Standard_Integer) const ) &BRepFilletAPI_MakeFillet::NbComputedSurfaces, "returns the number of surfaces which have been computed on the contour IC", py::arg("IC"));
	cls_BRepFilletAPI_MakeFillet.def("ComputedSurface", (opencascade::handle<Geom_Surface> (BRepFilletAPI_MakeFillet::*)(const Standard_Integer, const Standard_Integer) const ) &BRepFilletAPI_MakeFillet::ComputedSurface, "returns the surface number IS concerning the contour IC", py::arg("IC"), py::arg("IS"));
	cls_BRepFilletAPI_MakeFillet.def("NbFaultyVertices", (Standard_Integer (BRepFilletAPI_MakeFillet::*)() const ) &BRepFilletAPI_MakeFillet::NbFaultyVertices, "returns the number of vertices where the computation failed");
	cls_BRepFilletAPI_MakeFillet.def("FaultyVertex", (TopoDS_Vertex (BRepFilletAPI_MakeFillet::*)(const Standard_Integer) const ) &BRepFilletAPI_MakeFillet::FaultyVertex, "returns the vertex where the computation failed", py::arg("IV"));
	cls_BRepFilletAPI_MakeFillet.def("HasResult", (Standard_Boolean (BRepFilletAPI_MakeFillet::*)() const ) &BRepFilletAPI_MakeFillet::HasResult, "returns true if a part of the result has been computed if the filling in a corner failed a shape with a hole is returned");
	cls_BRepFilletAPI_MakeFillet.def("BadShape", (TopoDS_Shape (BRepFilletAPI_MakeFillet::*)() const ) &BRepFilletAPI_MakeFillet::BadShape, "if (HasResult()) returns the partial result");
	cls_BRepFilletAPI_MakeFillet.def("StripeStatus", (ChFiDS_ErrorStatus (BRepFilletAPI_MakeFillet::*)(const Standard_Integer) const ) &BRepFilletAPI_MakeFillet::StripeStatus, "returns the status concerning the contour IC in case of error ChFiDS_Ok : the computation is Ok ChFiDS_StartsolFailure : the computation can't start, perhaps the the radius is too big ChFiDS_TwistedSurface : the computation failed because of a twisted surface ChFiDS_WalkingFailure : there is a problem in the walking ChFiDS_Error: other error different from above", py::arg("IC"));

	// C:\Miniconda\envs\occt\Library\include\opencascade\BRepFilletAPI_MakeFillet2d.hxx
	py::class_<BRepFilletAPI_MakeFillet2d, std::unique_ptr<BRepFilletAPI_MakeFillet2d, Deleter<BRepFilletAPI_MakeFillet2d>>, BRepBuilderAPI_MakeShape> cls_BRepFilletAPI_MakeFillet2d(mod, "BRepFilletAPI_MakeFillet2d", "Describes functions to build fillets and chamfers on the vertices of a planar face. Fillets and Chamfers on the Vertices of a Planar Face A MakeFillet2d object provides a framework for: - initializing the construction algorithm with a given face, - acquiring the data characterizing the fillets and chamfers, - building the fillets and chamfers, and constructing the resulting shape, and - consulting the result. Warning Only segments of straight lines and arcs of circles are treated. BSplines are not processed.");
	cls_BRepFilletAPI_MakeFillet2d.def(py::init<>());
	cls_BRepFilletAPI_MakeFillet2d.def(py::init<const TopoDS_Face &>(), py::arg("F"));
	cls_BRepFilletAPI_MakeFillet2d.def("Init", (void (BRepFilletAPI_MakeFillet2d::*)(const TopoDS_Face &)) &BRepFilletAPI_MakeFillet2d::Init, "Initializes this algorithm for constructing fillets or chamfers with the face F. Warning The status of the initialization, as given by the Status function, can be one of the following: - ChFi2d_Ready if the initialization is correct, - ChFi2d_NotPlanar if F is not planar, - ChFi2d_NoFace if F is a null face.", py::arg("F"));
	cls_BRepFilletAPI_MakeFillet2d.def("Init", (void (BRepFilletAPI_MakeFillet2d::*)(const TopoDS_Face &, const TopoDS_Face &)) &BRepFilletAPI_MakeFillet2d::Init, "This initialize method allow to init the builder from a face <RefFace> and another face <ModFace> which derive from <RefFace>. This is usefull to modify a fillet or a chamfer already created on <ModFace> .", py::arg("RefFace"), py::arg("ModFace"));
	cls_BRepFilletAPI_MakeFillet2d.def("AddFillet", (TopoDS_Edge (BRepFilletAPI_MakeFillet2d::*)(const TopoDS_Vertex &, const Standard_Real)) &BRepFilletAPI_MakeFillet2d::AddFillet, "Adds a fillet of radius Radius between the two edges adjacent to the vertex V on the face modified by this algorithm. The two edges do not need to be rectilinear. This function returns the fillet and builds the resulting face. Warning The status of the construction, as given by the Status function, can be one of the following: - ChFi2d_IsDone if the fillet is built, - ChFi2d_ConnexionError if V does not belong to the initial face, - ChFi2d_ComputationError if Radius is too large to build a fillet between the two adjacent edges, - ChFi2d_NotAuthorized - if one of the two edges connected to V is a fillet or chamfer, or - if a curve other than a straight line or an arc of a circle is used as E, E1 or E2. Do not use the returned fillet if the status of the construction is not ChFi2d_IsDone. Exceptions Standard_NegativeValue if Radius is less than or equal to zero.", py::arg("V"), py::arg("Radius"));
	cls_BRepFilletAPI_MakeFillet2d.def("ModifyFillet", (TopoDS_Edge (BRepFilletAPI_MakeFillet2d::*)(const TopoDS_Edge &, const Standard_Real)) &BRepFilletAPI_MakeFillet2d::ModifyFillet, "Assigns the radius Radius to the fillet Fillet already built on the face modified by this algorithm. This function returns the new fillet and modifies the existing face. Warning The status of the construction, as given by the Status function, can be one of the following: - ChFi2d_IsDone if the new fillet is built, - ChFi2d_ConnexionError if Fillet does not belong to the existing face, - ChFi2d_ComputationError if Radius is too large to build a fillet between the two adjacent edges. Do not use the returned fillet if the status of the construction is not ChFi2d_IsDone. Exceptions Standard_NegativeValue if Radius is less than or equal to zero.", py::arg("Fillet"), py::arg("Radius"));
	cls_BRepFilletAPI_MakeFillet2d.def("RemoveFillet", (TopoDS_Vertex (BRepFilletAPI_MakeFillet2d::*)(const TopoDS_Edge &)) &BRepFilletAPI_MakeFillet2d::RemoveFillet, "Removes the fillet Fillet already built on the face modified by this algorithm. This function returns the vertex connecting the two adjacent edges of Fillet and modifies the existing face. Warning - The returned vertex is only valid if the Status function returns ChFi2d_IsDone. - A null vertex is returned if the edge Fillet does not belong to the initial face.", py::arg("Fillet"));
	cls_BRepFilletAPI_MakeFillet2d.def("AddChamfer", (TopoDS_Edge (BRepFilletAPI_MakeFillet2d::*)(const TopoDS_Edge &, const TopoDS_Edge &, const Standard_Real, const Standard_Real)) &BRepFilletAPI_MakeFillet2d::AddChamfer, "Adds a chamfer on the face modified by this algorithm between the two adjacent edges E1 and E2, where the extremities of the chamfer are on E1 and E2 at distances D1 and D2 respectively In cases where the edges are not rectilinear, distances are measured using the curvilinear abscissa of the edges and the angle is measured with respect to the tangent at the corresponding point. The angle Ang is given in radians. This function returns the chamfer and builds the resulting face.", py::arg("E1"), py::arg("E2"), py::arg("D1"), py::arg("D2"));
	cls_BRepFilletAPI_MakeFillet2d.def("AddChamfer", (TopoDS_Edge (BRepFilletAPI_MakeFillet2d::*)(const TopoDS_Edge &, const TopoDS_Vertex &, const Standard_Real, const Standard_Real)) &BRepFilletAPI_MakeFillet2d::AddChamfer, "Adds a chamfer on the face modified by this algorithm between the two edges connected by the vertex V, where E is one of the two edges. The chamfer makes an angle Ang with E and one of its extremities is on E at distance D from V. In cases where the edges are not rectilinear, distances are measured using the curvilinear abscissa of the edges and the angle is measured with respect to the tangent at the corresponding point. The angle Ang is given in radians. This function returns the chamfer and builds the resulting face. Warning The status of the construction, as given by the Status function, can be one of the following: - ChFi2d_IsDone if the chamfer is built, - ChFi2d_ParametersError if D1, D2, D or Ang is less than or equal to zero, - ChFi2d_ConnexionError if: - the edge E, E1 or E2 does not belong to the initial face, or - the edges E1 and E2 are not adjacent, or - the vertex V is not one of the limit points of the edge E, - ChFi2d_ComputationError if the parameters of the chamfer are too large to build a chamfer between the two adjacent edges, - ChFi2d_NotAuthorized if: - the edge E1, E2 or one of the two edges connected to V is a fillet or chamfer, or - a curve other than a straight line or an arc of a circle is used as E, E1 or E2. Do not use the returned chamfer if the status of the construction is not ChFi2d_IsDone.", py::arg("E"), py::arg("V"), py::arg("D"), py::arg("Ang"));
	cls_BRepFilletAPI_MakeFillet2d.def("ModifyChamfer", (TopoDS_Edge (BRepFilletAPI_MakeFillet2d::*)(const TopoDS_Edge &, const TopoDS_Edge &, const TopoDS_Edge &, const Standard_Real, const Standard_Real)) &BRepFilletAPI_MakeFillet2d::ModifyChamfer, "Modifies the chamfer Chamfer on the face modified by this algorithm, where: E1 and E2 are the two adjacent edges on which Chamfer is already built; the extremities of the new chamfer are on E1 and E2 at distances D1 and D2 respectively.", py::arg("Chamfer"), py::arg("E1"), py::arg("E2"), py::arg("D1"), py::arg("D2"));
	cls_BRepFilletAPI_MakeFillet2d.def("ModifyChamfer", (TopoDS_Edge (BRepFilletAPI_MakeFillet2d::*)(const TopoDS_Edge &, const TopoDS_Edge &, const Standard_Real, const Standard_Real)) &BRepFilletAPI_MakeFillet2d::ModifyChamfer, "Modifies the chamfer Chamfer on the face modified by this algorithm, where: E is one of the two adjacent edges on which Chamfer is already built; the new chamfer makes an angle Ang with E and one of its extremities is on E at distance D from the vertex on which the chamfer is built. In cases where the edges are not rectilinear, the distances are measured using the curvilinear abscissa of the edges and the angle is measured with respect to the tangent at the corresponding point. The angle Ang is given in radians. This function returns the new chamfer and modifies the existing face. Warning The status of the construction, as given by the Status function, can be one of the following: - ChFi2d_IsDone if the chamfer is built, - ChFi2d_ParametersError if D1, D2, D or Ang is less than or equal to zero, - ChFi2d_ConnexionError if: - the edge E, E1, E2 or Chamfer does not belong to the existing face, or - the edges E1 and E2 are not adjacent, - ChFi2d_ComputationError if the parameters of the chamfer are too large to build a chamfer between the two adjacent edges, - ChFi2d_NotAuthorized if E1 or E2 is a fillet or chamfer. Do not use the returned chamfer if the status of the construction is not ChFi2d_IsDone.", py::arg("Chamfer"), py::arg("E"), py::arg("D"), py::arg("Ang"));
	cls_BRepFilletAPI_MakeFillet2d.def("RemoveChamfer", (TopoDS_Vertex (BRepFilletAPI_MakeFillet2d::*)(const TopoDS_Edge &)) &BRepFilletAPI_MakeFillet2d::RemoveChamfer, "Removes the chamfer Chamfer already built on the face modified by this algorithm. This function returns the vertex connecting the two adjacent edges of Chamfer and modifies the existing face. Warning - The returned vertex is only valid if the Status function returns ChFi2d_IsDone. - A null vertex is returned if the edge Chamfer does not belong to the initial face.", py::arg("Chamfer"));
	cls_BRepFilletAPI_MakeFillet2d.def("IsModified", (Standard_Boolean (BRepFilletAPI_MakeFillet2d::*)(const TopoDS_Edge &) const ) &BRepFilletAPI_MakeFillet2d::IsModified, "Returns true if the edge E on the face modified by this algorithm is chamfered or filleted. Warning Returns false if E does not belong to the face modified by this algorithm.", py::arg("E"));
	cls_BRepFilletAPI_MakeFillet2d.def("FilletEdges", (const TopTools_SequenceOfShape & (BRepFilletAPI_MakeFillet2d::*)() const ) &BRepFilletAPI_MakeFillet2d::FilletEdges, "Returns the table of fillets on the face modified by this algorithm.");
	cls_BRepFilletAPI_MakeFillet2d.def("NbFillet", (Standard_Integer (BRepFilletAPI_MakeFillet2d::*)() const ) &BRepFilletAPI_MakeFillet2d::NbFillet, "Returns the number of fillets on the face modified by this algorithm.");
	cls_BRepFilletAPI_MakeFillet2d.def("ChamferEdges", (const TopTools_SequenceOfShape & (BRepFilletAPI_MakeFillet2d::*)() const ) &BRepFilletAPI_MakeFillet2d::ChamferEdges, "Returns the table of chamfers on the face modified by this algorithm.");
	cls_BRepFilletAPI_MakeFillet2d.def("NbChamfer", (Standard_Integer (BRepFilletAPI_MakeFillet2d::*)() const ) &BRepFilletAPI_MakeFillet2d::NbChamfer, "Returns the number of chamfers on the face modified by this algorithm.");
	cls_BRepFilletAPI_MakeFillet2d.def("Modified", (const TopTools_ListOfShape & (BRepFilletAPI_MakeFillet2d::*)(const TopoDS_Shape &)) &BRepFilletAPI_MakeFillet2d::Modified, "Returns the list of shapes modified from the shape <S>.", py::arg("S"));
	cls_BRepFilletAPI_MakeFillet2d.def("NbCurves", (Standard_Integer (BRepFilletAPI_MakeFillet2d::*)() const ) &BRepFilletAPI_MakeFillet2d::NbCurves, "returns the number of new curves after the shape creation.");
	cls_BRepFilletAPI_MakeFillet2d.def("NewEdges", (const TopTools_ListOfShape & (BRepFilletAPI_MakeFillet2d::*)(const Standard_Integer)) &BRepFilletAPI_MakeFillet2d::NewEdges, "Return the Edges created for curve I.", py::arg("I"));
	cls_BRepFilletAPI_MakeFillet2d.def("HasDescendant", (Standard_Boolean (BRepFilletAPI_MakeFillet2d::*)(const TopoDS_Edge &) const ) &BRepFilletAPI_MakeFillet2d::HasDescendant, "None", py::arg("E"));
	cls_BRepFilletAPI_MakeFillet2d.def("DescendantEdge", (const TopoDS_Edge & (BRepFilletAPI_MakeFillet2d::*)(const TopoDS_Edge &) const ) &BRepFilletAPI_MakeFillet2d::DescendantEdge, "Returns the chamfered or filleted edge built from the edge E on the face modified by this algorithm. If E has not been modified, this function returns E. Exceptions Standard_NoSuchObject if the edge E does not belong to the initial face.", py::arg("E"));
	cls_BRepFilletAPI_MakeFillet2d.def("BasisEdge", (const TopoDS_Edge & (BRepFilletAPI_MakeFillet2d::*)(const TopoDS_Edge &) const ) &BRepFilletAPI_MakeFillet2d::BasisEdge, "Returns the basis edge on the face modified by this algorithm from which the chamfered or filleted edge E is built. If E has not been modified, this function returns E. Warning E is returned if it does not belong to the initial face.", py::arg("E"));
	cls_BRepFilletAPI_MakeFillet2d.def("Status", (ChFi2d_ConstructionError (BRepFilletAPI_MakeFillet2d::*)() const ) &BRepFilletAPI_MakeFillet2d::Status, "None");
	cls_BRepFilletAPI_MakeFillet2d.def("Build", (void (BRepFilletAPI_MakeFillet2d::*)()) &BRepFilletAPI_MakeFillet2d::Build, "Update the result and set the Done flag");


}
