#include <pyOCCT_Common.hpp>

#include <Standard_Handle.hxx>
#include <Geom_BSplineCurve.hxx>
#include <Standard_TypeDef.hxx>
#include <TColStd_Array1OfInteger.hxx>
#include <GeomConvert_BSplineCurveKnotSplitting.hxx>
#include <Geom_BSplineSurface.hxx>
#include <GeomConvert_BSplineSurfaceKnotSplitting.hxx>
#include <Geom_BezierCurve.hxx>
#include <TColGeom_Array1OfBezierCurve.hxx>
#include <TColStd_Array1OfReal.hxx>
#include <GeomConvert_BSplineCurveToBezierCurve.hxx>
#include <Convert_ParameterisationType.hxx>
#include <Geom_BoundedCurve.hxx>
#include <GeomConvert_CompCurveToBSplineCurve.hxx>
#include <Geom_BezierSurface.hxx>
#include <TColGeom_Array2OfBezierSurface.hxx>
#include <GeomConvert_BSplineSurfaceToBezierSurface.hxx>
#include <GeomAbs_Shape.hxx>
#include <TColgp_HArray2OfPnt.hxx>
#include <TColStd_HArray1OfReal.hxx>
#include <TColStd_HArray1OfInteger.hxx>
#include <GeomConvert_CompBezierSurfacesToBSplineSurface.hxx>
#include <Geom_Surface.hxx>
#include <Adaptor3d_HSurface.hxx>
#include <Standard_OStream.hxx>
#include <GeomConvert_ApproxSurface.hxx>
#include <Geom_Curve.hxx>
#include <Adaptor3d_HCurve.hxx>
#include <GeomConvert_ApproxCurve.hxx>
#include <TColGeom_Array1OfBSplineCurve.hxx>
#include <TColGeom_HArray1OfBSplineCurve.hxx>
#include <GeomConvert.hxx>

PYBIND11_MODULE(GeomConvert, mod) {

	// IMPORT
	py::module::import("OCCT.Standard");
	py::module::import("OCCT.Geom");
	py::module::import("OCCT.TColStd");
	py::module::import("OCCT.TColGeom");
	py::module::import("OCCT.Convert");
	py::module::import("OCCT.GeomAbs");
	py::module::import("OCCT.TColgp");
	py::module::import("OCCT.Adaptor3d");

	py::module other_mod;

	// IMPORT GUARDS

	// ENUMS

	// FUNCTIONS

	// CLASSES
	// C:\Miniconda\envs\occt\Library\include\opencascade\GeomConvert_BSplineCurveKnotSplitting.hxx
	py::class_<GeomConvert_BSplineCurveKnotSplitting, std::unique_ptr<GeomConvert_BSplineCurveKnotSplitting, Deleter<GeomConvert_BSplineCurveKnotSplitting>>> cls_GeomConvert_BSplineCurveKnotSplitting(mod, "GeomConvert_BSplineCurveKnotSplitting", "An algorithm to determine points at which a BSpline curve should be split in order to obtain arcs of the same continuity. If you require curves with a minimum continuity for your computation, it is useful to know the points between which an arc has a continuity of a given order. The continuity order is given at the construction time. For a BSpline curve, the discontinuities are localized at the knot values. Between two knot values the BSpline is infinitely and continuously differentiable. At a given knot, the continuity is equal to: Degree - Mult, where Degree is the degree of the BSpline curve and Mult is the multiplicity of the knot. It is possible to compute the arcs which correspond to this splitting using the global function SplitBSplineCurve provided by the package GeomConvert. A BSplineCurveKnotSplitting object provides a framework for: - defining the curve to be analyzed and the required degree of continuity, - implementing the computation algorithm, and - consulting the results.");
	cls_GeomConvert_BSplineCurveKnotSplitting.def(py::init<const opencascade::handle<Geom_BSplineCurve> &, const Standard_Integer>(), py::arg("BasisCurve"), py::arg("ContinuityRange"));
	cls_GeomConvert_BSplineCurveKnotSplitting.def("NbSplits", (Standard_Integer (GeomConvert_BSplineCurveKnotSplitting::*)() const ) &GeomConvert_BSplineCurveKnotSplitting::NbSplits, "Returns the number of points at which the analyzed BSpline curve should be split, in order to obtain arcs with the continuity required by this framework. All these points correspond to knot values. Note that the first and last points of the curve, which bound the first and last arcs, are counted among these splitting points.");
	cls_GeomConvert_BSplineCurveKnotSplitting.def("Splitting", (void (GeomConvert_BSplineCurveKnotSplitting::*)(TColStd_Array1OfInteger &) const ) &GeomConvert_BSplineCurveKnotSplitting::Splitting, "Loads the SplitValues table with the split knots values computed in this framework. Each value in the table is an index in the knots table of the BSpline curve analyzed by this algorithm. The values in SplitValues are given in ascending order and comprise the indices of the knots which give the first and last points of the curve. Use two consecutive values from the table as arguments of the global function SplitBSplineCurve (provided by the package GeomConvert) to split the curve. Exceptions Standard_DimensionError if the array SplitValues was not created with the following bounds: - 1, and - the number of split points computed in this framework (as given by the function NbSplits).", py::arg("SplitValues"));
	cls_GeomConvert_BSplineCurveKnotSplitting.def("SplitValue", (Standard_Integer (GeomConvert_BSplineCurveKnotSplitting::*)(const Standard_Integer) const ) &GeomConvert_BSplineCurveKnotSplitting::SplitValue, "Returns the split knot of index Index to the split knots table computed in this framework. The returned value is an index in the knots table of the BSpline curve analyzed by this algorithm. Notes: - If Index is equal to 1, the corresponding knot gives the first point of the curve. - If Index is equal to the number of split knots computed in this framework, the corresponding point is the last point of the curve. Exceptions Standard_RangeError if Index is less than 1 or greater than the number of split knots computed in this framework.", py::arg("Index"));

	// C:\Miniconda\envs\occt\Library\include\opencascade\GeomConvert_BSplineSurfaceKnotSplitting.hxx
	py::class_<GeomConvert_BSplineSurfaceKnotSplitting, std::unique_ptr<GeomConvert_BSplineSurfaceKnotSplitting, Deleter<GeomConvert_BSplineSurfaceKnotSplitting>>> cls_GeomConvert_BSplineSurfaceKnotSplitting(mod, "GeomConvert_BSplineSurfaceKnotSplitting", "An algorithm to determine isoparametric curves along which a BSpline surface should be split in order to obtain patches of the same continuity. The continuity order is given at the construction time. It is possible to compute the surface patches corresponding to the splitting with the method of package SplitBSplineSurface. For a B-spline surface the discontinuities are localised at the knot values. Between two knots values the B-spline is infinitely continuously differentiable. For each parametric direction at a knot of range index the continuity in this direction is equal to : Degree - Mult (Index) where Degree is the degree of the basis B-spline functions and Mult the multiplicity of the knot of range Index in the given direction. If for your computation you need to have B-spline surface with a minima of continuity it can be interesting to know between which knot values, a B-spline patch, has a continuity of given order. This algorithm computes the indexes of the knots where you should split the surface, to obtain patches with a constant continuity given at the construction time. If you just want to compute the local derivatives on the surface you don't need to create the BSpline patches, you can use the functions LocalD1, LocalD2, LocalD3, LocalDN of the class BSplineSurface from package Geom.");
	cls_GeomConvert_BSplineSurfaceKnotSplitting.def(py::init<const opencascade::handle<Geom_BSplineSurface> &, const Standard_Integer, const Standard_Integer>(), py::arg("BasisSurface"), py::arg("UContinuityRange"), py::arg("VContinuityRange"));
	cls_GeomConvert_BSplineSurfaceKnotSplitting.def("NbUSplits", (Standard_Integer (GeomConvert_BSplineSurfaceKnotSplitting::*)() const ) &GeomConvert_BSplineSurfaceKnotSplitting::NbUSplits, "Returns the number of u-isoparametric curves along which the analysed BSpline surface should be split in order to obtain patches with the continuity required by this framework. The parameters which define these curves are knot values in the corresponding parametric direction. Note that the four curves which bound the surface are counted among these splitting curves.");
	cls_GeomConvert_BSplineSurfaceKnotSplitting.def("NbVSplits", (Standard_Integer (GeomConvert_BSplineSurfaceKnotSplitting::*)() const ) &GeomConvert_BSplineSurfaceKnotSplitting::NbVSplits, "Returns the number of v-isoparametric curves along which the analysed BSpline surface should be split in order to obtain patches with the continuity required by this framework. The parameters which define these curves are knot values in the corresponding parametric direction. Note that the four curves which bound the surface are counted among these splitting curves.");
	cls_GeomConvert_BSplineSurfaceKnotSplitting.def("Splitting", (void (GeomConvert_BSplineSurfaceKnotSplitting::*)(TColStd_Array1OfInteger &, TColStd_Array1OfInteger &) const ) &GeomConvert_BSplineSurfaceKnotSplitting::Splitting, "Loads the USplit and VSplit tables with the split knots values computed in this framework. Each value in these tables is an index in the knots table corresponding to the u or v parametric direction of the BSpline surface analysed by this algorithm. The USplit and VSplit values are given in ascending order and comprise the indices of the knots which give the first and last isoparametric curves of the surface in the corresponding parametric direction. Use two consecutive values from the USplit table and two consecutive values from the VSplit table as arguments of the global function SplitBSplineSurface (provided by the package GeomConvert) to split the surface. Exceptions Standard_DimensionError if: - the array USplit was not created with the following bounds: - 1 , and - the number of split knots in the u parametric direction computed in this framework (as given by the function NbUSplits); or - the array VSplit was not created with the following bounds: - 1 , and - the number of split knots in the v parametric direction computed in this framework (as given by the function NbVSplits).", py::arg("USplit"), py::arg("VSplit"));
	cls_GeomConvert_BSplineSurfaceKnotSplitting.def("USplitValue", (Standard_Integer (GeomConvert_BSplineSurfaceKnotSplitting::*)(const Standard_Integer) const ) &GeomConvert_BSplineSurfaceKnotSplitting::USplitValue, "Returns the split knot of index UIndex to the split knots table for the u parametric direction computed in this framework. The returned value is an index in the knots table relative to the u parametric direction of the BSpline surface analysed by this algorithm. Note: If UIndex is equal to 1, or to the number of split knots for the u parametric direction computed in this framework, the corresponding knot gives the parameter of one of the bounding curves of the surface. Exceptions Standard_RangeError if UIndex is less than 1 or greater than the number of split knots for the u parametric direction computed in this framework.", py::arg("UIndex"));
	cls_GeomConvert_BSplineSurfaceKnotSplitting.def("VSplitValue", (Standard_Integer (GeomConvert_BSplineSurfaceKnotSplitting::*)(const Standard_Integer) const ) &GeomConvert_BSplineSurfaceKnotSplitting::VSplitValue, "Returns the split knot of index VIndex to the split knots table for the v parametric direction computed in this framework. The returned value is an index in the knots table relative to the v parametric direction of the BSpline surface analysed by this algorithm. Note: If UIndex is equal to 1, or to the number of split knots for the v parametric direction computed in this framework, the corresponding knot gives the parameter of one of the bounding curves of the surface. Exceptions Standard_RangeError if VIndex is less than 1 or greater than the number of split knots for the v parametric direction computed in this framework.", py::arg("VIndex"));

	// C:\Miniconda\envs\occt\Library\include\opencascade\GeomConvert_BSplineCurveToBezierCurve.hxx
	py::class_<GeomConvert_BSplineCurveToBezierCurve, std::unique_ptr<GeomConvert_BSplineCurveToBezierCurve, Deleter<GeomConvert_BSplineCurveToBezierCurve>>> cls_GeomConvert_BSplineCurveToBezierCurve(mod, "GeomConvert_BSplineCurveToBezierCurve", "An algorithm to convert a BSpline curve into a series of adjacent Bezier curves. A BSplineCurveToBezierCurve object provides a framework for: - defining the BSpline curve to be converted - implementing the construction algorithm, and - consulting the results. References : Generating the Bezier points of B-spline curves and surfaces (Wolfgang Bohm) CAD volume 13 number 6 november 1981");
	cls_GeomConvert_BSplineCurveToBezierCurve.def(py::init<const opencascade::handle<Geom_BSplineCurve> &>(), py::arg("BasisCurve"));
	cls_GeomConvert_BSplineCurveToBezierCurve.def(py::init<const opencascade::handle<Geom_BSplineCurve> &, const Standard_Real, const Standard_Real, const Standard_Real>(), py::arg("BasisCurve"), py::arg("U1"), py::arg("U2"), py::arg("ParametricTolerance"));
	cls_GeomConvert_BSplineCurveToBezierCurve.def("Arc", (opencascade::handle<Geom_BezierCurve> (GeomConvert_BSplineCurveToBezierCurve::*)(const Standard_Integer)) &GeomConvert_BSplineCurveToBezierCurve::Arc, "Constructs and returns the Bezier curve of index Index to the table of adjacent Bezier arcs computed by this algorithm. This Bezier curve has the same orientation as the BSpline curve analyzed in this framework. Exceptions Standard_OutOfRange if Index is less than 1 or greater than the number of adjacent Bezier arcs computed by this algorithm.", py::arg("Index"));
	cls_GeomConvert_BSplineCurveToBezierCurve.def("Arcs", (void (GeomConvert_BSplineCurveToBezierCurve::*)(TColGeom_Array1OfBezierCurve &)) &GeomConvert_BSplineCurveToBezierCurve::Arcs, "Constructs all the Bezier curves whose data is computed by this algorithm and loads these curves into the Curves table. The Bezier curves have the same orientation as the BSpline curve analyzed in this framework. Exceptions Standard_DimensionError if the Curves array was not created with the following bounds: - 1 , and - the number of adjacent Bezier arcs computed by this algorithm (as given by the function NbArcs).", py::arg("Curves"));
	cls_GeomConvert_BSplineCurveToBezierCurve.def("Knots", (void (GeomConvert_BSplineCurveToBezierCurve::*)(TColStd_Array1OfReal &) const ) &GeomConvert_BSplineCurveToBezierCurve::Knots, "This methode returns the bspline's knots associated to the converted arcs Raised if the length of Curves is not equal to NbArcs + 1.", py::arg("TKnots"));
	cls_GeomConvert_BSplineCurveToBezierCurve.def("NbArcs", (Standard_Integer (GeomConvert_BSplineCurveToBezierCurve::*)() const ) &GeomConvert_BSplineCurveToBezierCurve::NbArcs, "Returns the number of BezierCurve arcs. If at the creation time you have decomposed the basis curve between the parametric values UFirst, ULast the number of BezierCurve arcs depends on the number of knots included inside the interval [UFirst, ULast]. If you have decomposed the whole basis B-spline curve the number of BezierCurve arcs NbArcs is equal to the number of knots less one.");

	// C:\Miniconda\envs\occt\Library\include\opencascade\GeomConvert_CompCurveToBSplineCurve.hxx
	py::class_<GeomConvert_CompCurveToBSplineCurve, std::unique_ptr<GeomConvert_CompCurveToBSplineCurve, Deleter<GeomConvert_CompCurveToBSplineCurve>>> cls_GeomConvert_CompCurveToBSplineCurve(mod, "GeomConvert_CompCurveToBSplineCurve", "Algorithm converts and concat several curve in an BSplineCurve");
	cls_GeomConvert_CompCurveToBSplineCurve.def(py::init<>());
	cls_GeomConvert_CompCurveToBSplineCurve.def(py::init<const Convert_ParameterisationType>(), py::arg("Parameterisation"));
	cls_GeomConvert_CompCurveToBSplineCurve.def(py::init<const opencascade::handle<Geom_BoundedCurve> &>(), py::arg("BasisCurve"));
	cls_GeomConvert_CompCurveToBSplineCurve.def(py::init<const opencascade::handle<Geom_BoundedCurve> &, const Convert_ParameterisationType>(), py::arg("BasisCurve"), py::arg("Parameterisation"));
	cls_GeomConvert_CompCurveToBSplineCurve.def("Add", [](GeomConvert_CompCurveToBSplineCurve &self, const opencascade::handle<Geom_BoundedCurve> & a0, const Standard_Real a1) -> Standard_Boolean { return self.Add(a0, a1); }, py::arg("NewCurve"), py::arg("Tolerance"));
	cls_GeomConvert_CompCurveToBSplineCurve.def("Add", [](GeomConvert_CompCurveToBSplineCurve &self, const opencascade::handle<Geom_BoundedCurve> & a0, const Standard_Real a1, const Standard_Boolean a2) -> Standard_Boolean { return self.Add(a0, a1, a2); }, py::arg("NewCurve"), py::arg("Tolerance"), py::arg("After"));
	cls_GeomConvert_CompCurveToBSplineCurve.def("Add", [](GeomConvert_CompCurveToBSplineCurve &self, const opencascade::handle<Geom_BoundedCurve> & a0, const Standard_Real a1, const Standard_Boolean a2, const Standard_Boolean a3) -> Standard_Boolean { return self.Add(a0, a1, a2, a3); }, py::arg("NewCurve"), py::arg("Tolerance"), py::arg("After"), py::arg("WithRatio"));
	cls_GeomConvert_CompCurveToBSplineCurve.def("Add", (Standard_Boolean (GeomConvert_CompCurveToBSplineCurve::*)(const opencascade::handle<Geom_BoundedCurve> &, const Standard_Real, const Standard_Boolean, const Standard_Boolean, const Standard_Integer)) &GeomConvert_CompCurveToBSplineCurve::Add, "Append a curve in the BSpline Return False if the curve is not G0 with the BSplineCurve. Tolerance is used to check continuity and decrease Multiplicity at the common Knot until MinM if MinM = 0, the common Knot can be removed", py::arg("NewCurve"), py::arg("Tolerance"), py::arg("After"), py::arg("WithRatio"), py::arg("MinM"));
	cls_GeomConvert_CompCurveToBSplineCurve.def("BSplineCurve", (opencascade::handle<Geom_BSplineCurve> (GeomConvert_CompCurveToBSplineCurve::*)() const ) &GeomConvert_CompCurveToBSplineCurve::BSplineCurve, "None");
	cls_GeomConvert_CompCurveToBSplineCurve.def("Clear", (void (GeomConvert_CompCurveToBSplineCurve::*)()) &GeomConvert_CompCurveToBSplineCurve::Clear, "Clear a result curve");

	// C:\Miniconda\envs\occt\Library\include\opencascade\GeomConvert_BSplineSurfaceToBezierSurface.hxx
	py::class_<GeomConvert_BSplineSurfaceToBezierSurface, std::unique_ptr<GeomConvert_BSplineSurfaceToBezierSurface, Deleter<GeomConvert_BSplineSurfaceToBezierSurface>>> cls_GeomConvert_BSplineSurfaceToBezierSurface(mod, "GeomConvert_BSplineSurfaceToBezierSurface", "This algorithm converts a B-spline surface into several Bezier surfaces. It uses an algorithm of knot insertion. A BSplineSurfaceToBezierSurface object provides a framework for: - defining the BSpline surface to be converted, - implementing the construction algorithm, and - consulting the results. References : Generating the Bezier points of B-spline curves and surfaces (Wolfgang Bohm) CAD volume 13 number 6 november 1981");
	cls_GeomConvert_BSplineSurfaceToBezierSurface.def(py::init<const opencascade::handle<Geom_BSplineSurface> &>(), py::arg("BasisSurface"));
	cls_GeomConvert_BSplineSurfaceToBezierSurface.def(py::init<const opencascade::handle<Geom_BSplineSurface> &, const Standard_Real, const Standard_Real, const Standard_Real, const Standard_Real, const Standard_Real>(), py::arg("BasisSurface"), py::arg("U1"), py::arg("U2"), py::arg("V1"), py::arg("V2"), py::arg("ParametricTolerance"));
	cls_GeomConvert_BSplineSurfaceToBezierSurface.def("Patch", (opencascade::handle<Geom_BezierSurface> (GeomConvert_BSplineSurfaceToBezierSurface::*)(const Standard_Integer, const Standard_Integer)) &GeomConvert_BSplineSurfaceToBezierSurface::Patch, "Constructs and returns the Bezier surface of indices (UIndex, VIndex) to the patch grid computed on the BSpline surface analyzed by this algorithm. This Bezier surface has the same orientation as the BSpline surface analyzed in this framework. UIndex is an index common to a row in the patch grid. A row in the grid corresponds to a series of adjacent patches, all limited by the same two u-isoparametric curves of the surface. VIndex is an index common to a column in the patch grid. A column in the grid corresponds to a series of adjacent patches, all limited by the same two v-isoparametric curves of the surface. Exceptions Standard_OutOfRange if: - UIndex is less than 1 or greater than the number of rows in the patch grid computed on the BSpline surface analyzed by this algorithm (as returned by the function NbUPatches); or if - VIndex is less than 1 or greater than the number of columns in the patch grid computed on the BSpline surface analyzed by this algorithm (as returned by the function NbVPatches).", py::arg("UIndex"), py::arg("VIndex"));
	cls_GeomConvert_BSplineSurfaceToBezierSurface.def("Patches", (void (GeomConvert_BSplineSurfaceToBezierSurface::*)(TColGeom_Array2OfBezierSurface &)) &GeomConvert_BSplineSurfaceToBezierSurface::Patches, "Constructs all the Bezier surfaces whose data is computed by this algorithm, and loads them into the Surfaces table. These Bezier surfaces have the same orientation as the BSpline surface analyzed in this framework. The Surfaces array is organised in the same way as the patch grid computed on the BSpline surface analyzed by this algorithm. A row in the array corresponds to a series of adjacent patches, all limited by the same two u-isoparametric curves of the surface. A column in the array corresponds to a series of adjacent patches, all limited by the same two v-isoparametric curves of the surface. Exceptions Standard_DimensionError if the Surfaces array was not created with the following bounds: - 1, and the number of adjacent patch series in the u parametric direction of the patch grid computed on the BSpline surface, analyzed by this algorithm (as given by the function NbUPatches) as row bounds, - 1, and the number of adjacent patch series in the v parametric direction of the patch grid computed on the BSpline surface, analyzed by this algorithm (as given by the function NbVPatches) as column bounds.", py::arg("Surfaces"));
	cls_GeomConvert_BSplineSurfaceToBezierSurface.def("UKnots", (void (GeomConvert_BSplineSurfaceToBezierSurface::*)(TColStd_Array1OfReal &) const ) &GeomConvert_BSplineSurfaceToBezierSurface::UKnots, "This methode returns the bspline's u-knots associated to the converted Patches Raised if the length of Curves is not equal to NbUPatches + 1.", py::arg("TKnots"));
	cls_GeomConvert_BSplineSurfaceToBezierSurface.def("VKnots", (void (GeomConvert_BSplineSurfaceToBezierSurface::*)(TColStd_Array1OfReal &) const ) &GeomConvert_BSplineSurfaceToBezierSurface::VKnots, "This methode returns the bspline's v-knots associated to the converted Patches Raised if the length of Curves is not equal to NbVPatches + 1.", py::arg("TKnots"));
	cls_GeomConvert_BSplineSurfaceToBezierSurface.def("NbUPatches", (Standard_Integer (GeomConvert_BSplineSurfaceToBezierSurface::*)() const ) &GeomConvert_BSplineSurfaceToBezierSurface::NbUPatches, "Returns the number of Bezier surfaces in the U direction. If at the creation time you have decomposed the basis Surface between the parametric values UFirst, ULast the number of Bezier surfaces in the U direction depends on the number of knots included inside the interval [UFirst, ULast]. If you have decomposed the whole basis B-spline surface the number of Bezier surfaces NbUPatches is equal to the number of UKnots less one.");
	cls_GeomConvert_BSplineSurfaceToBezierSurface.def("NbVPatches", (Standard_Integer (GeomConvert_BSplineSurfaceToBezierSurface::*)() const ) &GeomConvert_BSplineSurfaceToBezierSurface::NbVPatches, "Returns the number of Bezier surfaces in the V direction. If at the creation time you have decomposed the basis surface between the parametric values VFirst, VLast the number of Bezier surfaces in the V direction depends on the number of knots included inside the interval [VFirst, VLast]. If you have decomposed the whole basis B-spline surface the number of Bezier surfaces NbVPatches is equal to the number of VKnots less one.");

	// C:\Miniconda\envs\occt\Library\include\opencascade\GeomConvert_CompBezierSurfacesToBSplineSurface.hxx
	py::class_<GeomConvert_CompBezierSurfacesToBSplineSurface, std::unique_ptr<GeomConvert_CompBezierSurfacesToBSplineSurface, Deleter<GeomConvert_CompBezierSurfacesToBSplineSurface>>> cls_GeomConvert_CompBezierSurfacesToBSplineSurface(mod, "GeomConvert_CompBezierSurfacesToBSplineSurface", "An algorithm to convert a grid of adjacent non-rational Bezier surfaces (with continuity CM) into a BSpline surface (with continuity CM). A CompBezierSurfacesToBSplineSurface object provides a framework for: - defining the grid of adjacent Bezier surfaces which is to be converted into a BSpline surface, - implementing the computation algorithm, and - consulting the results. Warning Do not attempt to convert rational Bezier surfaces using such an algorithm. Input is array of Bezier patch 1 2 3 4 -> VIndex [1, NbVPatches] -> VDirection ----------------------- 1 | | | | | ----------------------- 2 | | | | | ----------------------- 3 | | | | | ----------------------- UIndex [1, NbUPatches] Udirection");
	cls_GeomConvert_CompBezierSurfacesToBSplineSurface.def(py::init<const TColGeom_Array2OfBezierSurface &>(), py::arg("Beziers"));
	cls_GeomConvert_CompBezierSurfacesToBSplineSurface.def(py::init<const TColGeom_Array2OfBezierSurface &, const Standard_Real>(), py::arg("Beziers"), py::arg("Tolerance"));
	cls_GeomConvert_CompBezierSurfacesToBSplineSurface.def(py::init<const TColGeom_Array2OfBezierSurface &, const Standard_Real, const Standard_Boolean>(), py::arg("Beziers"), py::arg("Tolerance"), py::arg("RemoveKnots"));
	cls_GeomConvert_CompBezierSurfacesToBSplineSurface.def(py::init<const TColGeom_Array2OfBezierSurface &, const TColStd_Array1OfReal &, const TColStd_Array1OfReal &>(), py::arg("Beziers"), py::arg("UKnots"), py::arg("VKnots"));
	cls_GeomConvert_CompBezierSurfacesToBSplineSurface.def(py::init<const TColGeom_Array2OfBezierSurface &, const TColStd_Array1OfReal &, const TColStd_Array1OfReal &, const GeomAbs_Shape>(), py::arg("Beziers"), py::arg("UKnots"), py::arg("VKnots"), py::arg("UContinuity"));
	cls_GeomConvert_CompBezierSurfacesToBSplineSurface.def(py::init<const TColGeom_Array2OfBezierSurface &, const TColStd_Array1OfReal &, const TColStd_Array1OfReal &, const GeomAbs_Shape, const GeomAbs_Shape>(), py::arg("Beziers"), py::arg("UKnots"), py::arg("VKnots"), py::arg("UContinuity"), py::arg("VContinuity"));
	cls_GeomConvert_CompBezierSurfacesToBSplineSurface.def(py::init<const TColGeom_Array2OfBezierSurface &, const TColStd_Array1OfReal &, const TColStd_Array1OfReal &, const GeomAbs_Shape, const GeomAbs_Shape, const Standard_Real>(), py::arg("Beziers"), py::arg("UKnots"), py::arg("VKnots"), py::arg("UContinuity"), py::arg("VContinuity"), py::arg("Tolerance"));
	cls_GeomConvert_CompBezierSurfacesToBSplineSurface.def("NbUKnots", (Standard_Integer (GeomConvert_CompBezierSurfacesToBSplineSurface::*)() const ) &GeomConvert_CompBezierSurfacesToBSplineSurface::NbUKnots, "Returns the number of knots in the U direction of the BSpline surface whose data is computed in this framework.");
	cls_GeomConvert_CompBezierSurfacesToBSplineSurface.def("NbUPoles", (Standard_Integer (GeomConvert_CompBezierSurfacesToBSplineSurface::*)() const ) &GeomConvert_CompBezierSurfacesToBSplineSurface::NbUPoles, "Returns number of poles in the U direction of the BSpline surface whose data is computed in this framework.");
	cls_GeomConvert_CompBezierSurfacesToBSplineSurface.def("NbVKnots", (Standard_Integer (GeomConvert_CompBezierSurfacesToBSplineSurface::*)() const ) &GeomConvert_CompBezierSurfacesToBSplineSurface::NbVKnots, "Returns the number of knots in the V direction of the BSpline surface whose data is computed in this framework.");
	cls_GeomConvert_CompBezierSurfacesToBSplineSurface.def("NbVPoles", (Standard_Integer (GeomConvert_CompBezierSurfacesToBSplineSurface::*)() const ) &GeomConvert_CompBezierSurfacesToBSplineSurface::NbVPoles, "Returns the number of poles in the V direction of the BSpline surface whose data is computed in this framework.");
	cls_GeomConvert_CompBezierSurfacesToBSplineSurface.def("Poles", (const opencascade::handle<TColgp_HArray2OfPnt> & (GeomConvert_CompBezierSurfacesToBSplineSurface::*)() const ) &GeomConvert_CompBezierSurfacesToBSplineSurface::Poles, "Returns the table of poles of the BSpline surface whose data is computed in this framework.");
	cls_GeomConvert_CompBezierSurfacesToBSplineSurface.def("UKnots", (const opencascade::handle<TColStd_HArray1OfReal> & (GeomConvert_CompBezierSurfacesToBSplineSurface::*)() const ) &GeomConvert_CompBezierSurfacesToBSplineSurface::UKnots, "Returns the knots table for the u parametric direction of the BSpline surface whose data is computed in this framework.");
	cls_GeomConvert_CompBezierSurfacesToBSplineSurface.def("UDegree", (Standard_Integer (GeomConvert_CompBezierSurfacesToBSplineSurface::*)() const ) &GeomConvert_CompBezierSurfacesToBSplineSurface::UDegree, "Returns the degree for the u parametric direction of the BSpline surface whose data is computed in this framework.");
	cls_GeomConvert_CompBezierSurfacesToBSplineSurface.def("VKnots", (const opencascade::handle<TColStd_HArray1OfReal> & (GeomConvert_CompBezierSurfacesToBSplineSurface::*)() const ) &GeomConvert_CompBezierSurfacesToBSplineSurface::VKnots, "Returns the knots table for the v parametric direction of the BSpline surface whose data is computed in this framework.");
	cls_GeomConvert_CompBezierSurfacesToBSplineSurface.def("VDegree", (Standard_Integer (GeomConvert_CompBezierSurfacesToBSplineSurface::*)() const ) &GeomConvert_CompBezierSurfacesToBSplineSurface::VDegree, "Returns the degree for the v parametric direction of the BSpline surface whose data is computed in this framework.");
	cls_GeomConvert_CompBezierSurfacesToBSplineSurface.def("UMultiplicities", (const opencascade::handle<TColStd_HArray1OfInteger> & (GeomConvert_CompBezierSurfacesToBSplineSurface::*)() const ) &GeomConvert_CompBezierSurfacesToBSplineSurface::UMultiplicities, "Returns the multiplicities table for the u parametric direction of the knots of the BSpline surface whose data is computed in this framework.");
	cls_GeomConvert_CompBezierSurfacesToBSplineSurface.def("VMultiplicities", (const opencascade::handle<TColStd_HArray1OfInteger> & (GeomConvert_CompBezierSurfacesToBSplineSurface::*)() const ) &GeomConvert_CompBezierSurfacesToBSplineSurface::VMultiplicities, "-- Returns the multiplicities table for the v parametric direction of the knots of the BSpline surface whose data is computed in this framework.");
	cls_GeomConvert_CompBezierSurfacesToBSplineSurface.def("IsDone", (Standard_Boolean (GeomConvert_CompBezierSurfacesToBSplineSurface::*)() const ) &GeomConvert_CompBezierSurfacesToBSplineSurface::IsDone, "Returns true if the conversion was successful. Unless an exception was raised at the time of construction, the conversion of the Bezier surface grid assigned to this algorithm is always carried out. IsDone returns false if the constraints defined at the time of construction cannot be respected. This occurs when there is an incompatibility between a required degree of continuity on the BSpline surface, and the maximum tolerance accepted for local deformations of the surface. In such a case the computed data does not satisfy all the initial constraints.");

	// C:\Miniconda\envs\occt\Library\include\opencascade\GeomConvert_ApproxSurface.hxx
	py::class_<GeomConvert_ApproxSurface, std::unique_ptr<GeomConvert_ApproxSurface, Deleter<GeomConvert_ApproxSurface>>> cls_GeomConvert_ApproxSurface(mod, "GeomConvert_ApproxSurface", "A framework to convert a surface to a BSpline surface. This is done by approximation to a BSpline surface within a given tolerance.");
	cls_GeomConvert_ApproxSurface.def(py::init<const opencascade::handle<Geom_Surface> &, const Standard_Real, const GeomAbs_Shape, const GeomAbs_Shape, const Standard_Integer, const Standard_Integer, const Standard_Integer, const Standard_Integer>(), py::arg("Surf"), py::arg("Tol3d"), py::arg("UContinuity"), py::arg("VContinuity"), py::arg("MaxDegU"), py::arg("MaxDegV"), py::arg("MaxSegments"), py::arg("PrecisCode"));
	cls_GeomConvert_ApproxSurface.def(py::init<const opencascade::handle<Adaptor3d_HSurface> &, const Standard_Real, const GeomAbs_Shape, const GeomAbs_Shape, const Standard_Integer, const Standard_Integer, const Standard_Integer, const Standard_Integer>(), py::arg("Surf"), py::arg("Tol3d"), py::arg("UContinuity"), py::arg("VContinuity"), py::arg("MaxDegU"), py::arg("MaxDegV"), py::arg("MaxSegments"), py::arg("PrecisCode"));
	cls_GeomConvert_ApproxSurface.def("Surface", (opencascade::handle<Geom_BSplineSurface> (GeomConvert_ApproxSurface::*)() const ) &GeomConvert_ApproxSurface::Surface, "Returns the BSpline surface resulting from the approximation algorithm.");
	cls_GeomConvert_ApproxSurface.def("IsDone", (Standard_Boolean (GeomConvert_ApproxSurface::*)() const ) &GeomConvert_ApproxSurface::IsDone, "Returns Standard_True if the approximation has be done");
	cls_GeomConvert_ApproxSurface.def("HasResult", (Standard_Boolean (GeomConvert_ApproxSurface::*)() const ) &GeomConvert_ApproxSurface::HasResult, "Returns true if the approximation did come out with a result that is not NECESSARILY within the required tolerance or a result that is not recognized with the wished continuities.");
	cls_GeomConvert_ApproxSurface.def("MaxError", (Standard_Real (GeomConvert_ApproxSurface::*)() const ) &GeomConvert_ApproxSurface::MaxError, "Returns the greatest distance between a point on the source conic surface and the BSpline surface resulting from the approximation (>0 when an approximation has been done, 0 if no approximation )");
	// FIXME cls_GeomConvert_ApproxSurface.def("Dump", (void (GeomConvert_ApproxSurface::*)(Standard_OStream &) const ) &GeomConvert_ApproxSurface::Dump, "Prints on the stream o informations on the current state of the object.", py::arg("o"));

	// C:\Miniconda\envs\occt\Library\include\opencascade\GeomConvert_ApproxCurve.hxx
	py::class_<GeomConvert_ApproxCurve, std::unique_ptr<GeomConvert_ApproxCurve, Deleter<GeomConvert_ApproxCurve>>> cls_GeomConvert_ApproxCurve(mod, "GeomConvert_ApproxCurve", "A framework to convert a 3D curve to a 3D BSpline. This is done by approximation to a BSpline curve within a given tolerance.");
	cls_GeomConvert_ApproxCurve.def(py::init<const opencascade::handle<Geom_Curve> &, const Standard_Real, const GeomAbs_Shape, const Standard_Integer, const Standard_Integer>(), py::arg("Curve"), py::arg("Tol3d"), py::arg("Order"), py::arg("MaxSegments"), py::arg("MaxDegree"));
	cls_GeomConvert_ApproxCurve.def(py::init<const opencascade::handle<Adaptor3d_HCurve> &, const Standard_Real, const GeomAbs_Shape, const Standard_Integer, const Standard_Integer>(), py::arg("Curve"), py::arg("Tol3d"), py::arg("Order"), py::arg("MaxSegments"), py::arg("MaxDegree"));
	cls_GeomConvert_ApproxCurve.def("Curve", (opencascade::handle<Geom_BSplineCurve> (GeomConvert_ApproxCurve::*)() const ) &GeomConvert_ApproxCurve::Curve, "Returns the BSpline curve resulting from the approximation algorithm.");
	cls_GeomConvert_ApproxCurve.def("IsDone", (Standard_Boolean (GeomConvert_ApproxCurve::*)() const ) &GeomConvert_ApproxCurve::IsDone, "returns Standard_True if the approximation has been done within requiered tolerance");
	cls_GeomConvert_ApproxCurve.def("HasResult", (Standard_Boolean (GeomConvert_ApproxCurve::*)() const ) &GeomConvert_ApproxCurve::HasResult, "Returns Standard_True if the approximation did come out with a result that is not NECESSARELY within the required tolerance");
	cls_GeomConvert_ApproxCurve.def("MaxError", (Standard_Real (GeomConvert_ApproxCurve::*)() const ) &GeomConvert_ApproxCurve::MaxError, "Returns the greatest distance between a point on the source conic and the BSpline curve resulting from the approximation. (>0 when an approximation has been done, 0 if no approximation)");
	// FIXME cls_GeomConvert_ApproxCurve.def("Dump", (void (GeomConvert_ApproxCurve::*)(Standard_OStream &) const ) &GeomConvert_ApproxCurve::Dump, "Print on the stream o information about the object", py::arg("o"));

	// C:\Miniconda\envs\occt\Library\include\opencascade\GeomConvert.hxx
	py::class_<GeomConvert, std::unique_ptr<GeomConvert, Deleter<GeomConvert>>> cls_GeomConvert(mod, "GeomConvert", "The GeomConvert package provides some global functions as follows - converting classical Geom curves into BSpline curves, - segmenting BSpline curves, particularly at knots values: this function may be used in conjunction with the GeomConvert_BSplineCurveKnotSplitting class to segment a BSpline curve into arcs which comply with required continuity levels, - converting classical Geom surfaces into BSpline surfaces, and - segmenting BSpline surfaces, particularly at knots values: this function may be used in conjunction with the GeomConvert_BSplineSurfaceKnotSplitting class to segment a BSpline surface into patches which comply with required continuity levels. All geometric entities used in this package are bounded.");
	cls_GeomConvert.def(py::init<>());
	cls_GeomConvert.def_static("SplitBSplineCurve_", [](const opencascade::handle<Geom_BSplineCurve> & a0, const Standard_Integer a1, const Standard_Integer a2) -> opencascade::handle<Geom_BSplineCurve> { return GeomConvert::SplitBSplineCurve(a0, a1, a2); }, py::arg("C"), py::arg("FromK1"), py::arg("ToK2"));
	cls_GeomConvert.def_static("SplitBSplineCurve_", (opencascade::handle<Geom_BSplineCurve> (*)(const opencascade::handle<Geom_BSplineCurve> &, const Standard_Integer, const Standard_Integer, const Standard_Boolean)) &GeomConvert::SplitBSplineCurve, "Convert a curve from Geom by an approximation method", py::arg("C"), py::arg("FromK1"), py::arg("ToK2"), py::arg("SameOrientation"));
	cls_GeomConvert.def_static("SplitBSplineCurve_", [](const opencascade::handle<Geom_BSplineCurve> & a0, const Standard_Real a1, const Standard_Real a2, const Standard_Real a3) -> opencascade::handle<Geom_BSplineCurve> { return GeomConvert::SplitBSplineCurve(a0, a1, a2, a3); }, py::arg("C"), py::arg("FromU1"), py::arg("ToU2"), py::arg("ParametricTolerance"));
	cls_GeomConvert.def_static("SplitBSplineCurve_", (opencascade::handle<Geom_BSplineCurve> (*)(const opencascade::handle<Geom_BSplineCurve> &, const Standard_Real, const Standard_Real, const Standard_Real, const Standard_Boolean)) &GeomConvert::SplitBSplineCurve, "This function computes the segment of B-spline curve between the parametric values FromU1, ToU2. If C is periodic the arc has the same orientation as C if SameOrientation = True. If C is not periodic SameOrientation is not used for the computation and C is oriented fromU1 toU2. If U1 and U2 and two parametric values we consider that U1 = U2 if Abs (U1 - U2) <= ParametricTolerance and ParametricTolerance must be greater or equal to Resolution from package gp.", py::arg("C"), py::arg("FromU1"), py::arg("ToU2"), py::arg("ParametricTolerance"), py::arg("SameOrientation"));
	cls_GeomConvert.def_static("SplitBSplineSurface_", [](const opencascade::handle<Geom_BSplineSurface> & a0, const Standard_Integer a1, const Standard_Integer a2, const Standard_Integer a3, const Standard_Integer a4) -> opencascade::handle<Geom_BSplineSurface> { return GeomConvert::SplitBSplineSurface(a0, a1, a2, a3, a4); }, py::arg("S"), py::arg("FromUK1"), py::arg("ToUK2"), py::arg("FromVK1"), py::arg("ToVK2"));
	cls_GeomConvert.def_static("SplitBSplineSurface_", [](const opencascade::handle<Geom_BSplineSurface> & a0, const Standard_Integer a1, const Standard_Integer a2, const Standard_Integer a3, const Standard_Integer a4, const Standard_Boolean a5) -> opencascade::handle<Geom_BSplineSurface> { return GeomConvert::SplitBSplineSurface(a0, a1, a2, a3, a4, a5); }, py::arg("S"), py::arg("FromUK1"), py::arg("ToUK2"), py::arg("FromVK1"), py::arg("ToVK2"), py::arg("SameUOrientation"));
	cls_GeomConvert.def_static("SplitBSplineSurface_", (opencascade::handle<Geom_BSplineSurface> (*)(const opencascade::handle<Geom_BSplineSurface> &, const Standard_Integer, const Standard_Integer, const Standard_Integer, const Standard_Integer, const Standard_Boolean, const Standard_Boolean)) &GeomConvert::SplitBSplineSurface, "Computes the B-spline surface patche between the knots values FromUK1, ToUK2, FromVK1, ToVK2. If S is periodic in one direction the patche has the same orientation as S in this direction if the flag is true in this direction (SameUOrientation, SameVOrientation). If S is not periodic SameUOrientation and SameVOrientation are not used for the computation and S is oriented FromUK1 ToUK2 and FromVK1 ToVK2. Raised if FromUK1 = ToUK2 or FromVK1 = ToVK2 FromUK1 or ToUK2 are out of the bounds [FirstUKnotIndex, LastUKnotIndex] FromVK1 or ToVK2 are out of the bounds [FirstVKnotIndex, LastVKnotIndex]", py::arg("S"), py::arg("FromUK1"), py::arg("ToUK2"), py::arg("FromVK1"), py::arg("ToVK2"), py::arg("SameUOrientation"), py::arg("SameVOrientation"));
	cls_GeomConvert.def_static("SplitBSplineSurface_", [](const opencascade::handle<Geom_BSplineSurface> & a0, const Standard_Integer a1, const Standard_Integer a2, const Standard_Boolean a3) -> opencascade::handle<Geom_BSplineSurface> { return GeomConvert::SplitBSplineSurface(a0, a1, a2, a3); }, py::arg("S"), py::arg("FromK1"), py::arg("ToK2"), py::arg("USplit"));
	cls_GeomConvert.def_static("SplitBSplineSurface_", (opencascade::handle<Geom_BSplineSurface> (*)(const opencascade::handle<Geom_BSplineSurface> &, const Standard_Integer, const Standard_Integer, const Standard_Boolean, const Standard_Boolean)) &GeomConvert::SplitBSplineSurface, "This method splits a B-spline surface patche between the knots values FromK1, ToK2 in one direction. If USplit = True then the splitting direction is the U parametric direction else it is the V parametric direction. If S is periodic in the considered direction the patche has the same orientation as S in this direction if SameOrientation is True If S is not periodic in this direction SameOrientation is not used for the computation and S is oriented FromK1 ToK2. Raised if FromK1 = ToK2 or if FromK1 or ToK2 are out of the bounds [FirstUKnotIndex, LastUKnotIndex] in the considered parametric direction.", py::arg("S"), py::arg("FromK1"), py::arg("ToK2"), py::arg("USplit"), py::arg("SameOrientation"));
	cls_GeomConvert.def_static("SplitBSplineSurface_", [](const opencascade::handle<Geom_BSplineSurface> & a0, const Standard_Real a1, const Standard_Real a2, const Standard_Real a3, const Standard_Real a4, const Standard_Real a5) -> opencascade::handle<Geom_BSplineSurface> { return GeomConvert::SplitBSplineSurface(a0, a1, a2, a3, a4, a5); }, py::arg("S"), py::arg("FromU1"), py::arg("ToU2"), py::arg("FromV1"), py::arg("ToV2"), py::arg("ParametricTolerance"));
	cls_GeomConvert.def_static("SplitBSplineSurface_", [](const opencascade::handle<Geom_BSplineSurface> & a0, const Standard_Real a1, const Standard_Real a2, const Standard_Real a3, const Standard_Real a4, const Standard_Real a5, const Standard_Boolean a6) -> opencascade::handle<Geom_BSplineSurface> { return GeomConvert::SplitBSplineSurface(a0, a1, a2, a3, a4, a5, a6); }, py::arg("S"), py::arg("FromU1"), py::arg("ToU2"), py::arg("FromV1"), py::arg("ToV2"), py::arg("ParametricTolerance"), py::arg("SameUOrientation"));
	cls_GeomConvert.def_static("SplitBSplineSurface_", (opencascade::handle<Geom_BSplineSurface> (*)(const opencascade::handle<Geom_BSplineSurface> &, const Standard_Real, const Standard_Real, const Standard_Real, const Standard_Real, const Standard_Real, const Standard_Boolean, const Standard_Boolean)) &GeomConvert::SplitBSplineSurface, "This method computes the B-spline surface patche between the parametric values FromU1, ToU2, FromV1, ToV2. If S is periodic in one direction the patche has the same orientation as S in this direction if the flag is True in this direction (SameUOrientation, SameVOrientation). If S is not periodic SameUOrientation and SameVOrientation are not used for the computation and S is oriented FromU1 ToU2 and FromV1 ToV2. If U1 and U2 and two parametric values we consider that U1 = U2 if Abs (U1 - U2) <= ParametricTolerance and ParametricTolerance must be greater or equal to Resolution from package gp.", py::arg("S"), py::arg("FromU1"), py::arg("ToU2"), py::arg("FromV1"), py::arg("ToV2"), py::arg("ParametricTolerance"), py::arg("SameUOrientation"), py::arg("SameVOrientation"));
	cls_GeomConvert.def_static("SplitBSplineSurface_", [](const opencascade::handle<Geom_BSplineSurface> & a0, const Standard_Real a1, const Standard_Real a2, const Standard_Boolean a3, const Standard_Real a4) -> opencascade::handle<Geom_BSplineSurface> { return GeomConvert::SplitBSplineSurface(a0, a1, a2, a3, a4); }, py::arg("S"), py::arg("FromParam1"), py::arg("ToParam2"), py::arg("USplit"), py::arg("ParametricTolerance"));
	cls_GeomConvert.def_static("SplitBSplineSurface_", (opencascade::handle<Geom_BSplineSurface> (*)(const opencascade::handle<Geom_BSplineSurface> &, const Standard_Real, const Standard_Real, const Standard_Boolean, const Standard_Real, const Standard_Boolean)) &GeomConvert::SplitBSplineSurface, "This method splits the B-spline surface S in one direction between the parametric values FromParam1, ToParam2. If USplit = True then the Splitting direction is the U parametric direction else it is the V parametric direction. If S is periodic in the considered direction the patche has the same orientation as S in this direction if SameOrientation is true. If S is not periodic in the considered direction SameOrientation is not used for the computation and S is oriented FromParam1 ToParam2. If U1 and U2 and two parametric values we consider that U1 = U2 if Abs (U1 - U2) <= ParametricTolerance and ParametricTolerance must be greater or equal to Resolution from package gp.", py::arg("S"), py::arg("FromParam1"), py::arg("ToParam2"), py::arg("USplit"), py::arg("ParametricTolerance"), py::arg("SameOrientation"));
	cls_GeomConvert.def_static("CurveToBSplineCurve_", [](const opencascade::handle<Geom_Curve> & a0) -> opencascade::handle<Geom_BSplineCurve> { return GeomConvert::CurveToBSplineCurve(a0); }, py::arg("C"));
	cls_GeomConvert.def_static("CurveToBSplineCurve_", (opencascade::handle<Geom_BSplineCurve> (*)(const opencascade::handle<Geom_Curve> &, const Convert_ParameterisationType)) &GeomConvert::CurveToBSplineCurve, "This function converts a non infinite curve from Geom into a B-spline curve. C must be an ellipse or a circle or a trimmed conic or a trimmed line or a Bezier curve or a trimmed Bezier curve or a BSpline curve or a trimmed BSpline curve or an OffsetCurve. The returned B-spline is not periodic except if C is a Circle or an Ellipse. If the Parameterisation is QuasiAngular than the returned curve is NOT periodic in case a periodic Geom_Circle or Geom_Ellipse. For TgtThetaOver2_1 and TgtThetaOver2_2 the method raises an exception in case of a periodic Geom_Circle or a Geom_Ellipse ParameterisationType applies only if the curve is a Circle or an ellipse : TgtThetaOver2, -- TgtThetaOver2_1, -- TgtThetaOver2_2, -- TgtThetaOver2_3, -- TgtThetaOver2_4,", py::arg("C"), py::arg("Parameterisation"));
	cls_GeomConvert.def_static("SurfaceToBSplineSurface_", (opencascade::handle<Geom_BSplineSurface> (*)(const opencascade::handle<Geom_Surface> &)) &GeomConvert::SurfaceToBSplineSurface, "This algorithm converts a non infinite surface from Geom into a B-spline surface. S must be a trimmed plane or a trimmed cylinder or a trimmed cone or a trimmed sphere or a trimmed torus or a sphere or a torus or a Bezier surface of a trimmed Bezier surface or a trimmed swept surface with a corresponding basis curve which can be turned into a B-spline curve (see the method CurveToBSplineCurve). Raises DomainError if the type of the surface is not previously defined.", py::arg("S"));
	cls_GeomConvert.def_static("ConcatG1_", (void (*)(TColGeom_Array1OfBSplineCurve &, const TColStd_Array1OfReal &, opencascade::handle<TColGeom_HArray1OfBSplineCurve> &, const Standard_Boolean, const Standard_Real)) &GeomConvert::ConcatG1, "This Method concatenates G1 the ArrayOfCurves as far as it is possible. ArrayOfCurves[0..N-1] ArrayOfToler contains the biggest tolerance of the two points shared by two consecutives curves. Its dimension: [0..N-2] ClosedG1 indicates if the ArrayOfCurves is closed. In this case ClosedG1 contains the biggest tolerance of the two points which are at the closure. Otherwise its value is 0.0", py::arg("ArrayOfCurves"), py::arg("ArrayOfToler"), py::arg("ArrayOfConcatenated"), py::arg("ClosedG1Flag"), py::arg("ClosedTolerance"));
	cls_GeomConvert.def_static("ConcatC1_", (void (*)(TColGeom_Array1OfBSplineCurve &, const TColStd_Array1OfReal &, opencascade::handle<TColStd_HArray1OfInteger> &, opencascade::handle<TColGeom_HArray1OfBSplineCurve> &, const Standard_Boolean, const Standard_Real)) &GeomConvert::ConcatC1, "This Method concatenates C1 the ArrayOfCurves as far as it is possible. ArrayOfCurves[0..N-1] ArrayOfToler contains the biggest tolerance of the two points shared by two consecutives curves. Its dimension: [0..N-2] ClosedG1 indicates if the ArrayOfCurves is closed. In this case ClosedG1 contains the biggest tolerance of the two points which are at the closure. Otherwise its value is 0.0", py::arg("ArrayOfCurves"), py::arg("ArrayOfToler"), py::arg("ArrayOfIndices"), py::arg("ArrayOfConcatenated"), py::arg("ClosedG1Flag"), py::arg("ClosedTolerance"));
	cls_GeomConvert.def_static("ConcatC1_", (void (*)(TColGeom_Array1OfBSplineCurve &, const TColStd_Array1OfReal &, opencascade::handle<TColStd_HArray1OfInteger> &, opencascade::handle<TColGeom_HArray1OfBSplineCurve> &, const Standard_Boolean, const Standard_Real, const Standard_Real)) &GeomConvert::ConcatC1, "This Method concatenates C1 the ArrayOfCurves as far as it is possible. ArrayOfCurves[0..N-1] ArrayOfToler contains the biggest tolerance of the two points shared by two consecutives curves. Its dimension: [0..N-2] ClosedG1 indicates if the ArrayOfCurves is closed. In this case ClosedG1 contains the biggest tolerance of the two points which are at the closure. Otherwise its value is 0.0", py::arg("ArrayOfCurves"), py::arg("ArrayOfToler"), py::arg("ArrayOfIndices"), py::arg("ArrayOfConcatenated"), py::arg("ClosedG1Flag"), py::arg("ClosedTolerance"), py::arg("AngularTolerance"));
	cls_GeomConvert.def_static("C0BSplineToC1BSplineCurve_", [](opencascade::handle<Geom_BSplineCurve> & a0, const Standard_Real a1) -> void { return GeomConvert::C0BSplineToC1BSplineCurve(a0, a1); }, py::arg("BS"), py::arg("tolerance"));
	cls_GeomConvert.def_static("C0BSplineToC1BSplineCurve_", (void (*)(opencascade::handle<Geom_BSplineCurve> &, const Standard_Real, const Standard_Real)) &GeomConvert::C0BSplineToC1BSplineCurve, "This Method reduces as far as it is possible the multiplicities of the knots of the BSpline BS.(keeping the geometry). It returns a new BSpline which could still be C0. tolerance is a geometrical tolerance. The Angular toleranceis in radians and mesures the angle of the tangents on the left and on the right to decide if the curve is G1 or not at a given point", py::arg("BS"), py::arg("tolerance"), py::arg("AngularTolerance"));
	cls_GeomConvert.def_static("C0BSplineToArrayOfC1BSplineCurve_", (void (*)(const opencascade::handle<Geom_BSplineCurve> &, opencascade::handle<TColGeom_HArray1OfBSplineCurve> &, const Standard_Real)) &GeomConvert::C0BSplineToArrayOfC1BSplineCurve, "This Method reduces as far as it is possible the multiplicities of the knots of the BSpline BS.(keeping the geometry). It returns an array of BSpline C1. tolerance is a geometrical tolerance.", py::arg("BS"), py::arg("tabBS"), py::arg("tolerance"));
	cls_GeomConvert.def_static("C0BSplineToArrayOfC1BSplineCurve_", (void (*)(const opencascade::handle<Geom_BSplineCurve> &, opencascade::handle<TColGeom_HArray1OfBSplineCurve> &, const Standard_Real, const Standard_Real)) &GeomConvert::C0BSplineToArrayOfC1BSplineCurve, "This Method reduces as far as it is possible the multiplicities of the knots of the BSpline BS.(keeping the geometry). It returns an array of BSpline C1. tolerance is a geometrical tolerance : it allows for the maximum deformation The Angular tolerance is in radians and mesures the angle of the tangents on the left and on the right to decide if the curve is C1 or not at a given point", py::arg("BS"), py::arg("tabBS"), py::arg("AngularTolerance"), py::arg("tolerance"));


}
